const props = {
  profileData: {
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '29, 5\' 10"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Muslim, Sunni',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Bengali',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Team Member / Staff',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Matrah, Oman',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '29 yrs, 5\' 10", Muslim, Bengali',
        },
        {
          key: 'profession',
          value: 'Team Member / Staff',
        },
        {
          key: 'location',
          value: 'Lives in Matrah, Oman',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India, Pakistan, United Kingdom, USA, Bangladesh',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '29, 5\' 10"',
        },
        {
          key: 'religion-caste',
          value: 'Muslim, Sunni',
        },
        {
          key: 'profession',
          value: 'Team Member / Staff',
        },
        {
          key: 'location',
          value: 'Matrah, Oman',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '29 yrs, 5\' 10", Muslim, Bengali',
        },
        {
          key: 'location',
          value: 'Matrah, Oman',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '29 yrs, 5\' 10", Muslim, Bengali',
        },
        {
          key: 'religion-caste',
          value: 'Sunni',
        },
        {
          key: 'location',
          value: 'Lives in Matrah, Oman',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '29 yrs, 5\' 10", Muslim, Bengali',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India, Pakistan, United Kingdom, USA, Bangladesh',
        },
        {
          key: 'location',
          value: 'Lives in Matrah, Oman',
        },
      ],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'accepted',
      connectionAction: 'member_accepted',
      connectionJustNowText: null,
      contactAction: 'available',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: false,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'invisible',
      onlineStatusDetails: '...',
      onlineAt: 0,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: '...',
      ready: false,
      chatIcon: 'none',
    },
    summary: {
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '29, 5\' 10"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Muslim',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Bengali',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Sunni',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Matrah, Oman',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Education',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Team Member / Staff',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '29, 5\' 10"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Muslim',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Bengali',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Matrah,Masqat, Oman',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India, Pakistan, United Kingdom, USA, Bangladesh',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Education',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Team Member / Staff',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '29 yrs, 5\' 10"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Muslim, Sunni',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Matrah, Oman',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Bengali',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Team Member / Staff',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '29 yrs, 5\' 10"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Team Member / Staff',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Muslim, Bengali',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Matrah,Masqat, Oman',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Education',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India, Pakistan, United Kingdom, USA, Bangladesh',
        },
      ],
      listAlbum: [],
      gridAlbum: [],
      shortBio: "I'm live in Muscat oman. I'm alone.  My father and mother no more. I like honest beautiful Muslim girl .",
      createdBy: 'Self',
      profileCreatedBy: 'Self',
      shortlistCount: -1,
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: 'Msg from Sami L (SH88709866): Hi, I liked the Profile that you have posted on Shaadi.com. Please visit my Profile and respond.',
      contact: {
        profileid: 'nSH37634787',
        convenient_time: '',
        from_time_hours: 0,
        from_time_min: 0,
        last_update_date: 20161209003134,
        mob_isd: '+968',
        mob_std: '',
        mobile: '93175558',
        mobile_country: 'Oman',
        mobile_verified: 'Y',
        name: '',
        relation: '',
        tel_isd: '+968',
        tel_std: '',
        telephone: '',
        telephone_country: 'Oman',
        telephone_verified: 'N',
        timezone: '',
        to_time_hours: 0,
        to_time_min: 0,
        contact_details_status: 'show_all',
        contact_details_title_status: 'show_all',
      },
      actionDate: '05 Sep 2017',
      dnd: 'N',
      hidden: 'N',
      hiddenReason: false,
      tempKey: 'bef182c3bc31db1ed70d91f0e3de11bb',
      contactType: 'Contact_viewed',
      photoStatus: 'show_photo',
      photoCount: 20,
      profileContactStatus: 'accepted',
      contactDetailsStatusString: 'available',
      contactDetailsTitleStatusString: 'available',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2016/12/09/nSH37634787-e586c0.jpg',
    thumbnail: 'https://img1.shaadi.com/2016/12/09/nSH37634787-e586c0.jpg',
    photoBlur: 'https://img1.shaadi.com/2016/12/09/nSH37634787-14be0a.jpg',
    photoMedium: '/assets/default-photo.png',
    photo: 'https://img1.shaadi.com/2016/12/09/nSH37634787-14be0a.jpg',
    fullPhotoBlur: 'https://img1.shaadi.com/2016/12/09/nSH37634787-695367.jpg',
    fullPhoto: 'https://img1.shaadi.com/2016/12/09/nSH37634787-695367.jpg',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    se: 'f3f3102e94e20003cf876efc34dce1ab',
    uid: 'nSH37634787',
    name: 'Mamunur Rashid Ashik',
    fullName: 'Mamunur rashid Ashik',
    firstName: 'Mamunur rashid',
    lastName: 'Ashik',
    slug: 'nSH37634787',
    userHandle: 'SH37634787',
    location: 'Matrah, Oman',
    mrMs: 'Mr.',
  },
  meta: {
    loading: false,
    results_id: 'contacts:9d347dde80ed5c27569f7d50163d3e1d',
    total: 108,
    page: '8',
    pages: 11,
    permaLink: '/inbox/contact-summary?pg_searchresults_id=contacts%3A9d347dde80ed5c27569f7d50163d3e1d&page=8',
  },
  settings: {
    defaultSearchFormat: 'grid',
    isPaidUser: true,
    showUpgradeBanner: false,
    canAccessChat: true,
    canInitiateChat: true,
    hasUploadedPhoto: true,
    canConnectWithMessage: true,
    showUpgradeLinks: false,
    canSendPasswordOnConnect: false,
    contactsTotal: 270,
    contactsRemaining: 97,
    isUnderScreening: false,
    isAstroGamified: false,
    gender: 'Female',
    canViewCollegeAndEmployer: true,
    canViewHoroscope: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: true,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '8767676565',
    wasPaidUser: false,
    expiryDate: '04-Mar-18',
    isNri: true,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'C',
      },
    },
    membershipTags: 'gold',
    offerCode: 'match15to1',
    offer_details: '',
  },
  type: 'profile',
  wwwBaseUrl: 'https://www.shaadi.com',
  albumUrl: 'https://www.shaadi.com/profile/index/view-album-photos/profileid/nSH37634787',
  tooltip: {
    key: 'none',
    page: 'none',
    position: 'none',
    title: null,
    body: [],
    loading: false,
  },
  isTooltipVisible: false,
  loading: false,
  changeCursorStatus: true,
  viewSmsShowStatus: false,
  doProfileAction() {},
  onTooltipClose() {},
};

const factory = { props };

it('should export props', () => {
  expect(Object.keys(factory).length).toEqual(1);
});
export default factory;
