/* eslint-disable camelcase, max-len */
const F_PAY_dr = {
  data: [
    {
      memberlogin: 'XSH32931119',
      action: '',
      action_date: 0,
      account: {
        status: 'Active',
        last_login_date: 20171228180621,
        profile_created: 20171215084545,
        profile_activated: 20171215091416,
        posted_by: 'Parent / Guardian',
        membership: ['Free Member'],
        hide_till: 0,
        screened: 'Y',
        hidden: 'N',
        astro_profile: 'N',
        memberlogin: 'XSH32931119',
        membership_tag: 'free',
      },
      basic: {
        username: 'SH32931119',
        display_name: 'Solanki K',
        first_name: 'solanki',
        last_name: 'kirit',
        gender: 'Male',
        age: '23',
        marital_status: 'Widowed',
        date_of_birth: 19941025,
      },
      trait: {
        personal_values: '',
        about_me:
          "Hello, am glad you are interested in my son's profile.\r\nHe has completed his Masters.My son's genuineness, caring and affectionate nature, wins his friends in every walk of life.I envision my son's life-partner to be good in nature with modest upbringing and importantly one who believes in the institution of marriage.",
        personality: [],
      },
      health_info: { special_cases: 'None', blood_group: '', ailments: '' },
      appearance: { complexion: 'Very Fair', built: 'Slim', height: 53, weight: '' },
      lifestyle: { diet: 'Non-Veg', drink: 'Yes', smoke: 'Yes' },
      doctrine: {
        religion: 'Parsi',
        caste: 'Parsi',
        sub_caste: '-',
        mother_tongue: 'Gujarati',
        gotra: '-',
        amritdhari: '',
        dastar: '',
        fasting: '',
        keshdhari: '',
        muslim_from_birth: '',
        namaaz: '',
        religious_values: '',
        zakaat: '',
        caste_no_bar: '',
      },
      location: {
        country: 'India',
        state: 'Bihar',
        district: 'Bihar Sharif',
        residency_status: 'Citizen',
        zip_code: '',
        country_code: '',
        city_google: '',
        living_since: '',
        city: 'Bihar Sharif',
        locality: '0',
      },
      education: {
        education: 'Masters - Armed Forces',
        education_stream: 'Armed Forces',
        college_university: '',
        college_1: 'null',
        valid_college_1: 'No',
        college_2: 'null',
        valid_college_2: 'No',
      },
      profession: {
        occupation: 'Banking Professional',
        industry: 'Accounting, Banking & Finance',
        working_with: 'Private Company',
        income_old: 'Rs 1 lakh to 2 lakhs',
        income: 'INR 1 Lakh to 2 Lakh',
        income_currency: 'INR',
        linkedin_employerid: 0,
        employer: 'null',
        valid_employer: 'No',
        income_hidden: '',
      },
      family: {
        children: 'Yes. Living together',
        cultural_values: '',
        about: 'null',
        father_profession: 'Employed',
        mother_profession: 'Homemaker',
        brothers: '1',
        brothers_married: '1',
        sisters: '1',
        sisters_married: '1',
        affluence: 0,
        no_of_kids: '1',
        type: '',
        located: '',
        father_employer: '',
        father_designation: '',
        about_father: '',
        mother_employer: '',
        mother_designation: '',
        about_mother: '',
        family_income: '',
        is_family_gamified: 'N',
      },
      origin: { grewup_in: ['India'], native_place: '', ethnicity: 'India' },
      interests_and_more: {
        hobbies: ['null'],
        interests: ['null'],
        cuisine: ['null'],
        music: ['null'],
        movies: ['null'],
        reads: ['null'],
        sports: ['null'],
        dress_style: ['null'],
        can_speak: ['null'],
      },
      photo_details: {
        count: 0,
        photos: [
          {
            domain_name: 'https://img2.shaadi.com',
            small: '/imgs/profiles/60-request-photo-m.gif',
            medium: '/imgs/profiles/150-photo-request-m.gif',
            semilarge: '/imgs/profiles/250-photo-request-m.gif',
            '120X120': '',
            '450X600': '',
            '250X310': '/imgs/profiles/250-photo-request-m.gif',
            small_nb: '/imgs/profiles/60-no-border-male.gif',
            domain_name_nb: 'https://img2.shaadi.com',
            medium_nb: '/imgs/profiles/150-no-border-male.gif',
            '120X120_nb': '',
          },
        ],
        status: 'photo_request',
      },
      connect: {},
      other: { se: '06599c28af45f2f879a8c47980605405', is_name_lock: 'Y' },
      recommendation: { memberlogin: 'XSH32931119', action: '', action_date: 0 },
    },
    {
      memberlogin: 'eSH96535039',
      action: '',
      action_date: 0,
      account: {
        status: 'Active',
        last_login_date: 20171229112216,
        profile_created: 20171228112054,
        profile_activated: 20171228114116,
        posted_by: 'Self',
        membership: ['Free Member', 'Bold Listing'],
        hide_till: 0,
        screened: 'Y',
        hidden: 'N',
        astro_profile: 'N',
        memberlogin: 'eSH96535039',
        membership_tag: 'free',
      },
      basic: {
        username: 'SH96535039',
        display_name: 'Aswin K',
        first_name: 'Aswin',
        last_name: 'kumar',
        gender: 'Male',
        age: '24',
        marital_status: 'Never Married',
        date_of_birth: 19930621,
      },
      trait: {
        personal_values: '',
        about_me: "I'm simple person. I like a normal homely girl. I'm only one son for my parents. I search a lovable girl to care my mom",
        personality: [],
      },
      health_info: { special_cases: 'None', blood_group: '', ailments: '' },
      appearance: { complexion: 'Fair', built: 'Slim', height: 60, weight: '' },
      lifestyle: { diet: 'Veg', drink: 'No', smoke: 'No' },
      doctrine: {
        religion: 'Hindu',
        caste: 'Brahmin - Iyer',
        sub_caste: '-',
        mother_tongue: 'Tamil',
        gotra: 'Bharadwaj',
        amritdhari: '',
        dastar: '',
        fasting: '',
        keshdhari: '',
        muslim_from_birth: '',
        namaaz: '',
        religious_values: '',
        zakaat: '',
        caste_no_bar: '',
      },
      location: {
        country: 'India',
        state: 'Tamil Nadu',
        district: 'Chennai',
        residency_status: 'Citizen',
        zip_code: '',
        country_code: '',
        city_google: '',
        living_since: '',
        city: 'Chennai',
        locality: '0',
      },
      education: {
        education: 'Bachelors - Engineering/ Technology',
        education_stream: 'Engineering/ Technology',
        college_university: '',
        college_1: 'PRIST University Thanjavur',
        valid_college_1: 'Yes',
        college_2: '',
        valid_college_2: 'No',
      },
      profession: {
        occupation: 'Training Professional (Others)',
        industry: 'Education & Training',
        working_with: 'Private Company',
        income_old: 'Rs 1 lakh to 2 lakhs',
        income: 'INR 1 Lakh to 2 Lakh',
        income_currency: 'INR',
        linkedin_employerid: 0,
        employer: '',
        valid_employer: 'No',
        income_hidden: '',
      },
      family: {
        children: 'No',
        cultural_values: '',
        about: 'null',
        father_profession: 'Retired',
        mother_profession: 'Homemaker',
        brothers: '0',
        brothers_married: '',
        sisters: '0',
        sisters_married: '',
        affluence: 'Middle Class',
        no_of_kids: '0',
        type: '',
        located: '',
        father_employer: '',
        father_designation: '',
        about_father: '',
        mother_employer: '',
        mother_designation: '',
        about_mother: '',
        family_income: '',
        is_family_gamified: 'N',
      },
      origin: { grewup_in: ['India'], native_place: '', ethnicity: 'India' },
      interests_and_more: {
        hobbies: ['null'],
        interests: ['null'],
        cuisine: ['null'],
        music: ['null'],
        movies: ['null'],
        reads: ['null'],
        sports: ['null'],
        dress_style: ['null'],
        can_speak: ['null'],
      },
      photo_details: {
        count: 1,
        photos: [
          {
            domain_name: 'https://img1.shaadi.com',
            small: '/2017/12/28/eSH96535039-277bf0-male.jpg',
            medium: '/2017/12/28/eSH96535039-290937-Male.jpg',
            semilarge: '/2017/12/28/eSH96535039-ffe7eb-male.jpg',
            status: 'Y',
            photo_order: 0,
            profile_photo: true,
            '120X120': '/2017/12/28/eSH96535039-d9fde1-male.jpg',
            '250X310': '/2017/12/28/eSH96535039-ffe7eb-male.jpg',
            '450X600': '/2017/12/28/eSH96535039-d2a56c-male.jpg',
            small_nb: '/2017/12/28/eSH96535039-277bf0-male.jpg',
            domain_name_nb: 'https://img1.shaadi.com',
            medium_nb: '/2017/12/28/eSH96535039-290937-Male.jpg',
            semilarge_nb: '/2017/12/28/eSH96535039-ffe7eb-male.jpg',
            '120X120_nb': '/2017/12/28/eSH96535039-d9fde1-male.jpg',
            '250X310_nb': '/2017/12/28/eSH96535039-ffe7eb-male.jpg',
            '450X600_nb': '/2017/12/28/eSH96535039-d2a56c-male.jpg',
          },
        ],
        status: 'show_photo',
      },
      connect: {},
      other: { se: 'fa15a4009453ed8269e4ef803285afa0', is_name_lock: 'Y' },
      recommendation: { memberlogin: 'eSH96535039', action: '', action_date: 0 },
    },
  ],
  remainingTime: 39403,
  totalCount: 7,
};
const F_EXP_dr = {
  profiles: [
    {
      se: '06599c28af45f2f879a8c47980605405',
      uid: 'XSH32931119',
      name: 'Solanki K',
      slug: 'XSH32931119',
      thumbnail: 'https://img2.shaadi.com/imgs/profiles/60-no-border-male.gif',
      photo: 'https://img2.shaadi.com/imgs/profiles/150-no-border-male.gif',
      fullPhoto: '/assets/60-add-ph-male-v2.gif',
      thumbnailBlur: 'https://img2.shaadi.com/imgs/profiles/60-request-photo-m.gif',
      photoBlur: 'https://img2.shaadi.com/imgs/profiles/150-photo-request-m.gif',
      fullPhotoBlur: 'https://img2.shaadi.com/imgs/profiles/250-photo-request-m.gif',
      userHandle: 'SH32931119',
      gender: 'Male',
      marital_status: 'Widowed',
      connectMessages: [],
      contact: {},
      horoscopeScore: {},
      flags: {
        membershipLevel: 'Free',
        membershipTags: 'free',
        isBoldListing: false,
        isDeleted: false,
        connectionStatus: 'shortlisted',
        connectionAction: null,
        connectionNote: null,
        contactStatus: null,
        contactAction: null,
        horoscopeStatus: null,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'noPhoto',
        isWatermarked: false,
        isTwoWayMatch: false,
        activeStatus: 'default',
        isNri: false,
        isIndianDiaspora: true,
        isHoroscopeApplicable: false,
        isFamilyGamified: false,
        isAstroReady: false,
        isSameGender: false,
        canCancelInvite: false,
        canRemind: false,
        canUnblock: false,
        isHidden: false,
        isBothPartyPayUser: false,
        isNameLocked: true,
        isSkipped: false,
      },
      base: {
        infoMap: [
          { key: 'info-0', label: 'Age / Height', value: '23, 4\' 5"' },
          { key: 'info-1', label: 'Religion/Community', value: 'Parsi, Parsi' },
          { key: 'info-2', label: 'Mother Tounge', value: 'Gujarati' },
          { key: 'info-3', label: 'Profession', value: 'Banking Professional' },
          { key: 'info-4', label: 'Location', value: 'Bihar Sharif, India' },
        ],
        infoList: [
          { key: 'age-height', value: '23 yrs, 4\' 5", Parsi, Gujarati' },
          { key: 'profession', value: 'Banking Professional' },
          { key: 'location', value: 'Lives in Bihar Sharif, India' },
          { key: 'grew up in', value: 'Grew up in India' },
        ],
        miniNriList: [
          { key: 'age-height', value: '23 yrs, 4\' 5", Parsi, Gujarati' },
          { key: 'grew up in', value: 'Grew up in India' },
          { key: 'location', value: 'Lives in Bihar Sharif, India' },
        ],
        miniList: [
          { key: 'age-height', value: '23 yrs, 4\' 5", Parsi, Gujarati' },
          { key: 'religion-caste', value: 'Not Specified' },
          { key: 'location', value: 'Lives in Bihar Sharif, India' },
        ],
        detailList: [
          { key: 'age-height', value: '23, 4\' 5"' },
          { key: 'religion-caste', value: 'Parsi, Not Specified' },
          { key: 'profession', value: 'Banking Professional' },
          { key: 'location', value: 'Bihar Sharif, India' },
        ],
        premiumInfo: [{ key: 'age-height', value: '23 yrs, 4\' 5", Parsi, Gujarati' }, { key: 'location', value: 'Bihar Sharif, India' }],
      },
      presence: null,
      summary: {
        shortBio:
          "Hello, am glad you are interested in my son's profile.\r\nHe has completed his Masters.My son's genuineness, caring and affectionate nature, wins his friends in every walk of life.I envision my son's life-partner to be good in nature with modest upbringing and importantly one who believes in the institution of marriage.",
        createdBy: 'Parent / Guardian',
        profileCreatedBy: 'Parent',
        shortlistCount: -1,
        infoMap: [
          { key: 'age_height', label: 'Age / Height', value: '23, 4\' 5"' },
          { key: 'religion', label: 'Religion', value: 'Parsi' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Gujarati' },
          { key: 'community', label: 'Community', value: 'Parsi' },
          { key: 'location', label: 'Location', value: 'Bihar Sharif, India' },
          { key: 'education', label: 'Education', value: 'Masters - Armed Forces' },
          { key: 'profession', label: 'Profession', value: 'Banking Professional' },
        ],
        infoMapNonIndian: [
          { key: 'age_height', label: 'Age / Height', value: '23, 4\' 5"' },
          { key: 'religion', label: 'Religion', value: 'Parsi' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Gujarati' },
          { key: 'location_nri_info', label: 'Location', value: 'Bihar Sharif,Bihar, India' },
          { key: 'info-6', label: 'Grew up in', value: 'India' },
          { key: 'education', label: 'Education', value: 'Masters - Armed Forces' },
          { key: 'profession', label: 'Profession', value: 'Banking Professional' },
        ],
        infoMapIndian: [
          { key: 'age_height_list', label: 'Age / Height', value: '23 yrs, 4\' 5"' },
          { key: 'marital_status', label: 'Marital Status', value: 'Widowed (Children: Yes. Living together)' },
          { key: 'religion_caste_list', label: 'Religion', value: 'Parsi, Parsi' },
          { key: 'location', label: 'Location', value: 'Bihar Sharif, India' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Gujarati' },
          { key: 'profession', label: 'Profession', value: 'Banking Professional' },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '23 yrs, 4\' 5"' },
          { key: 'profession', label: 'Profession', value: 'Banking Professional' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Parsi, Gujarati' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Bihar Sharif,Bihar, India' },
          { key: 'education', label: 'Education', value: 'Masters - Armed Forces' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
      },
      detailed: null,
      tempId: '',
      fullName: 'solanki kirit',
      firstName: 'solanki',
      lastName: 'kirit',
      location: 'Bihar Sharif, India',
      request: {},
      recommendation: { memberlogin: 'XSH32931119', action: '', action_date: 0 },
    },
    {
      se: 'fa15a4009453ed8269e4ef803285afa0',
      uid: 'eSH96535039',
      name: 'Aswin K',
      slug: 'eSH96535039',
      thumbnail: 'https://img1.shaadi.com/2017/12/28/eSH96535039-d9fde1-male.jpg',
      photo: 'https://img1.shaadi.com/2017/12/28/eSH96535039-d2a56c-male.jpg',
      fullPhoto: 'https://img1.shaadi.com/2017/12/28/eSH96535039-ffe7eb-male.jpg',
      thumbnailBlur: 'https://img1.shaadi.com/2017/12/28/eSH96535039-d9fde1-male.jpg',
      photoBlur: 'https://img1.shaadi.com/2017/12/28/eSH96535039-d2a56c-male.jpg',
      fullPhotoBlur: 'https://img1.shaadi.com/2017/12/28/eSH96535039-ffe7eb-male.jpg',
      userHandle: 'SH96535039',
      gender: 'Male',
      marital_status: 'Never Married',
      connectMessages: [],
      contact: {},
      horoscopeScore: {},
      flags: {
        membershipLevel: 'Free',
        membershipTags: 'free',
        isBoldListing: true,
        isDeleted: false,
        connectionStatus: 'shortlisted',
        connectionAction: null,
        connectionNote: null,
        contactStatus: null,
        contactAction: null,
        horoscopeStatus: null,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isWatermarked: true,
        isTwoWayMatch: false,
        activeStatus: 'default',
        isNri: false,
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: false,
        isSameGender: false,
        canCancelInvite: false,
        canRemind: false,
        canUnblock: false,
        isHidden: false,
        isBothPartyPayUser: false,
        isNameLocked: true,
        isSkipped: false,
      },
      base: {
        infoMap: [
          { key: 'info-0', label: 'Age / Height', value: '24, 5\' 0"' },
          { key: 'info-1', label: 'Religion/Community', value: 'Hindu, Brahmin - Iyer' },
          { key: 'info-2', label: 'Mother Tounge', value: 'Tamil' },
          { key: 'info-3', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'info-4', label: 'Location', value: 'Chennai, India' },
        ],
        infoList: [
          { key: 'age-height', value: '24 yrs, 5\' 0", Hindu, Tamil' },
          { key: 'profession', value: 'Training Professional (Others)' },
          { key: 'location', value: 'Lives in Chennai, India' },
          { key: 'grew up in', value: 'Grew up in India' },
        ],
        miniNriList: [
          { key: 'age-height', value: '24 yrs, 5\' 0", Hindu, Tamil' },
          { key: 'grew up in', value: 'Grew up in India' },
          { key: 'location', value: 'Lives in Chennai, India' },
        ],
        miniList: [
          { key: 'age-height', value: '24 yrs, 5\' 0", Hindu, Tamil' },
          { key: 'religion-caste', value: 'Brahmin - Iyer' },
          { key: 'location', value: 'Lives in Chennai, India' },
        ],
        detailList: [
          { key: 'age-height', value: '24, 5\' 0"' },
          { key: 'religion-caste', value: 'Hindu, Brahmin - Iyer' },
          { key: 'profession', value: 'Training Professional (Others)' },
          { key: 'location', value: 'Chennai, India' },
        ],
        premiumInfo: [{ key: 'age-height', value: '24 yrs, 5\' 0", Hindu, Tamil' }, { key: 'location', value: 'Chennai, India' }],
      },
      presence: null,
      summary: {
        shortBio: "I'm simple person. I like a normal homely girl. I'm only one son for my parents. I search a lovable girl to care my mom",
        createdBy: 'Self',
        profileCreatedBy: 'Self',
        shortlistCount: -1,
        infoMap: [
          { key: 'age_height', label: 'Age / Height', value: '24, 5\' 0"' },
          { key: 'religion', label: 'Religion', value: 'Hindu' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Tamil' },
          { key: 'community', label: 'Community', value: 'Brahmin - Iyer' },
          { key: 'location', label: 'Location', value: 'Chennai, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
        ],
        infoMapNonIndian: [
          { key: 'age_height', label: 'Age / Height', value: '24, 5\' 0"' },
          { key: 'religion', label: 'Religion', value: 'Hindu' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Tamil' },
          { key: 'location_nri_info', label: 'Location', value: 'Chennai,Tamil Nadu, India' },
          { key: 'info-6', label: 'Grew up in', value: 'India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
        ],
        infoMapIndian: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'marital_status', label: 'Marital Status', value: 'Never Married' },
          { key: 'religion_caste_list', label: 'Religion', value: 'Hindu, Brahmin - Iyer' },
          { key: 'location', label: 'Location', value: 'Chennai, India' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Tamil' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
      },
      detailed: null,
      tempId: '',
      fullName: 'Aswin kumar',
      firstName: 'Aswin',
      lastName: 'kumar',
      location: 'Chennai, India',
      request: {},
      recommendation: { memberlogin: 'eSH96535039', action: '', action_date: 0 },
    },
  ],
  defaultProfileId: 'XSH32931119',
  timeLeftToConnect: 39403,
  nextDefaultProfileId: 'eSH96535039',
};

const factory = {
  F_PAY_dr,
  F_EXP_dr,
};

it('should export profiles and props', () => {
  expect(Object.keys(factory).length).toEqual(2);
});

export default factory;
