const props = {
  profile: {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: false,
      isPremium: false,
      membershipLevel: 'none',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'unknown',
      connectionAction: 'not_contacted',
      connectionJustNowText: null,
      contactAction: 'none',
      contactStatus: 'none',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: false,
      isWatermarked: false,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'none',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      canCommunicate: false,
    },
    presence: {
      onlineStatus: 'invisible',
      onlineStatusDetails: '...',
      onlineAt: 0,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: '...',
      lastOnlineStatus: '...',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'none',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: '/assets/default-thumbnail.png',
    thumbnail: '/assets/default-thumbnail.png',
    photoBlur: '/assets/default-photo.png',
    photoMedium: '/assets/default-photo.png',
    photo: '/assets/default-photo.png',
    fullPhotoBlur: '/assets/default-full-photo.png',
    fullPhoto: '/assets/default-full-photo.png',
    drAction: {},
    heShe: '...',
    himHer: '...',
    hisHer: '...',
    gender: null,
    tempId: '',
    verification: {
      count: 0,
      shield_state: '',
      derived_text: '',
      verified_proofs: [],
    },
    uid: null,
    name: '...',
  },
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: true,
    showUpgradeBanner: false,
    canAccessChat: true,
    canInitiateChat: true,
    hasUploadedPhoto: true,
    canConnectWithMessage: true,
    showUpgradeLinks: false,
    canSendPasswordOnConnect: false,
    contactsTotal: 75,
    contactsRemaining: 16,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: true,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: false,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: true,
    mobileNumber: '9856989898',
    wasPaidUser: false,
    expiryDate: '02-Apr-18',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'B',
      },
      profile_verification: {
        bucket: 'B',
      },
      offline_otp: {
        bucket: 'A',
      },
      inbox_revamp: {
        bucket: 'B',
      },
      track_events: {
        bucket: 'A',
      },
    },
    membershipTags: 'gold',
    offerCode: 'match15to1',
    offer_details: '',
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  canInitiateChat: true,
  canShowUpgradeLink: false,
  source: 'none',
  isVisible: false,
  hoverCard: {
    uid: null,
    loading: false,
    flash: null,
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    photoLoading: false,
    eoiLoadingStyle: 'none',
  },

  doChatWindowAction() {},
  onAction() {},
  onProfileAction() {},
};

const freeUserProps = {
  profile: {
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '28, 5\' 7"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Hindu, Brahmin - Sakaldwipi',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Punjabi',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Finance Professional',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Jalandhar, India',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 7", Hindu, Punjabi',
        },
        {
          key: 'profession',
          value: 'Finance Professional',
        },
        {
          key: 'location',
          value: 'Lives in Jalandhar, India',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '28, 5\' 7"',
        },
        {
          key: 'religion-caste',
          value: 'Hindu, Brahmin - Sakaldwipi',
        },
        {
          key: 'profession',
          value: 'Finance Professional',
        },
        {
          key: 'location',
          value: 'Jalandhar, India',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 7", Hindu, Punjabi',
        },
        {
          key: 'location',
          value: 'Jalandhar, India',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 7", Hindu, Punjabi',
        },
        {
          key: 'religion-caste',
          value: 'Brahmin - Sakaldwipi',
        },
        {
          key: 'location',
          value: 'Lives in Jalandhar, India',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 7", Hindu, Punjabi',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
        {
          key: 'location',
          value: 'Lives in Jalandhar, India',
        },
      ],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'default',
      connectionAction: 'not_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: false,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: true,
      canSendEmail: true,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: true,
      showPostOnWall: true,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/HIN/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: true,
      isFamilyGamified: false,
      isAstroReady: true,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
      canCommunicate: false,
    },
    presence: {
      onlineStatus: 'Online',
      onlineStatusDetails: '...',
      onlineAt: 1521783760000,
      device: 'mobile_native-iphone',
      platform: 'mobile',
      lastOnline: 'Online on iPhone App',
      lastOnlineDetails: 'Online now',
      ready: false,
      chatIcon: 'app_online',
    },
    summary: {
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '28, 5\' 7"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Brahmin - Sakaldwipi',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Jalandhar, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Arts',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Finance Professional',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '28, 5\' 7"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Jalandhar,Punjab, India',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Arts',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Finance Professional',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '28 yrs, 5\' 7"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Hindu, Brahmin - Sakaldwipi',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Jalandhar, India',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Finance Professional',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '28 yrs, 5\' 7"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Finance Professional',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Hindu, Punjabi',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Jalandhar,Punjab, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Arts',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India',
        },
      ],
      listAlbum: [],
      gridAlbum: [],
      shortBio: "Hello and welcome to my brother's profile!\r\n\r\nDilip is a caring and fun-loving gentleman.",
      createdBy: 'Parent / Guardian',
      profileCreatedBy: 'Parent',
      shortlistCount: -1,
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2018/03/15/TSH96052980-2612e8-male.webp',
    thumbnail: 'https://img1.shaadi.com/2018/03/15/TSH96052980-2612e8-male.webp',
    photoBlur: 'https://img1.shaadi.com/2018/03/15/TSH96052980-adf191-male.webp',
    photoMedium: '/assets/default-photo.png',
    photo: 'https://img1.shaadi.com/2018/03/15/TSH96052980-adf191-male.webp',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/03/15/TSH96052980-489e9b-male.webp',
    fullPhoto: 'https://img1.shaadi.com/2018/03/15/TSH96052980-489e9b-male.webp',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 0,
      shield_state: '',
      derived_text: '',
      verified_proofs: [],
    },
    se: '33cba89edcc17dd28876c044c1917622',
    uid: 'TSH96052980',
    name: 'Dilip K',
    fullName: 'dilip kumar',
    firstName: 'dilip',
    lastName: 'kumar',
    slug: 'TSH96052980',
    userHandle: 'SH96052980',
    location: 'Jalandhar, India',
    mrMs: 'Mr.',
  },
  settings: {
    defaultSearchFormat: 'grid',
    isPaidUser: false,
    showUpgradeBanner: true,
    canAccessChat: true,
    canInitiateChat: false,
    hasUploadedPhoto: false,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: 0,
    contactsRemaining: -25,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: false,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '8966565656',
    wasPaidUser: false,
    expiryDate: '',
    isNri: true,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'A',
      },
      offline_otp: {
        bucket: 'A',
      },
      inbox_revamp: {
        bucket: 'A',
      },
      track_events: {
        bucket: 'A',
      },
    },
    membershipTags: 'free',
    offerCode: 'foreversunh3',
    offer_details: [
      {
        type: 'perc',
        value: 60,
      },
    ],
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  canInitiateChat: false,
  canShowUpgradeLink: true,
  source: 'online',
  isVisible: false,
  hoverCard: {
    uid: null,
    loading: false,
    flash: null,
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    photoLoading: false,
    eoiLoadingStyle: 'none',
  },
  doChatWindowAction() {},
  onAction() {},
  onProfileAction() {},
};

const factory = { props, freeUserProps };

it('should export premiumprops and freeUserProps', () => {
  expect(factory.props).not.toBeFalsy();
  expect(factory.freeUserProps).not.toBeFalsy();
});

export default factory;
