const profileA = {
  flags: {
    isFree: false,
    isPremium: true,
    membershipLevel: 'PremiumPlus',
    connectionNote: null,
    connectionError: false,
    connectionStatus: 'theyAccepted',
    connectionAction: 'profile_accepted',
    connectionJustNowText: null,
    contactAction: 'free',
    contactStatus: 'available',
    horoscopeStatus: 'none',
    loading: 'none',
    isDeleted: false,
    isNri: false,
    isWatermarked: true,
    isTwoWayMatch: false,
    isBoldListing: true,
    canUnblock: false,
    unblockMessage: null,
    canUnignore: false,
    canRemind: false,
    canCancelInvite: true,
    isSameGender: false,
    activeStatus: 'default',
    isPreferredMatch: false,
    isConnectLimitExceeded: false,
    showHistory: false,
    membershipTags: 'diamond_plus',
    isNameLocked: true,
    canCallSendSMS: false,
    canSendEmail: false,
    canSendEmailReminder: false,
    canSendSMS: false,
    canViewPhoneNo: false,
    isPhoneNoViewed: false,
    isSmsAlreadySent: false,
    showChatNow: false,
    showPostOnWall: false,
    isFiltered: false,
    horoscopeStyle: 'l//hs/1',
    albumStatus: 'default',
    isIndianDiaspora: true,
    isHoroscopeApplicable: true,
    isFamilyGamified: false,
    isAstroReady: false,
    isHidden: false,
    isBothPartyPayUser: false,
  },
  presence: {
    onlineStatus: 'Online',
    onlineStatusDetails: 'Online',
    onlineAt: 1512625304000,
    device: 'mobile_native-android',
    platform: 'mobile',
    lastOnline: 'Online on Android App',
    lastOnlineDetails: 'Online now',
    ready: false,
    chatIcon: 'web_online',
  },
  summary: {
    infoMap: [
      {
        key: 'age_height',
        label: 'Age / Height',
        value: '31, 5\' 9"',
      },
      {
        key: 'religion',
        label: 'Religion',
        value: 'Hindu',
      },
      {
        key: 'mother_tongue',
        label: 'Mother Tongue',
        value: 'Hindi',
      },
      {
        key: 'community',
        label: 'Community',
        value: 'Kurmi, Kurmi',
      },
      {
        key: 'location',
        label: 'Location',
        value: 'Mumbai, India',
      },
      {
        key: 'education',
        label: 'Education',
        value: 'Masters - Management',
      },
      {
        key: 'profession',
        label: 'Profession',
        value: 'Marketing Professional',
      },
    ],
    infoMapNonIndian: [
      {
        key: 'age_height',
        label: 'Age / Height',
        value: '31, 5\' 9"',
      },
      {
        key: 'religion',
        label: 'Religion',
        value: 'Hindu',
      },
      {
        key: 'mother_tongue',
        label: 'Mother Tongue',
        value: 'Hindi',
      },
      {
        key: 'location',
        label: 'Location',
        value: 'Mumbai,Maharashtra, India',
      },
      {
        key: 'info-6',
        label: 'Grew up in',
        value: 'India',
      },
      {
        key: 'education',
        label: 'Education',
        value: 'Masters - Management',
      },
      {
        key: 'profession',
        label: 'Profession',
        value: 'Marketing Professional',
      },
    ],
    listAlbum: [],
    gridAlbum: [],
    shortBio:
      'Hi! \r\n My name is Rakesh Kurmi.    I have completed my Masters in Management.    I am currently working as a Marketing Professional.',
    createdBy: 'Self',
    profileCreatedBy: 'Self',
    shortlistCount: -1,
  },
  requests: {
    count: 0,
    items: [],
  },
  shortlists: {
    selected: [],
    ready: false,
    count: 0,
  },
  thumbnailBlur: 'https://img1.shaadi.com//2017/12/04/uSH26911954-0d1950-male.jpg',
  thumbnail: 'https://img1.shaadi.com//2017/12/04/uSH26911954-0d1950-male.jpg',
  photoBlur: 'https://img1.shaadi.com//2017/12/04/uSH26911954-088569-Male.jpg',
  photo: 'https://img1.shaadi.com//2017/12/04/uSH26911954-088569-Male.jpg',
  fullPhotoBlur: 'https://img1.shaadi.com//2017/12/04/uSH26911954-73dd62-male.jpg',
  fullPhoto: 'https://img1.shaadi.com//2017/12/04/uSH26911954-73dd62-male.jpg',
  heShe: 'He',
  himHer: 'Him',
  hisHer: 'His',
  gender: 'Male',
  tempId: '123',
  se: '4a0fb3285b7b9f192a299b522a8481cd',
  uid: 'uSH26911954',
  name: 'Rakesh K',
  fullName: 'Rakesh Kurmi',
  firstName: 'Rakesh',
  lastName: 'Kurmi',
  slug: 'uSH26911954',
  userHandle: 'SH26911954',
  location: 'Mumbai, India',
  mrMs: 'Mr.',
  horoscopeScore: {},
};

const profileB = {
  ...profileA,
  uid: 'XSH66211199',
};
const profileC = {
  ...profileA,
  uid: 'OnceInLife_1981',
};
const profileD = {
  ...profileA,
  uid: 'dSH12384610',
};

const profiles = {
  uSH26911954: profileA,
  XSH66211199: profileB,
  OnceInLife_1981: profileC,
  dSH12384610: profileD,
};

const props = {
  searchType: 'preferred',
  wwwBaseUrl: 'https://www.shaadi.com',
  loading: true,
  results: {
    results_id: 'search:0d649a9a7de82f4e7bf6138afe05c1b2',
    permalink: '/search/partner',
    pg_ubt: 'L3NlYXJjaC9wYXJ0bmVyfHwyMA==',
    evt_ref: '',
    query: {
      format: 'list',
      per_page: '20',
      request_id:
        'eyJzZWFyY2hfdHlwZSI6InBhZ2luYXRpb24iLCJyZXN1bHRzX2lkIjoic2VhcmNoOjBkNjQ5YTlhN2RlODJmNGU3YmY2MTM4YWZlMDVjMWIyIiwidmlld2VkIjoiTiIsImZvcm1hdCI6Imxpc3QiLCJwZXJfcGFnZSI6IjIwIiwiX3QiOjE1MTI2Mjg3OTAwOTl9',
      results_id: 'search:0d649a9a7de82f4e7bf6138afe05c1b2',
      search_type: 'pagination',
      viewed: 'N',
    },
    items: [
      { uid: 'uSH26911954', justNow: false, eoiLoadingStyle: 'none', photoLoading: false },
      { uid: 'XSH66211199', justNow: false, eoiLoadingStyle: 'none', photoLoading: false },
      { uid: 'OnceInLife_1981', justNow: false, eoiLoadingStyle: 'none', photoLoading: false },
      { uid: 'dSH12384610', justNow: false, eoiLoadingStyle: 'none', photoLoading: false },
    ],
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
  },
  pageCount: 0,
  page: 0,
  shortlistItems: [],
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: false,
    showUpgradeBanner: false,
    canAccessChat: false,
    canInitiateChat: false,
    hasUploadedPhoto: true,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: 0,
    contactsRemaining: 0,
    isUnderScreening: false,
    isAstroGamified: false,
    gender: 'none',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: false,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '',
  },
  listStyle: 'list',
  sortOrder: [
    {
      key: 'score',
      label: 'Default Order',
      isSelected: true,
    },
    {
      key: 'recorddate',
      label: 'Newest First',
      isSelected: false,
    },
    {
      key: 'lastlogindate',
      label: 'Last Logged In',
      isSelected: false,
    },
  ],
  footerMatches: {
    uid: null,
    loading: false,
    flash: null,
    count: 0,
    results_id: '',
    items: [],
  },
  searchPremiumBanner: {
    isPremiumBannerVisible: false,
    premiumBanner: {},
  },
  profiles,
  onSortChange() {},
  onBulkConnect() {},
  onAction() {},
  onListStyleChange() {},
  onMatchSelectionChange() {},
  daTracking() {},
};
const factory = { profiles, props };
it('should export profiles, props', () => {
  expect(factory.profiles).not.toBeFalsy();
  expect(factory.props).not.toBeFalsy();
});

export default factory;
