const inboxListType = {
  connect_pending: {
    Title: 'Pending Invitations',
  },
};

const getListItem = (listType, itemConfig = {}) => {
  const [type, action] = listType.split('_');
  return [
    {
      uid: 'tSH75248933',
      justNow: false,
      eoiLoadingStyle: 'none',
      photoLoading: false,
      listType,
      requests: {
        [listType]: {
          type: type === 'request' ? 'photo' : type,
          action,
          from: 'tSH75248933',
          to: '1SH14951377',
          isNew: false,
          actionDate: '02 Jul',
          actionTS: '02 Jul 2018',
          requestKey: '3137ffe759307be0a2b5c28efb309e71',
          message_id: '',
          viewed_date: 0,
          direction: 'in',
          ...itemConfig,
        },
      },
    },
    {
      uid: 'dSH56525291',
      justNow: false,
      eoiLoadingStyle: 'none',
      photoLoading: false,
      listType,
      requests: {
        [listType]: {
          type,
          action,
          from: 'dSH56525291',
          to: '1SH14951377',
          isNew: false,
          actionDate: '30 Jun',
          actionTS: '30 Jun 2018',
          requestKey: '3882ac38a283ad540b36c49572266338',
          message_id: '',
          viewed_date: 0,
          direction: 'in',
          ...itemConfig,
        },
      },
    },
    {
      uid: '6SH60175274',
      justNow: false,
      eoiLoadingStyle: 'none',
      photoLoading: false,
      listType,
      requests: {
        [listType]: {
          type,
          action,
          from: '6SH60175274',
          to: '1SH14951377',
          isNew: false,
          actionDate: '30 Jun',
          actionTS: '30 Jun 2018',
          requestKey: '7bf0d28b765d9176c2fc92cc26e86f36',
          message_id: '',
          viewed_date: 0,
          direction: 'in',
          ...itemConfig,
        },
      },
    },
    {
      uid: 'nSH09041149',
      justNow: false,
      eoiLoadingStyle: 'none',
      photoLoading: false,
      listType,
      requests: {
        [listType]: {
          type,
          action,
          from: 'nSH09041149',
          to: '1SH14951377',
          isNew: false,
          actionDate: '30 Jun',
          actionTS: '30 Jun 2018',
          requestKey: '5f867948388d799d387254fe68f0b3d6',
          message_id: 'connect-nSH09041149-1SH14951377-6152-8638-1530313279',
          message: 'Has messaged you',
          viewed_date: 0,
          direction: 'in',
          ...itemConfig,
        },
      },
    },
    {
      uid: '9SH43859929',
      justNow: false,
      eoiLoadingStyle: 'none',
      photoLoading: false,
      listType,
      requests: {
        [listType]: {
          type,
          action,
          from: '9SH43859929',
          to: '1SH14951377',
          isNew: false,
          actionDate: '29 Jun',
          actionTS: '29 Jun 2018',
          requestKey: 'df609993423b4cbf780c9cfcb95f6f2c',
          message_id: 'connect-9SH43859929-1SH14951377-4605-3717-1530290094',
          message: 'Has messaged you',
          viewed_date: 0,
          direction: 'in',
          ...itemConfig,
        },
      },
    },
  ];
};

// const profileIdList = ['tSH75248933', 'dSH56525291', '6SH60175274', 'nSH09041149', '9SH43859929'];
const profiles = {
  tSH75248933: {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [
        {
          key: 'info-0',
          label: 'age_height',
          value: '29 , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'religionComm',
          value: 'Hindu , Arora',
        },
        {
          key: 'info-2',
          label: 'profession',
          value: 'Customer Support / BPO / KPO Professional',
        },
        {
          key: 'info-3',
          label: 'city_country',
          value: 'Delhi , India',
        },
      ],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: 'He sent you an Invitation on 02 Jul 2018.',
      connectionError: false,
      connectionStatus: 'theyContacted',
      connectionAction: 'profile_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: true,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Online',
      onlineStatusDetails: '...',
      onlineAt: 1531810672000,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: 'Online now',
      lastOnlineStatus: 'Online now',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'app_online',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
      infoMapInboxIndian: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Delhi , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Customer Support / BPO / KPO Professional',
        },
      ],
      infoMapInboxNri: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Delhi , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Customer Support / BPO / KPO Professional',
        },
      ],
      infoMapFeaturedNri: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8" , Delhi',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoMapFeatured: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8" , Delhi',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoIndian: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Arora',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
      infoIndianNRI: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Hindu',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2017/11/26/tSH75248933-e19e4b-male.jpg',
    thumbnail: 'https://img1.shaadi.com/2017/11/26/tSH75248933-e19e4b-male.jpg',
    photoBlur: 'https://img1.shaadi.com/2017/11/26/tSH75248933-582810-Male.jpg',
    photoMedium: 'https://img1.shaadi.com/2017/11/26/tSH75248933-582810-Male.jpg',
    photo: '/assets/60-add-ph-male-v2.gif',
    fullPhotoBlur: 'https://img1.shaadi.com/2017/11/26/tSH75248933-af1141-male.jpg',
    fullPhoto: '/assets/60-add-ph-male-v2.gif',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 3,
      shield_state: 'GREEN',
      derived_text: 'PAN, Facebook and Mobile number verified',
      verified_proofs: ['PAN Verified', 'Facebook Verified', 'Mobile number Verified'],
    },
    se: 'b8132af641c6ad001876ef92a1aa405c',
    uid: 'tSH75248933',
    name: 'Pankaj G',
    fullName: 'Pankaj Gulati',
    firstName: 'Pankaj',
    lastName: 'Gulati',
    slug: 'tSH75248933',
    userHandle: 'SH75248933',
    location: 'Delhi India',
    mrMs: 'Mr.',
  },
  dSH56525291: {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [
        {
          key: 'info-0',
          label: 'age_height',
          value: '24 , 5\' 0"',
        },
        {
          key: 'info-1',
          label: 'religionComm',
          value: 'Hindu , Khatri',
        },
        {
          key: 'info-2',
          label: 'profession',
          value: 'Hotel & Hospitality Professional (Others)',
        },
        {
          key: 'info-3',
          label: 'city_country',
          value: 'Churu , India',
        },
      ],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: 'He sent you an Invitation on 30 Jun 2018.',
      connectionError: false,
      connectionStatus: 'theyContacted',
      connectionAction: 'profile_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: true,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Offline',
      onlineStatusDetails: '...',
      onlineAt: 1531020367000,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: 'Online 1w ago',
      lastOnlineStatus: 'Online 1 week ago',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'web_offline',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
      infoMapInboxIndian: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '24 yrs , 5\' 0"',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Khatri',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Churu , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Hotel & Hospitality Professional (Others)',
        },
      ],
      infoMapInboxNri: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '24 yrs , 5\' 0"',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Churu , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Hotel & Hospitality Professional (Others)',
        },
      ],
      infoMapFeaturedNri: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '24 yrs , 5\' 0" , Churu',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoMapFeatured: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '24 yrs , 5\' 0" , Churu',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Khatri',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoIndian: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Arora',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
      infoIndianNRI: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Hindu',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2018/06/29/dSH56525291-250d4a-male.jpg',
    thumbnail: 'https://img1.shaadi.com/2018/06/29/dSH56525291-250d4a-male.jpg',
    photoBlur: 'https://img1.shaadi.com/2018/06/29/dSH56525291-791210-Male.jpg',
    photoMedium: 'https://img1.shaadi.com/2018/06/29/dSH56525291-791210-Male.jpg',
    photo: '/assets/60-add-ph-male-v2.gif',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/06/29/dSH56525291-abf8b0-male.jpg',
    fullPhoto: '/assets/60-add-ph-male-v2.gif',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 1,
      shield_state: 'HOLLOW',
      derived_text: 'Mobile number verified',
      verified_proofs: ['Mobile number Verified'],
    },
    se: '5d0129eb0efe8ae0ef60835a879fa6b4',
    uid: 'dSH56525291',
    name: 'Aditiya R',
    fullName: 'aditiya raj',
    firstName: 'aditiya',
    lastName: 'raj',
    slug: 'dSH56525291',
    userHandle: 'SH56525291',
    location: 'Churu India',
    mrMs: 'Mr.',
  },
  '6SH60175274': {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [
        {
          key: 'info-0',
          label: 'age_height',
          value: '26 , 5\' 4"',
        },
        {
          key: 'info-1',
          label: 'religionComm',
          value: 'Hindu , Khatri',
        },
        {
          key: 'info-2',
          label: 'profession',
          value: 'Mechanical / Production Engineer',
        },
        {
          key: 'info-3',
          label: 'city_country',
          value: 'Gorakhpur , India',
        },
      ],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: 'He sent you an Invitation on 30 Jun 2018.',
      connectionError: false,
      connectionStatus: 'theyContacted',
      connectionAction: 'profile_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: true,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Idle',
      onlineStatusDetails: '...',
      onlineAt: 1531821870000,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: 'Online 1h ago',
      lastOnlineStatus: 'Online few hours ago',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'web_idle',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
      infoMapInboxIndian: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '26 yrs , 5\' 4"',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Khatri',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Gorakhpur , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Engineering/ Technology',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Mechanical / Production Engineer',
        },
      ],
      infoMapInboxNri: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '26 yrs , 5\' 4"',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Gorakhpur , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Engineering/ Technology',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Mechanical / Production Engineer',
        },
      ],
      infoMapFeaturedNri: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '26 yrs , 5\' 4" , Gorakhpur',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Engineering/ Technology',
        },
      ],
      infoMapFeatured: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '26 yrs , 5\' 4" , Gorakhpur',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Khatri',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Engineering/ Technology',
        },
      ],
      infoIndian: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Arora',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
      infoIndianNRI: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Hindu',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2018/01/25/6SH60175274-0478fc-male.jpg',
    thumbnail: 'https://img1.shaadi.com/2018/01/25/6SH60175274-0478fc-male.jpg',
    photoBlur: 'https://img1.shaadi.com/2018/01/25/6SH60175274-432921-Male.jpg',
    photoMedium: 'https://img1.shaadi.com/2018/01/25/6SH60175274-432921-Male.jpg',
    photo: '/assets/60-add-ph-male-v2.gif',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/01/25/6SH60175274-c65732-male.jpg',
    fullPhoto: '/assets/60-add-ph-male-v2.gif',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 1,
      shield_state: 'HOLLOW',
      derived_text: 'Mobile number verified',
      verified_proofs: ['Mobile number Verified'],
    },
    se: '258dd53319ac6982324ed14af3c2cba2',
    uid: '6SH60175274',
    name: 'Prashant S',
    fullName: 'Prashant Sehgal',
    firstName: 'Prashant',
    lastName: 'Sehgal',
    slug: '6SH60175274',
    userHandle: 'SH60175274',
    location: 'Gorakhpur India',
    mrMs: 'Mr.',
  },
  nSH09041149: {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [
        {
          key: 'info-0',
          label: 'age_height',
          value: '29 , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'religionComm',
          value: 'Hindu , Arora',
        },
        {
          key: 'info-2',
          label: 'profession',
          value: 'Business Owner / Entrepreneur',
        },
        {
          key: 'info-3',
          label: 'city_country',
          value: 'Ghaziabad , India',
        },
      ],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: false,
      isPremium: true,
      membershipLevel: 'PremiumPlus',
      connectionNote: 'He sent you an Invitation with Email on 30 Jun 2018.',
      connectionError: false,
      connectionStatus: 'theyContacted',
      connectionAction: 'profile_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: true,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: true,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'platinum_plus',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Online',
      onlineStatusDetails: '...',
      onlineAt: 1531824252000,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: 'Online now',
      lastOnlineStatus: 'Online now',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'app_online',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
      infoMapInboxIndian: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Ghaziabad , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Business Owner / Entrepreneur',
        },
      ],
      infoMapInboxNri: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Ghaziabad , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Business Owner / Entrepreneur',
        },
      ],
      infoMapFeaturedNri: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8" , Ghaziabad',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoMapFeatured: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '29 yrs , 5\' 8" , Ghaziabad',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Bachelors - Commerce',
        },
      ],
      infoIndian: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Arora',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
      infoIndianNRI: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Hindu',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [
      {
        message_id: 'connect-nSH09041149-1SH14951377-6152-8638-1530313279',
        message: 'Has messaged you',
        type: 'connect',
        fullDate: '30 Jun 2018',
      },
    ],
    thumbnailBlur: 'https://img1.shaadi.com/2018/06/23/nSH09041149-9430b2-male.jpg',
    thumbnail: 'https://img1.shaadi.com/2018/06/23/nSH09041149-9430b2-male.jpg',
    photoBlur: 'https://img1.shaadi.com/2018/06/23/nSH09041149-231367-Male.jpg',
    photoMedium: 'https://img1.shaadi.com/2018/06/23/nSH09041149-231367-Male.jpg',
    photo: '/assets/60-add-ph-male-v2.gif',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/06/23/nSH09041149-ef2cf1-male.jpg',
    fullPhoto: '/assets/60-add-ph-male-v2.gif',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 1,
      shield_state: 'HOLLOW',
      derived_text: 'Mobile number verified',
      verified_proofs: ['Mobile number Verified'],
    },
    se: 'd19442c1ad910ec15f277534cdaf5ec1',
    uid: 'nSH09041149',
    name: 'Arjun A',
    fullName: 'Arjun Arora',
    firstName: 'Arjun',
    lastName: 'Arora',
    slug: 'nSH09041149',
    userHandle: 'SH09041149',
    location: 'Ghaziabad India',
    mrMs: 'Mr.',
  },
  '9SH43859929': {
    base: {
      infoMap: [],
      infoList: [],
      detailList: [
        {
          key: 'info-0',
          label: 'age_height',
          value: '27 , 5\' 11"',
        },
        {
          key: 'info-1',
          label: 'religionComm',
          value: 'Hindu , Arora',
        },
        {
          key: 'info-2',
          label: 'profession',
          value: 'Marketing Professional',
        },
        {
          key: 'info-3',
          label: 'city_country',
          value: 'Delhi , India',
        },
      ],
      cardInfo: [],
      premiumInfo: [],
      miniList: [],
      miniNriList: [],
    },
    flags: {
      isFree: false,
      isPremium: true,
      membershipLevel: 'PremiumPlus',
      connectionNote: 'He sent you an Invitation with Email on 29 Jun 2018.',
      connectionError: false,
      connectionStatus: 'theyContacted',
      connectionAction: 'profile_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: true,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: true,
      canCancelInvite: true,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'diamond_plus',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Online',
      onlineStatusDetails: '...',
      onlineAt: 1531807892000,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: 'Online now',
      lastOnlineStatus: 'Online now',
      lastOnlineText: '...',
      ready: false,
      chatIcon: 'app_online',
    },
    summary: {
      infoMap: [],
      infoMapNonIndian: [],
      infoMapIndian: [],
      infoMapNri: [],
      listAlbum: [],
      gridAlbum: [],
      photosLoading: true,
      infoMapInboxIndian: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11"',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Delhi , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Masters - Management',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Marketing Professional',
        },
      ],
      infoMapInboxNri: [
        {
          key: 'info-0',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11"',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-2',
          label: 'city_country',
          value: 'Delhi , India',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Masters - Management',
        },
        {
          key: 'info-5',
          label: 'profession_income',
          value: 'Marketing Professional',
        },
      ],
      infoMapFeaturedNri: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Delhi',
        },
        {
          key: 'info-1',
          label: 'mt_religion',
          value: 'Hindi , Hindu',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Masters - Management',
        },
      ],
      infoMapFeatured: [
        {
          key: 'info-6',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Delhi',
        },
        {
          key: 'info-1',
          label: 'mt_caste',
          value: 'Hindi , Arora',
        },
        {
          key: 'info-3',
          label: 'education',
          value: 'Masters - Management',
        },
      ],
      infoIndian: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Arora',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
      infoIndianNRI: [
        {
          key: 'Info8',
          label: 'age_height_mt_caste',
          value: '27 yrs , 5\' 11" , Hindi , Hindu',
        },
        {
          key: 'Info9',
          label: 'city_country_edu',
          value: 'Mumbai , India , Diploma - Engineering/ Technology',
        },
        {
          key: 'info10',
          label: 'profession_income',
          value: 'Civil Engineer',
        },
      ],
    },
    detailed: {
      album: [],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mLifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      mBackground: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
      conversationStarters: {
        items: [],
      },
      ready: false,
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [
      {
        message_id: 'connect-9SH43859929-1SH14951377-4605-3717-1530290094',
        message: 'Has messaged you',
        type: 'connect',
        fullDate: '29 Jun 2018',
      },
    ],
    thumbnailBlur: 'https://img1.shaadi.com/2018/06/25/9SH43859929-36631e-male.jpg',
    thumbnail: 'https://img1.shaadi.com/2018/06/25/9SH43859929-36631e-male.jpg',
    photoBlur: 'https://img1.shaadi.com/2018/06/25/9SH43859929-134934-Male.jpg',
    photoMedium: 'https://img1.shaadi.com/2018/06/25/9SH43859929-134934-Male.jpg',
    photo: '/assets/60-add-ph-male-v2.gif',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/06/25/9SH43859929-aaee0e-male.jpg',
    fullPhoto: '/assets/60-add-ph-male-v2.gif',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 2,
      shield_state: 'HOLLOW',
      derived_text: 'Facebook and Mobile number verified',
      verified_proofs: ['Facebook Verified', 'Mobile number Verified'],
    },
    se: '4ae6ebbb9472307fdc5c8b2a575276b4',
    uid: '9SH43859929',
    name: 'Ankit K',
    fullName: 'Ankit Kumar',
    firstName: 'Ankit',
    lastName: 'Kumar',
    slug: '9SH43859929',
    userHandle: 'SH43859929',
    location: 'Delhi India',
    mrMs: 'Mr.',
  },
};
// const getProfile = profileId => profiles[profileId] || {};

const formInboxFactory = listType => {
  const [type, action] = listType.split('_');
  const config = { ...inboxListType[listType] };
  const props = {
    loading: false,
    freshLoading: false,
    isLoggedOut: false,
    wwwBaseUrl: 'https://www.shaadi.com',
    settings: {
      defaultSearchFormat: 'list',
      isPaidUser: false,
      showUpgradeBanner: true,
      canAccessChat: true,
      canInitiateChat: false,
      hasUploadedPhoto: false,
      canConnectWithMessage: false,
      showUpgradeLinks: true,
      canSendPasswordOnConnect: false,
      contactsTotal: null,
      contactsRemaining: null,
      isUnderScreening: false,
      isAstroGamified: true,
      gender: 'Female',
      canViewCollegeAndEmployer: false,
      canViewHoroscope: true,
      horoscopeStyle: 'l/ENG/hs/1',
      isFamilyGamified: true,
      isHidden: false,
      isBothPartyPayUser: true,
      isMobileVerified: false,
      mobileNumber: '9876568790',
      wasPaidUser: false,
      expiryDate: '',
      isNri: false,
      isIndianDiaspora: true,
      experiments: {
        premium_tag: {
          bucket: 'A',
        },
        near_me: {
          bucket: 'A',
        },
        webCTA_Dec2017: {
          bucket: 'B',
        },
        premium_carousel: {
          bucket: 'A',
        },
        cartpage: {
          bucket: 'A',
        },
        cartpagenew: {
          bucket: 'B',
        },
        profile_verification: {
          bucket: 'B',
        },
        inbox_revamp: {
          bucket: 'A',
        },
        track_events: {
          bucket: 'A',
        },
        profilepage_revamp_abc: {
          bucket: 'C',
        },
        profilebooster_ab: {
          bucket: 'B',
        },
        featured_invite: {
          bucket: 'B',
        },
        album_revamped: {
          bucket: 'A',
        },
        accept_success: {
          bucket: 'B',
        },
        grid_view: {
          bucket: 'B',
        },
        whatsapp_contact: {
          bucket: 'A',
        },
        premium_message: {
          bucket: 'A',
        },
        cta_ab: {
          bucket: 'B',
        },
        similar_profile: {
          bucket: 'B',
        },
        profile_contact_card: {
          bucket: 'B',
        },
      },
      membershipTags: 'free',
      offerCode: 'octbd60h2',
      offer_details: [
        {
          type: 'perc',
          value: 60,
        },
      ],
    },
    profiles,
    results: {
      results_id: 'inbox:9c3c61f0a4f0640343639454d91fa601',
      permalink: '/inbox/pending/interests?page=1&pg_searchresults_id=inbox%3A9c3c61f0a4f0640343639454d91fa601',
      evt: 'inbox-interests',
      evt_ref: 'aW5ib3gtaW50ZXJlc3Rz',
      items: getListItem(listType),
      tooltip: {
        key: 'none',
        page: 'none',
        position: 'none',
        title: null,
        body: [],
        loading: false,
      },
      source: 'unified',
    },
    requestType: { type, action },
    type,
    action,
    listType,
    itemCount: 300,
    pageTitle: 'Shaadi.com - Find Your Life Partner',
    toast: {
      key: '-inbox-eoi--1531980319146',
    },
    meta: {
      loading: false,
      freshLoading: false,
      listCount: {
        connect_pending: getListItem('connect_pending').length,
      },
    },
  };
  return { props, config };
};
const helpersFn = { formInboxFactory, inboxListType };

it('should export pages props factory helpers', () => {
  expect(Object.keys(helpersFn).length).toEqual(2);
});
export { formInboxFactory, inboxListType };
