const actionTypes = {
  UNAUTH: 'UNAUTH',

  SET_LAYOUT: 'SET_LAYOUT',

  M_DRAWER_ACTION: 'M_DRAWER_ACTION',

  ALERT_SHOW: 'ALERT_SHOW',
  ALERT_HIDE: 'ALERT_HIDE',
  ALERT_HIDE_KEY: 'ALERT_HIDE_KEY',

  METADATA: 'METADATA',
  MOBILE_CARD_SET_STATUS: 'MOBILE_CARD_SET_STATUS',
  EOI_REQUEST: 'EOI_REQUEST',
  EOI_SUCCESS: 'EOI_SUCCESS',
  EOI_FAIL: 'EOI_FAIL',
  CONTACT_EOI_REQUEST: 'CONTACT_EOI_REQUEST',
  CONTACT_EOI_SUCCESS: 'CONTACT_EOI_SUCCESS',
  CONTACT_EOI_FAIL: 'CONTACT_EOI_FAIL',
  PHOTO_EOI_REQUEST: 'PHOTO_EOI_REQUEST',
  PHOTO_EOI_SUCCESS: 'PHOTO_EOI_SUCCESS',
  PHOTO_EOI_FAIL: 'PHOTO_EOI_FAIL',

  PROFILE_BACKGROUND_SUCCESS: 'PROFILE_BACKGROUND_SUCCESS',
  PROFILES_BACKGROUND_SUCCESS: 'PROFILES_BACKGROUND_SUCCESS',
  PROFILES_BACKGROUND_REQUEST: 'PROFILES_BACKGROUND_REQUEST',

  CONTACT_GET_SMS_REQUEST: 'CONTACT_GET_SMS_REQUEST',
  CONTACT_GET_SMS_SUCCESS: 'CONTACT_GET_SMS_SUCCESS',
  CONTACT_GET_SMS_ERROR: 'CONTACT_GET_SMS_ERROR',

  PROFILE_HOVER: 'PROFILE_HOVER',

  PHONE_VERIFICATION_REQUEST_SENT: 'PHONE_VERIFICATION_REQUEST_SENT',

  SELECTED_SHORTLISTS_REQUEST: 'SELECTED_SHORTLISTS_REQUEST',
  SELECTED_SHORTLISTS_SUCCESS: 'SELECTED_SHORTLISTS_SUCCESS',
  SELECTED_SHORTLISTS_FAIL: 'SELECTED_SHORTLISTS_FAIL',

  PREFERRED_SEARCH_REQUEST: 'PREFERRED_SEARCH_REQUEST',
  PREFERRED_SEARCH_CACHE: 'PREFERRED_SEARCH_CACHE',
  PREFERRED_SEARCH_SUCCESS: 'PREFERRED_SEARCH_SUCCESS',
  PREFERRED_SEARCH_CANCEL: 'PREFERRED_SEARCH_CANCEL',
  PREFERRED_SEARCH_FAIL: 'PREFERRED_SEARCH_FAIL',
  PREFERRED_SEARCH_FREEZE: 'PREFERRED_SEARCH_FREEZE',

  OTHER_SEARCH_REQUEST: 'OTHER_SEARCH_REQUEST',
  OTHER_SEARCH_SUCCESS: 'OTHER_SEARCH_SUCCESS',
  OTHER_SEARCH_FAIL: 'OTHER_SEARCH_FAIL',
  OTHER_SEARCH_FREEZE: 'OTHER_SEARCH_FREEZE',
  OTHER_SEARCH_TYPE_SET: 'OTHER_SEARCH_TYPE_SET',

  PROFILE_QUEUE_PREDICT: 'PROFILE_QUEUE_PREDICT',
  PROFILE_QUEUE_REQUEST: 'PROFILE_QUEUE_REQUEST',
  PROFILE_QUEUE_SUCCESS: 'PROFILE_QUEUE_SUCCESS',
  PROFILE_QUEUE_FAIL: 'PROFILE_QUEUE_FAIL',

  PREFERRED_PHOTOS_REQUEST: 'PREFERRED_PHOTOS_REQUEST',
  PREFERRED_PHOTOS_CACHE: 'PREFERRED_PHOTOS_CACHE',
  PREFERRED_PHOTOS_SUCCESS: 'PREFERRED_PHOTOS_SUCCESS',
  PREFERRED_PHOTOS_CANCEL: 'PREFERRED_PHOTOS_CANCEL',
  PREFERRED_PHOTOS_FAIL: 'PREFERRED_PHOTOS_FAIL',

  OTHERSEARCH_PHOTOS_REQUEST: 'OTHERSEARCH_PHOTOS_REQUEST',
  OTHERSEARCH_PHOTOS_CACHE: 'OTHERSEARCH_PHOTOS_CACHE',
  OTHERSEARCH_PHOTOS_SUCCESS: 'OTHERSEARCH_PHOTOS_SUCCESS',
  OTHERSEARCH_PHOTOS_CANCEL: 'OTHERSEARCH_PHOTOS_CANCEL',
  OTHERSEARCH_PHOTOS_FAIL: 'OTHERSEARCH_PHOTOS_FAIL',

  PREFERRED_FACET_UPDATE: 'PREFERRED_FACET_UPDATE',

  OTHERSEARCH_FACET_UPDATE: 'OTHERSEARCH_FACET_UPDATE',

  PREFERRED_SEARCH_FLASH: 'PREFERRED_SEARCH_FLASH',

  PREFERRED_SEARCH_LOADING: 'PREFERRED_SEARCH_LOADING',

  PREMIUM_BANNNER_REQUEST: 'PREMIUM_BANNNER_REQUEST',
  PREMIUM_BANNNER_CACHE: 'PREMIUM_BANNNER_CACHE',
  PREMIUM_BANNNER_SUCCESS: 'PREMIUM_BANNNER_SUCCESS',
  PREMIUM_BANNNER_FAIL: 'PREMIUM_BANNNER_FAIL',

  CHAT_SKEW: 'CHAT_SKEW',
  CHAT_SHOW_FLASH: 'CHAT_SHOW_FLASH',
  CHAT_HIDE_FLASH: 'CHAT_HIDE_FLASH',
  CHAT_HISTORY_REQUEST: 'CHAT_HISTORY_REQUEST',
  CHAT_HISTORY_SUCCESS: 'CHAT_HISTORY_SUCCESS',
  CHAT_HISTORY_FAIL: 'CHAT_HISTORY_FAIL',

  NOTIFICATIONS_REQUEST: 'NOTIFICATIONS_REQUEST',
  NOTIFICATIONS_SUCCESS: 'NOTIFICATIONS_SUCCESS',
  NOTIFICATIONS_FAIL: 'NOTIFICATIONS_FAIL',
  NOTIFICATIONS_TOAST_SHOW: 'NOTIFICATIONS_TOAST_SHOW',
  NOTIFICATIONS_TOAST_HIDE: 'NOTIFICATIONS_TOAST_HIDE',

  CHAT_DATA_REQUEST: 'CHAT_DATA_REQUEST',
  CHAT_DATA_SUCCESS: 'CHAT_DATA_SUCCESS',
  CHAT_DATA_CACHE: 'CHAT_DATA_CACHE',
  CHAT_DATA_FAIL: 'CHAT_DATA_FAIL',

  CHAT_CONNECTING: 'CHAT_CONNECTING',
  CHAT_CONNECTED: 'CHAT_CONNECTED',
  CHAT_DISCONNECTED: 'CHAT_DISCONNECTED',
  CHAT_PRESENCE: 'CHAT_PRESENCE',

  CHAT_OTHER_IS_TYPING: 'CHAT_OTHER_IS_TYPING',
  CHAT_OTHER_IS_NOT_TYPING: 'CHAT_OTHER_IS_NOT_TYPING',

  CHAT_MESSAGES_RECEIVED: 'CHAT_MESSAGES_RECEIVED',
  CHAT_MESSAGE_STATUS: 'CHAT_MESSAGE_STATUS',
  CHAT_INCREMENT_COUNT: 'CHAT_INCREMENT_COUNT',

  CHAT_WINDOW_ADD: 'CHAT_WINDOW_ADD',
  CHAT_WINDOW_OPEN: 'CHAT_WINDOW_OPEN',
  CHAT_WINDOW_CLOSE: 'CHAT_WINDOW_CLOSE',
  CHAT_WINDOW_MINIMIZE: 'CHAT_WINDOW_MINIMIZE',
  CHAT_WINDOW_UNREAD: 'CHAT_WINDOW_UNREAD',
  CHAT_WINDOW_STACK: 'CHAT_WINDOW_STACK',

  CHAT_WINDOW_REQUEST: 'CHAT_WINDOW_REQUEST',
  CHAT_WINDOW_SUCCESS: 'CHAT_WINDOW_SUCCESS',
  CHAT_WINDOW_FAIL: 'CHAT_WINDOW_FAIL',

  CHAT_SETTINGS_CHANGE: 'CHAT_SETTINGS_CHANGE',
  CHAT_SETTINGS_CACHE: 'CHAT_SETTINGS_CACHE',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_CACHE: 'AUTH_CACHE',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',

  SUCCESS_STORIES_REQUEST: 'SUCCESS_STORIES_REQUEST',
  SUCCESS_STORIES_CACHE: 'SUCCESS_STORIES_CACHE',
  SUCCESS_STORIES_SUCCESS: 'SUCCESS_STORIES_SUCCESS',
  SUCCESS_STORIES_FAIL: 'SUCCESS_STORIES_FAIL',

  SESSION_REQUEST: 'SESSION_REQUEST',
  SESSION_CACHE: 'SESSION_CACHE',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAIL: 'SESSION_FAIL',

  COUNTS_REQUEST: 'COUNTS_REQUEST',
  COUNTS_CACHE: 'COUNTS_CACHE',
  COUNTS_SUCCESS: 'COUNTS_SUCCESS',
  COUNTS_FAIL: 'COUNTS_FAIL',

  EVT_REF: 'EVT_REF',
  ROUTE_CHANGE: 'ROUTE_CHANGE',

  COOKIE_SUCCESS: 'COOKIE_SUCCESS',

  TRUST_BADGE_REQUEST: 'TRUST_BADGE_REQUEST',
  TRUST_BADGE_SUCCESS: 'TRUST_BADGE_SUCCESS',

  MODAL_HIDE: 'MODAL_HIDE',
  MODAL_SHOW: 'MODAL_SHOW',

  SHORTLIST_CREATE_REQUEST: 'SHORTLIST_CREATE_REQUEST',
  SHORTLIST_CREATE_SUCCESS: 'SHORTLIST_CREATE_SUCCESS',
  SHORTLIST_CREATE_FAIL: 'SHORTLIST_CREATE_FAIL',

  HIDE_DRAFT_FLASH: 'HIDE_DRAFT_FLASH',
  FETCH_DRAFTS_REQUEST: 'FETCH_DRAFTS_REQUEST',
  FETCH_DRAFTS_FAIL: 'FETCH_DRAFTS_FAIL',
  FETCH_DRAFTS_SUCCESS: 'FETCH_DRAFTS_SUCCESS',
  NEW_DRAFT_REQUEST: 'NEW_DRAFT_REQUEST',
  NEW_DRAFT_FAIL: 'NEW_DRAFT_FAIL',
  NEW_DRAFT_SUCCESS: 'NEW_DRAFT_SUCCESS',
  MODIFY_DRAFT_REQUEST: 'MODIFY_DRAFT_REQUEST',
  MODIFY_DRAFT_FAIL: 'MODIFY_DRAFT_FAIL',
  MODIFY_DRAFT_SUCCESS: 'MODIFY_DRAFT_SUCCESS',
  FETCH_DEFAULT_DRAFT_REQUEST: 'FETCH_DEFAULT_DRAFT_REQUEST',
  FETCH_DEFAULT_DRAFT_FAIL: 'FETCH_DEFAULT_DRAFT_FAIL',
  FETCH_DEFAULT_DRAFT_SUCCESS: 'FETCH_DEFAULT_DRAFT_SUCCESS',

  PHOTO_PASSWORD_REQUEST_SUCCESS: 'PHOTO_PASSWORD_REQUEST_SUCCESS',

  CHAT_USER_POPOVER_SUCCESS: 'CHAT_USER_POPOVER_SUCCESS',

  LAYER_REQUEST: 'LAYER_REQUEST',
  LAYER_SUCCESS: 'LAYER_SUCCESS',
  LAYER_FAIL: 'LAYER_FAIL',

  COLLECTION_DESTROY: 'COLLECTION_DESTROY',
  COLLECTION_REQUEST: 'COLLECTION_REQUEST',
  COLLECTION_SUCCESS: 'COLLECTION_SUCCESS',
  COLLECTION_MOVE: 'COLLECTION_MOVE',
  COLLECTION_FAIL: 'COLLECTION_FAIL',

  PROFILE_LIST_REQUEST: 'PROFILE_LIST_REQUEST',
  PROFILE_LIST_SUCCESS: 'PROFILE_LIST_SUCCESS',
  PROFILE_LIST_POSTSUCCESS: 'PROFILE_LIST_POSTSUCCESS',

  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_CACHE: 'PROFILE_CACHE',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_FAIL: 'PROFILE_FAIL',
  PROFILE_PREPARE_NEXT: 'PROFILE_PREPARE_NEXT',
  PROFILE_RESET: 'PROFILE_RESET',

  WIDGET_MATCHES_REQUEST: 'WIDGET_MATCHES_REQUEST',
  WIDGET_MATCHES_CACHE: 'WIDGET_MATCHES_CACHE',
  WIDGET_MATCHES_SUCCESS: 'WIDGET_MATCHES_SUCCESS',
  WIDGET_MATCHES_FAIL: 'WIDGET_MATCHES_FAIL',

  UPDATE_DIMENSIONS_RESIZE: 'UPDATE_DIMENSIONS_RESIZE',
  UPDATE_DIMENSIONS_SCROLL: 'UPDATE_DIMENSIONS_SCROLL',

  HIDE_ALL_DROPDOWNS: 'HIDE_ALL_DROPDOWNS',
  UPDATE_ACTIVE_DROPDOWN: 'UPDATE_ACTIVE_DROPDOWN',
  EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAIL: 'EDIT_PROFILE_FAIL',

  EDIT_ASTRO_REQUEST: 'EDIT_ASTRO_REQUEST',
  EDIT_ASTRO_SUCCESS: 'EDIT_ASTRO_SUCCESS',
  EDIT_ASTRO_FAIL: 'EDIT_ASTRO_FAIL',

  FOUR_HOUR_REQUEST: 'FOUR_HOUR_REQUEST',
  FOUR_HOUR_SUCCESS: 'FOUR_HOUR_SUCCESS',
  FOUR_HOUR_FAIL: 'FOUR_HOUR_FAIL',
  FOUR_HOUR_CLOSE: 'FOUR_HOUR_CLOSE',

  CONNECT_MESSAGE_SUCCESS: 'CONNECT_MESSAGE_SUCCESS',

  HISTORY_MODAL_SHOW: 'HISTORY_MODAL_SHOW',
  REQUEST_MODAL_SHOW: 'REQUEST_MODAL_SHOW',

  BLOCK_MEMBER_MISUSE: 'BLOCK_MEMBER_MISUSE',
  REPORT_MODAL_REQUEST: 'REPORT_MODAL_REQUEST',
  REPORT_MODAL_SUCCESS: 'REPORT_MODAL_SUCCESS',
  REPORT_MODAL_ERROR: 'REPORT_MODAL_ERROR',
  REPORT_MODAL_CLOSE: 'REPORT_MODAL_CLOSE',

  REPORT_MISUSE_FAIL: 'REPORT_MISUSE_FAIL',

  ATTACHMENT_UPLOAD_REQUEST: 'ATTACHMENT_UPLOAD_REQUEST',
  ATTACHMENT_UPLOAD_PROGRESS: 'ATTACHMENT_UPLOAD_PROGRESS',
  ATTACHMENT_UPLOAD_SUCCESS: 'ATTACHMENT_UPLOAD_SUCCESS',
  ATTACHMENT_UPLOAD_ERROR: 'ATTACHMENT_UPLOAD_ERROR',
  ATTACHMENT_UPLOAD_RESET: 'ATTACHMENT_UPLOAD_RESET',

  FETCH_VIP_CONSULTANT_REQUEST: 'FETCH_VIP_CONSULTANT_REQUEST',
  FETCH_VIP_CONSULTANT_FAIL: 'FETCH_VIP_CONSULTANT_FAIL',
  FETCH_VIP_CONSULTANT_SUCCESS: 'FETCH_VIP_CONSULTANT_SUCCESS',

  CONSULTANT_SUBMITTED_REQUEST: 'CONSULTANT_SUBMITTED_REQUEST',
  CONSULTANT_SUBMITTED_SUCCESS: 'CONSULTANT_SUBMITTED_SUCCESS',
  CONSULTANT_SUBMITTED_FAIL: 'CONSULTANT_SUBMITTED_FAIL',

  MATCHES_GROUP_REQUEST: 'MATCHES_GROUP_REQUEST',
  MATCHES_GROUP_SUCCESS: 'MATCHES_GROUP_SUCCESS',
  MATCHES_GROUP_FAIL: 'MATCHES_GROUP_FAIL',
  SAVED_SEARCH_REQUEST: 'SAVED_SEARCH_REQUEST',
  SAVED_SEARCH_SUCCESS: 'SAVED_SEARCH_SUCCESS',
  SAVED_SEARCH_FAIL: 'SAVED_SEARCH_FAIL',
  SUBMIT_SAVED_SEARCH_SUCCESS: 'SUBMIT_SAVED_SEARCH_SUCCESS',
  TOGGLE_SKIP: 'TOGGLE_SKIP',

  DR_PROFILES_REQUEST: 'DR_PROFILES_REQUEST',
  DR_PROFILES_SUCCESS: 'DR_PROFILES_SUCCESS',
  DR_PROFILES_FAIL: 'DR_PROFILES_FAIL',
  DR_QUEUE_SUCCESS: 'DR_QUEUE_SUCCESS',
  DR_PHOTOS_SUCCESS: 'DR_PHOTOS_SUCCESS',

  PROFILE_PHOTO_UPLOAD_SUCCESS: 'PROFILE_PHOTO_UPLOAD_SUCCESS',
  PROFILE_PHOTO_UPLOAD_FAILED: 'PROFILE_PHOTO_UPLOAD_FAILED',
  PROFILE_PHOTO_UPLOAD_MODAL_CLOSE: 'PROFILE_PHOTO_UPLOAD_MODAL_CLOSE',

  FACEBOOK_ALBUM_PHOTO_REQUEST: 'FACEBOOK_ALBUM_PHOTO_REQUEST',
  FACEBOOK_ALBUM_PHOTO_SUCCESS: 'FACEBOOK_ALBUM_PHOTO_SUCCESS',
  FACEBOOK_ALBUM_PHOTO_FAIL: 'FACEBOOK_ALBUM_PHOTO_FAIL',

  PHOTO_UPLOADED: 'PHOTO_UPLOADED',

  GET_PROFILE_PHOTOS_REQUEST: 'GET_PROFILE_PHOTOS_REQUEST',
  GET_PROFILE_PHOTOS_SUCCESS: 'GET_PROFILE_PHOTOS_SUCCESS',
  GET_PROFILE_PHOTOS_FAIL: 'GET_PROFILE_PHOTOS_FAIL',

  GET_REJECTED_ALBUM_PHOTOS_REQUEST: 'GET_REJECTED_ALBUM_PHOTOS_REQUEST',
  GET_REJECTED_ALBUM_PHOTOS_SUCCESS: 'GET_REJECTED_ALBUM_PHOTOS_SUCCESS',
  GET_REJECTED_ALBUM_PHOTOS_FAIL: 'GET_REJECTED_ALBUM_PHOTOS_FAIL',

  UPDATE_PHOTO_REQUEST: 'UPDATE_PHOTO_REQUEST',
  UPDATE_PHOTO_SUCCESS: 'UPDATE_PHOTO_SUCCESS',
  UPDATE_PHOTO_FAIL: 'UPDATE_PHOTO_FAIL',

  DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
  DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
  DELETE_PHOTO_FAIL: 'DELETE_PHOTO_FAIL',

  GET_PROFILE_ASTRO_REQUEST: 'GET_PROFILE_ASTRO_REQUEST',
  GET_PROFILE_ASTRO_SUCCESS: 'GET_PROFILE_ASTRO_SUCCESS',
  GET_PROFILE_ASTRO_CACHE: 'GET_PROFILE_ASTRO_CACHE',
  GET_PROFILE_ASTRO_FAIL: 'GET_PROFILE_ASTRO_FAIL',

  GET_PROFILE_PRIVACY_SETTING_REQUEST: 'GET_PROFILE_PRIVACY_SETTING_REQUEST',
  GET_PROFILE_PRIVACY_SETTING_SUCCESS: 'GET_PROFILE_PRIVACY_SETTING_SUCCESS',
  GET_PROFILE_PRIVACY_SETTING_FAIL: 'GET_PROFILE_PRIVACY_SETTING_FAIL',

  UPDATE_PROFILE_PRIVACY_SETTING_REQUEST: 'UPDATE_PROFILE_PRIVACY_SETTING_REQUEST',
  UPDATE_PROFILE_PRIVACY_SETTING_SUCCESS: 'UPDATE_PROFILE_PRIVACY_SETTING_SUCCESS',
  UPDATE_PROFILE_PRIVACY_SETTING_FAIL: 'UPDATE_PROFILE_PRIVACY_SETTING_FAIL',

  CONTACT_SUMMARY_DATA_REQUEST: 'CONTACT_SUMMARY_DATA_REQUEST',
  CONTACT_SUMMARY_DATA_SUCCESS: 'CONTACT_SUMMARY_DATA_SUCCESS',
  CONTACT_SUMMARY_DATA_FAIL: 'CONTACT_SUMMARY_DATA_FAIL',
  CONTACT_SUMMARY_VIEW_SMS_SHOW_SUCCESS: 'CONTACT_SUMMARY_VIEW_SMS_SHOW_SUCCESS',
  CONTACT_SUMMARY_VIEW_SMS_SHOW_FAIL: 'CONTACT_SUMMARY_VIEW_SMS_SHOW_FAIL',

  CART_REQUEST: 'CART_REQUEST',
  CART_SUCCESS: 'CART_SUCCESS',
  CART_FAIL: 'CART_FAIL',

  PAYPAL_REQUEST: 'PAYPAL_REQUEST',
  PAYPAL_SUCCESS: 'PAYPAL_SUCCESS',
  PAYPAL_FAIL: 'PAYPAL_FAIL',

  BANKLIST_REQUEST: 'BANKLIST_REQUEST',
  BANKLIST_SUCCESS: 'BANKLIST_SUCCESS',
  BANKLIST_FAIL: 'BANKLIST_FAIL',

  DOORSTEP_REQUEST: 'DOORSTEP_REQUEST',
  DOORSTEP_SUCCESS: 'DOORSTEP_SUCCESS',
  DOORSTEP_FAIL: 'DOORSTEP_FAIL',

  SHAADICENTER_REQUEST: 'SHAADICENTER_REQUEST',
  SHAADICENTER_SUCCESS: 'SHAADICENTER_SUCCESS',
  SHAADICENTER_FAIL: 'SHAADICENTER_FAIL',

  UAE_EXCHANGE_REQUEST: 'UAE_EXCHANGE_REQUEST',
  UAE_EXCHANGE_SUCCESS: 'UAE_EXCHANGE_SUCCESS',
  UAE_EXCHANGE_FAIL: 'UAE_EXCHANGE_FAIL',

  CONSENT_ACTION_REQUEST: 'CONSENT_ACTION_REQUEST',
  CONSENT_ACTION_SUCCESS: 'CONSENT_ACTION_SUCCESS',
  CONSENT_ACTION_FAIL: 'CONSENT_ACTION_FAIL',

  GET_EXPERIEMENT_ACTION_REQUEST: 'GET_EXPERIEMENT_ACTION_REQUEST',
  GET_EXPERIEMENT_ACTION_SUCCESS: 'GET_EXPERIEMENT_ACTION_SUCCESS',
  GET_EXPERIEMENT_ACTION_FAIL: 'GET_EXPERIEMENT_ACTION_FAIL',

  DOWNLOAD_BANNER_SHOW: 'DOWNLOAD_BANNER_SHOW',
  DOWNLOAD_BANNER_HIDE: 'DOWNLOAD_BANNER_HIDE',
  TOAST_SHOW: 'TOAST_SHOW',
  TOAST_HIDE: 'TOAST_HIDE',
  TOAST_HIDE_KEY: 'TOAST_HIDE_KEY',

  INBOX_DATA_REQUEST: 'INBOX_DATA_REQUEST',
  INBOX_DATA_SUCCESS: 'INBOX_DATA_SUCCESS',
  INBOX_DATA_FREEZE: 'INBOX_DATA_FREEZE',
  INBOX_FACET_UPDATE: 'INBOX_FACET_UPDATE',

  GET_OTHER_PROFILE_PHOTOS_REQUEST: 'GET_OTHER_PROFILE_PHOTOS_REQUEST',
  GET_OTHER_PROFILE_PHOTOS_SUCCESS: 'GET_OTHER_PROFILE_PHOTOS_SUCCESS',
  GET_OTHER_PROFILE_PHOTOS_FAIL: 'GET_OTHER_PROFILE_PHOTOS_FAIL',

  PRODUCTS_DETAIL_REQUEST: 'PRODUCTS_DETAIL_REQUEST',
  PRODUCTS_DETAIL_SUCCESS: 'PRODUCTS_DETAIL_SUCCESS',
  PRODUCTS_DETAIL_FAIL: 'PRODUCTS_DETAIL_FAIL',

  OTP_GENERATION_REQUEST: 'OTP_GENERATION_REQUEST',
  OTP_GENERATION_SUCCESS: 'OTP_GENERATION_SUCCESS',
  OTP_GENERATION_FAIL: 'OTP_GENERATION_FAIL',

  OTP_VERIFICATION_REQUEST: 'OTP_VERIFICATION_REQUEST',
  OTP_VERIFICATION_SUCCESS: 'OTP_VERIFICATION_SUCCESS',
  OTP_VERIFICATION_FAIL: 'OTP_VERIFICATION_FAIL',

  VERIFIED_MOBILE_REQUEST: 'VERIFIED_MOBILE_REQUEST',
  VERIFIED_MOBILE_SUCCESS: 'VERIFIED_MOBILE_SUCCESS',
  VERIFIED_MOBILE_FAIL: 'VERIFIED_MOBILE_FAIL',

  GET_ORDERID_REQUEST: 'GET_ORDERID_REQUEST',
  GET_ORDERID_SUCCESS: 'GET_ORDERID_SUCCESS',
  GET_ORDERID_FAIL: 'GET_ORDERID_FAIL',

  ADD_CART_REQUEST: 'ADD_CART_REQUEST',
  ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
  ADD_CART_FAIL: 'ADD_CART_FAIL',
  GET_PROFILE_PHOTO_REQUEST: 'GET_PROFILE_PHOTO_REQUEST',
  GET_PROFILE_PHOTO_SUCCESS: 'GET_PROFILE_PHOTO_SUCCESS',
  GET_PROFILE_PHOTO_FAIL: 'GET_PROFILE_PHOTO_FAIL',

  GET_SELF_PROFILE_REQUEST: 'GET_SELF_PROFILE_REQUEST',
  GET_SELF_PROFILE_SUCCESS: 'GET_SELF_PROFILE_SUCCESS',
  GET_SELF_PROFILE_FAIL: 'GET_SELF_PROFILE_FAIL',

  EOI_JUSTNOW_RESET: 'EOI_JUSTNOW_RESET',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',

  DOCUMENT_ON_CLICK_CHANGE_REQUEST: 'DOCUMENT_ON_CLICK_CHANGE_REQUEST',
  DOCUMENT_ON_CLICK_CHANGE_SUCCESS: 'DOCUMENT_ON_CLICK_CHANGE_SUCCESS',
  DOCUMENT_ON_CLICK_CHANGE_FAIL: 'DOCUMENT_ON_CLICK_CHANGE_FAIL',

  REMOVE_PAGE_LOADER: 'REMOVE_PAGE_LOADER',

  PAYMENT_THANK_YOU_REQUEST: 'PAYMENT_THANK_YOU_REQUEST',
  PAYMENT_THANK_YOU_SUCCESS: 'PAYMENT_THANK_YOU_SUCCESS',
  PAYMENT_THANK_YOU_FAIL: 'PAYMENT_THANK_YOU_FAIL',

  BEEP_SOUND_PLAY: 'BEEP_SOUND_PLAY',
  BEEP_SOUND_STOP: 'BEEP_SOUND_STOP',

  CSAT_DATA_REQUEST: 'CSAT_DATA_REQUEST',
  CSAT_DATA_SUCCESS: 'CSAT_DATA_SUCCESS',
  CSAT_DATA_FAIL: 'CSAT_DATA_FAIL',

  UPDATE_TRUST_BADGE_REQUEST: 'UPDATE_TRUST_BADGE_REQUEST',
  UPDATE_TRUST_BADGE_SUCCESS: 'UPDATE_TRUST_BADGE_SUCCESS',
  UPDATE_TRUST_BADGE_FAIL: 'UPDATE_TRUST_BADGE_FAIL',

  SIMILAR_PROFILE_REQUEST: 'SIMILAR_PROFILE_REQUEST',
  SIMILAR_PROFILE_SUCCESS: 'SIMILAR_PROFILE_SUCCESS',
  SIMILAR_PROFILE_FAIL: 'SIMILAR_PROFILE_FAIL',
  SET_CANCEL: 'SET_CANCEL',
  RESET_CANCEL: 'RESET_CANCEL',

  INBOX_REQUEST_SUMMARY_REQUEST: 'INBOX_REQUEST_SUMMARY_REQUEST',
  INBOX_REQUEST_SUMMARY_SUCCESS: 'INBOX_REQUEST_SUMMARY_SUCCESS',

  PROFILE_PAGE_SUCCESS: 'PROFILE_PAGE_SUCCESS',

  NAV_HIDDEN: 'NAV_HIDDEN',

  POSTPONE_AUTO_MOVE: 'POSTPONE_AUTO_MOVE',
  UPDATE_NAV: 'UPDATE_NAV',

  UPDATE_INVERSE_LOGO: 'UPDATE_INVERSE_LOGO',

  PHONE_SETTING_DATA_REQUEST: 'PHONE_SETTING_DATA_REQUEST',
  PHONE_SETTING_DATA_SUCCESS: 'PHONE_SETTING_DATA_SUCCESS',
  PHONE_SETTING_DATA_FAIL: 'PHONE_SETTING_DATA_FAIL',

  MY_DASHBOARD_WIDGETS_REQUESTS: 'MY_DASHBOARD_WIDGETS_REQUESTS',
  MY_DASHBOARD_WIDGETS_SUCCESS: 'MY_DASHBOARD_WIDGETS_SUCCESS',
  MY_DASHBOARD_WIDGETS_FAIL: 'MY_DASHBOARD_WIDGETS_FAIL',
};

export default actionTypes;
