/* eslint-disable max-len */
const allData = {
  isDR: true,
  item: {
    uid: '6SH22595848',
    loading: false,
    loadingText: 'Loading...',
    flash: null,
    toast: { key: 'none', page: 'none', position: 'none', title: null, body: [], loading: false },
    topToast: { key: 'none', page: 'none', position: 'none', title: null, body: [], loading: false },
    tooltip: { key: 'none', page: 'none', position: 'none', title: null, body: [], loading: false },
    photoLoading: false,
    eoiLoadingStyle: 'none',
    justNow: false,
    justNowText: null,
    justNowIcon: null,
    isPreferredMatch: false,
    connectMessages: [],
    contact: {
      profileid: '6SH22595848',
      convenient_time: '',
      from_time_hours: 0,
      from_time_min: 0,
      last_update_date: 20170908194502,
      mobile_country: 'India',
      mobile_verified: 'Y',
      name: '',
      relation: '',
      telephone_country: 'India',
      telephone_verified: 'N',
      timezone: '',
      to_time_hours: 0,
      to_time_min: 0,
      contact_details_status: 'free_member',
      contact_details_title_status: 'show_all',
    },
    modalShowCount: 0,
    request: {},
    justNowClass: null,
    pageTitle: 'SH22595848 View and Contact Parsi, Hindi Matches',
    triggerReportMisuse: false,
    isAstroStatusError: false,
    interestsAndMore: {},
  },
  profile: {
    base: {
      infoMap: [
        { key: 'info-0', label: 'Age / Height', value: '25, 4\' 5"' },
        { key: 'info-1', label: 'Religion/Community', value: 'Parsi, Parsi' },
        { key: 'info-2', label: 'Mother Tounge', value: 'Hindi' },
        { key: 'info-3', label: 'Profession', value: 'Mariner' },
        { key: 'info-4', label: 'Location', value: 'Hyderabad, India' },
      ],
      infoList: [
        { key: 'age-height', value: '25 yrs, 4\' 5", Parsi, Hindi' },
        { key: 'profession', value: 'Mariner' },
        { key: 'location', value: 'Lives in Hyderabad, India' },
        { key: 'grew up in', value: 'Grew up in India' },
      ],
      detailList: [
        { key: 'age-height', value: '25, 4\' 5"' },
        { key: 'religion-caste', value: 'Parsi, Not Specified' },
        { key: 'profession', value: 'Mariner' },
        { key: 'location', value: 'Hyderabad, India' },
      ],
      premiumInfo: [{ key: 'age-height', value: '25 yrs, 4\' 5", Parsi, Hindi' }, { key: 'location', value: 'Hyderabad, India' }],
      miniList: [
        { key: 'age-height', value: '25 yrs, 4\' 5", Parsi, Hindi' },
        { key: 'religion-caste', value: 'Not Specified' },
        { key: 'location', value: 'Lives in Hyderabad, India' },
      ],
      miniNriList: [
        { key: 'age-height', value: '25 yrs, 4\' 5", Parsi, Hindi' },
        { key: 'grew up in', value: 'Grew up in India' },
        { key: 'location', value: 'Lives in Hyderabad, India' },
      ],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'default',
      connectionAction: 'not_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: false,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      isMaskedProfile: false,
      canCallSendSMS: true,
      canSendEmail: true,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: true,
      showPostOnWall: true,
      isFiltered: false,
      isSkipped: false,
      horoscopeStyle: 'l/undefined/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: false,
      isFamilyGamified: true,
      isAstroReady: false,
      isHidden: false,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'invisible',
      onlineStatusDetails: '...',
      onlineAt: 1514532790000,
      device: 'none',
      platform: 'none',
      lastOnline: 'Online on Android App',
      lastOnlineDetails: 'Online now',
      ready: true,
      chatIcon: 'none',
    },
    summary: {
      infoMap: [
        { key: 'age_height', label: 'Age / Height', value: '25, 4\' 5"' },
        { key: 'religion', label: 'Religion', value: 'Parsi' },
        { key: 'mother_tongue', label: 'Mother Tongue', value: 'Hindi' },
        { key: 'community', label: 'Community', value: 'Parsi' },
        { key: 'location', label: 'Location', value: 'Hyderabad, India' },
        { key: 'education', label: 'Education', value: 'Masters - Arts' },
        { key: 'profession', label: 'Profession', value: 'Mariner' },
      ],
      infoMapNonIndian: [
        { key: 'age_height', label: 'Age / Height', value: '25, 4\' 5"' },
        { key: 'religion', label: 'Religion', value: 'Parsi' },
        { key: 'mother_tongue', label: 'Mother Tongue', value: 'Hindi' },
        { key: 'location_nri_info', label: 'Location', value: 'Hyderabad,Telangana, India' },
        { key: 'info-6', label: 'Grew up in', value: 'India' },
        { key: 'education', label: 'Education', value: 'Masters - Arts' },
        { key: 'profession', label: 'Profession', value: 'Mariner' },
      ],
      infoMapIndian: [
        { key: 'age_height_list', label: 'Age / Height', value: '25 yrs, 4\' 5"' },
        { key: 'marital_status', label: 'Marital Status', value: 'Divorced (Children: Yes. Living together)' },
        { key: 'religion_caste_list', label: 'Religion', value: 'Parsi, Parsi' },
        { key: 'location', label: 'Location', value: 'Hyderabad, India' },
        { key: 'mother_tongue', label: 'Mother Tongue', value: 'Hindi' },
        { key: 'profession', label: 'Profession', value: 'Mariner' },
      ],
      infoMapNri: [
        { key: 'age_height_list', label: 'Age / Height', value: '25 yrs, 4\' 5"' },
        { key: 'profession', label: 'Profession', value: 'Mariner' },
        { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Parsi, Hindi' },
        { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Hyderabad,Telangana, India' },
        { key: 'education', label: 'Education', value: 'Masters - Arts' },
        { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
      ],
      listAlbum: ['https://img1.shaadi.com//2017/11/26/6SH22595848-398ec5-male.webp'],
      gridAlbum: ['https://img1.shaadi.com//2017/11/26/6SH22595848-9e28d3-male.webp'],
      shortBio:
        'Hi, am putting up this profile on behalf of my son.\r\nHe has completed his Masters.Exploring different destinations, cuisines and cultures is something he enjoys.\r\nI wish all the very best to everyone in finding their perfect matches.',
      createdBy: 'Parent / Guardian',
      profileCreatedBy: 'Parent',
      shortlistCount: -1,
    },
    detailed: {
      album: [
        'https://img1.shaadi.com//2017/11/26/6SH22595848-9e28d3-male.webp',
        'https://img1.shaadi.com/2017/11/26/6SH22595848-faee2c-male.webp',
        'https://img1.shaadi.com/2017/11/26/6SH22595848-3934e2-male.webp',
        'https://img1.shaadi.com/2017/09/13/6SH22595848-7acc67-male.webp',
        'https://img1.shaadi.com/2017/12/04/6SH22595848-0926c1-male.webp',
      ],
      albumRevamp: [
        'https://img1.shaadi.com//2017/11/26/6SH22595848-9e28d3-male.webp',
        'https://img1.shaadi.com/2017/11/26/6SH22595848-faee2c-male.webp',
        'https://img1.shaadi.com/2017/11/26/6SH22595848-3934e2-male.webp',
        'https://img1.shaadi.com/2017/09/13/6SH22595848-7acc67-male.webp',
        'https://img1.shaadi.com/2017/12/04/6SH22595848-0926c1-male.webp',
      ],
      infoMap: [
        { key: 'info-0', icon: 'height_sunsign', value: '25 yrs, 4\' 5", Taurus' },
        { key: 'info-1', icon: 'marital_status', value: 'Divorced (1 Child,  Living together)' },
        { key: 'info-2', icon: 'profile_religion', value: 'Parsi, Hindi' },
        { key: 'info-5', icon: 'profile_profession', value: 'Mariner' },
        { key: 'info-6', icon: 'profile_living_in', value: 'Lives in Hyderabad, India' },
        { key: 'info-4', icon: 'edu_qualification', value: 'Masters degree in Arts' },
      ],
      infoMapRevamp: [
        { key: 'info-0', value: '25 yrs, 5\'9"' },
        { key: 'info-1', value: 'Never Married ' },
        { key: 'info-2', value: 'Gujarati' },
        { key: 'info-3', value: 'Lives in Himmatnagar, India' },
        { key: 'info-4', value: 'Hindu, Patel' },
        { key: 'info-5', value: 'Business Owner / Entrepreneur' },
        { key: 'info-6', value: 'Diploma in Management' },
        { key: 'info-7', value: "Doesn't wish to specify his income" },
      ],
      about: {
        title: 'About Him',
        titleRevamp: 'About Him',
        icon: 'about',
        desc:
          'Hi, am putting up this profile on behalf of my son.\r\nHe has completed his Masters.Exploring different destinations, cuisines and cultures is something he enjoys.\r\nI wish all the very best to everyone in finding their perfect matches.',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [
          { key: 'lifestyle-item-0', icon: 'veg', desc: 'Jain diet', title: 'Jain diet' },
          { key: 'lifestyle-item-1', icon: 'drinks', desc: 'Drinks Often', title: 'Drinks Often' },
          { key: 'lifestyle-item-2', icon: 'smoke', desc: 'Smokes Often', title: 'Smokes Often' },
          { key: 'lifestyle-item-3', icon: 'body_type', desc: 'Very Fair skinned, Slim build', title: 'Very Fair skinned, Slim build' },
        ],
      },
      interests: { title: 'Interests & More', icon: 'interests', items: [], extra: [] },
      background: {
        title: 'Background',
        icon: 'background',
        items: [
          { key: 'background-item-0', icon: 'profile_religion', desc: 'Parsi, Hindi', title: 'Religion' },
          { key: 'background-item-1', icon: 'profile_community', desc: '', title: 'Community' },
          { key: 'background-item-4', icon: 'profile_living_in', desc: 'Lives in Hyderabad, Telangana, India ' },
        ],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [
          { key: 'education-item-0', icon: 'edu_qualification', desc: 'Masters degree in Arts' },
          { key: 'education-item-1', icon: 'profession', desc: 'Mariner in government/public sector' },
          { key: 'education-item-5', icon: 'income', desc: 'Earns INR 20 Lakh to 30 Lakh annually' },
        ],
        hasCollegeOrEmployer: '',
      },
      horoscope: { title: 'Horoscope Details', icon: 'astro', isGamified: false, items: [], horoscopeMatch: {}, info: '', link: '' },
      family: { title: 'His Family', icon: 'family', isGamified: false, desc: '' },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [
          { key: 'preference-age', preferenceKey: 'age', term: 'Age', desc: '19 to 27', isMatch: true },
          { key: 'preference-height', preferenceKey: 'height', term: 'Height', desc: '4\' 5"(134cm) to 4\' 11"(149cm)', isMatch: true },
          { key: 'preference-country', preferenceKey: 'country', term: 'Country Living in', desc: 'India', isMatch: true },
        ],
        matchCount: 3,
      },
      trustBadges: [{ key: 'trustbadge-info-item-0', label: 'Contact Info Verified', category: 'Mobile', icon: 'contact' }],
      commonInterests: [],
    },
    requests: { count: 0, items: [] },
    shortlists: { selected: [], ready: false, count: 0 },
    thumbnailBlur: 'https://img1.shaadi.com//2017/11/26/6SH22595848-16c4fa-male.webp',
    thumbnail: 'https://img1.shaadi.com//2017/11/26/6SH22595848-16c4fa-male.webp',
    photoBlur: 'https://img1.shaadi.com//2017/11/26/6SH22595848-398ec5-male.webp',
    photo: 'https://img1.shaadi.com//2017/11/26/6SH22595848-398ec5-male.webp',
    fullPhotoBlur: 'https://img1.shaadi.com//2017/11/26/6SH22595848-9e28d3-male.webp',
    fullPhoto: 'https://img1.shaadi.com//2017/11/26/6SH22595848-9e28d3-male.webp',
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    se: '7b9818b8f6b887b90c51f0df2319e618',
    uid: '6SH22595848',
    name: 'Mafaz K',
    fullName: 'mafaz khan',
    firstName: 'mafaz',
    lastName: 'khan',
    slug: '6SH22595848',
    userHandle: 'SH22595848',
    location: 'Hyderabad, India',
    mrMs: 'Mr.',
  },
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: false,
    showUpgradeBanner: true,
    canAccessChat: true,
    canInitiateChat: false,
    hasUploadedPhoto: false,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: 15,
    contactsRemaining: 0,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: false,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '8169275580',
    wasPaidUser: false,
    expiryDate: '',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: { bucket: 'A' },
      near_me: { bucket: 'B' },
      webCTA_Dec2017: { bucket: 'D' },
      premium_carousel: { bucket: 'A' },
    },
    membershipTags: 'free',
    offerCode: '',
    offer_details: '',
  },
  shortlistItems: [
    { key: 'sl-6369822', id: '6369822', label: "My Maybe's" },
    { key: 'sl-6784850', id: '6784850', label: 'sheman1' },
    { key: 'sl-6784852', id: '6784852', label: 'sheman2' },
    { key: 'sl-6784853', id: '6784853', label: 'sheman3' },
    { key: 'sl-7044760', id: '7044760', label: 'dsfjd' },
    { key: 'sl-7044765', id: '7044765', label: '11111' },
    { key: 'sl-7066022', id: '7066022', label: 'ramji' },
    { key: 'sl-7066025', id: '7066025', label: 'ramji1' },
  ],
  pagination: {
    profileUid: null,
    prevText: 'Prev',
    prevUrl: '/profile/daily-recommendations?profileid=9SH30650981',
    backUrl: null,
    backText: null,
    nextUrl: '/profile/daily-recommendations?profileid=XSH32931119',
    nextText: 'Next',
    nextUid: 'XSH32931119',
    isVisible: true,
    loading: false,
    uid: '6SH22595848',
    prevSectionInfo: {
      icon: 'https://img2.shaadi.com/imgs/profiles/60-request-photo-f.gif',
      iconStatus: 'photo_request',
    },
    nextSectionInfo: {
      icon: 'https://img1.shaadi.com/2017/12/05/rSH82531497-d6fa28-female.jpg',
      iconStatus: 'show_photo',
    },
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  isHovered: false,
  tooltip: { key: 'none', page: 'none', position: 'none', title: null, body: [], loading: false },
  photoLoading: false,
  eoiLoadingStyle: 'none',
  membership: 'Free',
  timeLeftToConnect: 1514572157,
  defaultProfileId: 'XSH32931119',
  isPaidUser: false,
  onAction() {},
};

const factory = { allData };

it('should export profiles and props', () => {
  expect(factory.allData).not.toBeFalsy();
});

export default factory;

/* eslint-enable max-len */
