const PayloadMap = {
  PROFILE_SUCCESS: {
    se: 'f37a65a97f70f7dd3845ac729111cc96',
    uid: 'PSH70219826',
    name: 'SH70219826',
    slug: 'PSH70219826',
    thumbnail: 'https://img1.shaadi.com/2018/08/31/PSH70219826-3d2336-male.webp',
    photo: 'https://img1.shaadi.com/2018/08/31/PSH70219826-e21cbb-male.webp',
    fullPhoto: 'https://img1.shaadi.com/2018/08/31/PSH70219826-652cfa-male.webp',
    thumbnailBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-3d2336-male.webp',
    photoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-e21cbb-male.webp',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-652cfa-male.webp',
    userHandle: 'SH70219826',
    gender: 'Male',
    marital_status: 'Never Married',
    matchTag: '',
    connectMessages: [],
    contact: {
      profileid: 'PSH70219826',
      convenient_time: '',
      from_time_hours: 0,
      from_time_min: 0,
      last_update_date: 20180831160822,
      mobile_country: 'India',
      mobile_verified: 'Y',
      name: '',
      relation: '',
      telephone_country: 'India',
      telephone_verified: 'N',
      timezone: '',
      to_time_hours: 0,
      to_time_min: 0,
      contact_details_status: 'free_member',
      contact_details_title_status: 'show_all',
      country_code: '+91',
      std_code: '',
      contact_number: '9417XXXXXX',
      email: 'XXXXXXXXXX@gmail.com',
    },
    horoscopeScore: {},
    flags: {
      membershipLevel: 'PremiumPlus',
      membershipTags: 'gold_plus',
      isBoldListing: true,
      isDeleted: false,
      connectionStatus: 'default',
      connectionAction: 'not_contacted',
      connectionNote: null,
      contactStatus: 'available',
      contactAction: 'free',
      horoscopeStatus: 'none',
      horoscopeStyle: 'l/undefined/hs/1',
      albumStatus: 'default',
      isWatermarked: true,
      isTwoWayMatch: false,
      activeStatus: 'default',
      isNri: false,
      isIndianDiaspora: true,
      isHoroscopeApplicable: true,
      isFamilyGamified: true,
      isAstroReady: false,
      isSameGender: false,
      canCancelInvite: false,
      canRemind: false,
      canUnblock: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
      showHistory: false,
      isNameLocked: false,
      canCallSendSMS: true,
      canSendEmail: true,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: true,
      showPostOnWall: true,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
    },
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '25, 6\' 0"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Sikh, Jat',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Punjabi',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Farming',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Other, India',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '25 yrs, 6\' 0", Sikh, Punjabi',
        },
        {
          key: 'profession',
          value: 'Farming',
        },
        {
          key: 'location',
          value: 'Lives in Other, India',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '25 yrs, 6\' 0", Sikh, Punjabi',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
        {
          key: 'location',
          value: 'Lives in Other, India',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '25 yrs, 6\' 0", Sikh, Punjabi',
        },
        {
          key: 'religion-caste',
          value: 'Jat',
        },
        {
          key: 'location',
          value: 'Lives in Other, India',
        },
      ],
      cardInfo: [
        {
          key: 'age-height',
          value: '25 yrs, 6\' 0"',
        },
        {
          key: 'religion-caste',
          value: 'Punjabi, Sikh',
        },
        {
          key: 'profession',
          value: 'Farming',
        },
        {
          key: 'location',
          value: 'Other, India',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '25, 6\' 0"',
        },
        {
          key: 'religion-caste',
          value: 'Sikh, Jat',
        },
        {
          key: 'profession',
          value: 'Farming',
        },
        {
          key: 'location',
          value: 'Other, India',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '25 yrs, 6\' 0", Sikh, Punjabi',
        },
        {
          key: 'location',
          value: 'Other, India',
        },
      ],
    },
    presence: {
      onlineStatus: 'Online',
      onlineAt: 1537786101000,
      device: null,
      platform: null,
      lastOnline: 'Online on Android App',
      lastOnlineDetails: 'Online now',
      lastOnlineStatus: 'Online now',
      chatIcon: 'app_online',
      lastOnlineText: 'Online',
    },
    summary: {
      shortBio:
        'Hi there, me in a nutshell...\rI have completed my High school.My family is of a paramount importance to me and I strike a healthy balance between work and personal life.\rWishing you the best for your partner search..',
      createdBy: 'Self',
      profileCreatedBy: 'Self',
      shortlistCount: -1,
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '25, 6\' 0"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Sikh',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Jat, jat',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Other, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Arts',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Farming',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '25, 6\' 0"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Sikh',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Other,Punjab, India',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Arts',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Farming',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '25 yrs, 6\' 0"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Sikh, Jat',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Other, India',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Punjabi',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Farming',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '25 yrs, 6\' 0"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Farming',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Sikh, Punjabi',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Other,Punjab, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'High school - Arts',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India',
        },
      ],
    },
    detailed: {
      createdBy: 'Self',
      shortlistCount: 0,
      infoMap: [
        {
          key: 'info-0',
          icon: 'height_sunsign',
          value: '25 yrs, 6\' 0", Cancer',
        },
        {
          key: 'info-1',
          icon: 'marital_status',
          value: 'Never Married ',
        },
        {
          key: 'info-2',
          icon: 'profile_religion',
          value: 'Sikh, Punjabi',
        },
        {
          key: 'info-3',
          icon: 'profile_community',
          value: 'Jat, jat',
        },
        {
          key: 'info-5',
          icon: 'profile_profession',
          value: 'Farming',
        },
        {
          key: 'info-6',
          icon: 'profile_living_in',
          value: 'Lives in Other, India',
        },
        {
          key: 'info-4',
          icon: 'edu_qualification',
          value: 'High school certified in Arts',
        },
      ],
      about:
        'Hi there, me in a nutshell...\rI have completed my High school.My family is of a paramount importance to me and I strike a healthy balance between work and personal life.\rWishing you the best for your partner search..',
      interests: {},
      lifestyle: {
        diet: 'Veg',
        drink: 'No',
        smoke: 'No',
        complexion: 'Wheatish',
        body_built: 'Average',
      },
      background: [
        {
          key: 'background-item-0',
          icon: 'profile_religion',
          desc: 'Sikh, Punjabi',
          title: 'Religion',
        },
        {
          key: 'background-item-1',
          icon: 'profile_community',
          desc: 'Jat, jat',
          title: 'Community',
        },
        {
          key: 'background-item-4',
          icon: 'profile_living_in',
          desc: 'Lives in Other, Punjab, India ',
        },
      ],
      education: {
        items: [
          {
            key: 'education-item-0',
            icon: 'edu_qualification',
            desc: 'High school certified in Arts',
          },
          {
            key: 'education-item-1',
            icon: 'profession',
            desc: 'Does Farming - own business/self employed',
          },
          {
            key: 'education-item-5',
            icon: 'income',
            desc: 'Earns INR 20 Lakh to 30 Lakh annually',
          },
        ],
        hasCollegeOrEmployer: '',
      },
      commonInterests: ['He lives in punjab as well', 'You both are from the Punjabi community'],
      horoscope: {
        birth_star: '',
        moon_sign: '',
        info: '',
        manglik: '',
        score: {},
        link: {},
        is_gamified: false,
      },
      trustBadges: [
        {
          key: 'trustbadge-info-item-0',
          label: 'Contact Info Verified',
          category: 'Mobile',
          icon: 'contact',
        },
        {
          key: 'trustbadge-info-item-2',
          label: 'Offline ID provided',
          category: 'Driving License',
          icon: 'offline',
        },
      ],
      family: {
        desc: 'My father  and my mother is a homemaker. I have 1 sister (married).',
      },
      preferences: {
        items: [
          {
            key: 'preference-age',
            preferenceKey: 'age',
            term: 'Age',
            desc: '21 to 27',
            isMatch: true,
          },
          {
            key: 'preference-height',
            preferenceKey: 'height',
            term: 'Height',
            desc: '5\' 3"(160cm) to 5\' 11"(180cm)',
            isMatch: true,
          },
          {
            key: 'preference-maritalStatus',
            preferenceKey: 'marital_status',
            term: 'Marital Status',
            desc: 'Never Married',
            isMatch: true,
          },
          {
            key: 'preference-match-2',
            preferenceKey: 'caste',
            term: 'Religion / Community',
            desc: 'Sikh: Jat',
            isMatch: true,
          },
          {
            key: 'preference-motherTongue',
            preferenceKey: 'mother_tongue',
            term: 'Mother Tongue',
            desc: 'Punjabi',
            isMatch: true,
          },
          {
            key: 'preference-country',
            preferenceKey: 'country',
            term: 'Country Living in',
            desc: 'Germany, Pakistan, Kuwait, Canada, Australia, Saudi Arabia, USA, United Kingdom, South Africa, New Zealand',
            isMatch: false,
          },
        ],
        matchCount: 5,
      },
    },
    isAstroStatusError: false,
    tempId: '',
    contactSummary: {
      dnd: 'N',
      hidden: 'N',
      hiddenReason: false,
      contact: {
        profileid: 'PSH70219826',
        convenient_time: '',
        from_time_hours: 0,
        from_time_min: 0,
        last_update_date: 20180831160822,
        mobile_country: 'India',
        mobile_verified: 'Y',
        name: '',
        relation: '',
        telephone_country: 'India',
        telephone_verified: 'N',
        timezone: '',
        to_time_hours: 0,
        to_time_min: 0,
        contact_details_status: 'free_member',
        contact_details_title_status: 'show_all',
        country_code: '+91',
        std_code: '',
        contact_number: '9417XXXXXX',
        email: 'XXXXXXXXXX@gmail.com',
      },
      photoStatus: 'show_photo',
      photoCount: 2,
      profileContactStatus: 'none',
      contactDetailsStatusString: 'none',
      contactDetailsTitleStatusString: 'available',
    },
    fullName: ' ',
    firstName: '',
    lastName: '',
    location: 'Other, India',
    photos: {
      count: 2,
      photos: [
        {
          status: 'Y',
          photo_order: 0,
          profile_photo: true,
          medium: '/2018/08/31/PSH70219826-724425-Male.jpg',
          '60X60': '/2018/08/31/PSH70219826-eb752a-male.webp',
          '40X40': '/2018/08/31/PSH70219826-5ffbe8-male.webp',
          '750X1333': '/2018/08/31/PSH70219826-c01d62-male.webp',
          '720X1006_nb': '',
          '150X200': '/2018/08/31/PSH70219826-724425-Male.webp',
          '400X500': '/2018/08/31/PSH70219826-c66f29-male.webp',
          '120X120': '/2018/08/31/PSH70219826-3d2336-male.webp',
          small_nb: '/2018/08/31/PSH70219826-eb752a-male.jpg',
          large_nb: '/2018/08/31/PSH70219826-c66f29-male.jpg',
          large: '/2018/08/31/PSH70219826-c66f29-male.jpg',
          medium_nb: '/2018/08/31/PSH70219826-724425-Male.jpg',
          semilarge_nb: '/2018/08/31/PSH70219826-652cfa-male.jpg',
          '40X40_nb': '/2018/08/31/PSH70219826-5ffbe8-male.webp',
          '120X120_nb': '/2018/08/31/PSH70219826-3d2336-male.webp',
          '750X1333_nb': '/2018/08/31/PSH70219826-c01d62-male.webp',
          '400X500_nb': '/2018/08/31/PSH70219826-c66f29-male.webp',
          '250X310_nb': '/2018/08/31/PSH70219826-652cfa-male.webp',
          semilarge: '/2018/08/31/PSH70219826-652cfa-male.jpg',
          '150X200_nb': '/2018/08/31/PSH70219826-724425-Male.webp',
          '60X60_nb': '/2018/08/31/PSH70219826-eb752a-male.webp',
          '250X310': '/2018/08/31/PSH70219826-652cfa-male.webp',
          '450X600_nb': '/2018/08/31/PSH70219826-e21cbb-male.webp',
          small: '/2018/08/31/PSH70219826-eb752a-male.jpg',
          '720X1006': '',
          '450X600': '/2018/08/31/PSH70219826-e21cbb-male.webp',
          domain_name: 'https://img1.shaadi.com',
          domain_name_nb: 'https://img1.shaadi.com',
          isProfilePhoto: true,
          isPhotoScreened: true,
          isPhotoUnderScreening: false,
          isPhotoRejected: false,
          canShowMakeProfilePhotoOpt: false,
          canShowPhotoOpts: true,
          cantMakeProfilePhotoReason: false,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          isImgComingSoonSilhouette: false,
          getCaption: 'Profile Photo',
          getUrlForAlbumPage: 'https://img1.shaadi.com/2018/08/31/PSH70219826-724425-Male.webp',
          rejectedMsg: 'Please refer to Photo Guidelines',
          isScaledDownImage: false,
          cantDeletePhotoReason: 'Please select a profile photo from your album!',
        },
        {
          status: 'Y',
          photo_order: 1,
          profile_photo: false,
          '450X600': '/2018/08/31/PSH70219826-60e033-male.webp',
          '40X40': '/2018/08/31/PSH70219826-4e5fbd-male.webp',
          '60X60_nb': '/2018/08/31/PSH70219826-e31fc3-male.webp',
          '750X1333_nb': '/2018/08/31/PSH70219826-7d2b2c-male.webp',
          small: '/2018/08/31/PSH70219826-e31fc3-male.jpg',
          '60X60': '/2018/08/31/PSH70219826-e31fc3-male.webp',
          '150X200': '/2018/08/31/PSH70219826-128385-Male.webp',
          '720X1006': '',
          medium: '/2018/08/31/PSH70219826-128385-Male.jpg',
          '750X1333': '/2018/08/31/PSH70219826-7d2b2c-male.webp',
          '250X310_nb': '/2018/08/31/PSH70219826-423f1b-male.webp',
          medium_nb: '/2018/08/31/PSH70219826-128385-Male.jpg',
          '150X200_nb': '/2018/08/31/PSH70219826-128385-Male.webp',
          '400X500_nb': '/2018/08/31/PSH70219826-9671f4-male.webp',
          '450X600_nb': '/2018/08/31/PSH70219826-60e033-male.webp',
          large: '/2018/08/31/PSH70219826-9671f4-male.jpg',
          '400X500': '/2018/08/31/PSH70219826-9671f4-male.webp',
          large_nb: '/2018/08/31/PSH70219826-9671f4-male.jpg',
          '120X120_nb': '/2018/08/31/PSH70219826-d14046-male.webp',
          '250X310': '/2018/08/31/PSH70219826-423f1b-male.webp',
          '40X40_nb': '/2018/08/31/PSH70219826-4e5fbd-male.webp',
          '120X120': '/2018/08/31/PSH70219826-d14046-male.webp',
          small_nb: '/2018/08/31/PSH70219826-e31fc3-male.jpg',
          semilarge: '/2018/08/31/PSH70219826-423f1b-male.jpg',
          semilarge_nb: '/2018/08/31/PSH70219826-423f1b-male.jpg',
          '720X1006_nb': '',
          domain_name: 'https://img1.shaadi.com',
          domain_name_nb: 'https://img1.shaadi.com',
          isProfilePhoto: false,
          isPhotoScreened: true,
          isPhotoUnderScreening: false,
          isPhotoRejected: false,
          canShowMakeProfilePhotoOpt: true,
          canShowPhotoOpts: true,
          cantMakeProfilePhotoReason: false,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          isImgComingSoonSilhouette: false,
          getCaption: 'Album Photo 1',
          getUrlForAlbumPage: 'https://img1.shaadi.com/2018/08/31/PSH70219826-128385-Male.webp',
          rejectedMsg: 'Please refer to Photo Guidelines',
          isScaledDownImage: false,
        },
      ],
      status: 'show_photo',
      hasPhotos: true,
      hasApprovedProfilePhotos: true,
      isProfilePhotoScreened: true,
      cantDeleteProfilePhotoReason: 'Please select a profile photo from your album!',
      hasApprovedSoloAlbumPhoto: true,
      rejectedPhotosCount: 0,
      nonRejectedPhotosCnt: 2,
      screeningPhotosCount: 0,
      approvedPhotoCount: 2,
      hasRejectedPhotos: false,
      profilePhoto: {
        status: 'Y',
        photo_order: 0,
        profile_photo: true,
        medium: '/2018/08/31/PSH70219826-724425-Male.jpg',
        '60X60': '/2018/08/31/PSH70219826-eb752a-male.webp',
        '40X40': '/2018/08/31/PSH70219826-5ffbe8-male.webp',
        '750X1333': '/2018/08/31/PSH70219826-c01d62-male.webp',
        '720X1006_nb': '',
        '150X200': '/2018/08/31/PSH70219826-724425-Male.webp',
        '400X500': '/2018/08/31/PSH70219826-c66f29-male.webp',
        '120X120': '/2018/08/31/PSH70219826-3d2336-male.webp',
        small_nb: '/2018/08/31/PSH70219826-eb752a-male.jpg',
        large_nb: '/2018/08/31/PSH70219826-c66f29-male.jpg',
        large: '/2018/08/31/PSH70219826-c66f29-male.jpg',
        medium_nb: '/2018/08/31/PSH70219826-724425-Male.jpg',
        semilarge_nb: '/2018/08/31/PSH70219826-652cfa-male.jpg',
        '40X40_nb': '/2018/08/31/PSH70219826-5ffbe8-male.webp',
        '120X120_nb': '/2018/08/31/PSH70219826-3d2336-male.webp',
        '750X1333_nb': '/2018/08/31/PSH70219826-c01d62-male.webp',
        '400X500_nb': '/2018/08/31/PSH70219826-c66f29-male.webp',
        '250X310_nb': '/2018/08/31/PSH70219826-652cfa-male.webp',
        semilarge: '/2018/08/31/PSH70219826-652cfa-male.jpg',
        '150X200_nb': '/2018/08/31/PSH70219826-724425-Male.webp',
        '60X60_nb': '/2018/08/31/PSH70219826-eb752a-male.webp',
        '250X310': '/2018/08/31/PSH70219826-652cfa-male.webp',
        '450X600_nb': '/2018/08/31/PSH70219826-e21cbb-male.webp',
        small: '/2018/08/31/PSH70219826-eb752a-male.jpg',
        '720X1006': '',
        '450X600': '/2018/08/31/PSH70219826-e21cbb-male.webp',
        domain_name: 'https://img1.shaadi.com',
        domain_name_nb: 'https://img1.shaadi.com',
        isProfilePhoto: true,
        isPhotoScreened: true,
        isPhotoUnderScreening: false,
        isPhotoRejected: false,
        canShowMakeProfilePhotoOpt: false,
        canShowPhotoOpts: true,
        cantMakeProfilePhotoReason: false,
        isGroupPhoto: false,
        isPhotoOptsOpen: false,
        isImgComingSoonSilhouette: false,
        getCaption: 'Profile Photo',
        getUrlForAlbumPage: 'https://img1.shaadi.com/2018/08/31/PSH70219826-724425-Male.webp',
        rejectedMsg: 'Please refer to Photo Guidelines',
        isScaledDownImage: false,
        cantDeletePhotoReason: 'Please select a profile photo from your album!',
      },
    },
    request: {
      details: {
        count: 0,
        request_type: [],
      },
    },
    privacy: {
      memberlogin: 'PSH70219826',
      display_name: 'profile_id',
      phone: 'Show All',
      photo: 'Show All',
      photo_password: 'null',
      horoscope_status: 'None',
      visitors_setting: 'N',
      shortlist_setting: 'N',
      profile_privacy: 'Show All',
      sms_alert: 0,
    },
    recommendation: {},
    verification: {
      count: 2,
      shield_state: 'GREEN',
      derived_text: 'Driving license and Mobile number verified',
      verified_proofs: ['Driving license Verified', 'Mobile number Verified'],
    },
    profileQueue: {},
    otherPhotos: [
      {
        order: 0,
        photoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-e21cbb-male.webp',
        fullPhotoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-652cfa-male.webp',
      },
      {
        order: 1,
        photoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-60e033-male.webp',
        fullPhotoBlur: 'https://img1.shaadi.com/2018/08/31/PSH70219826-423f1b-male.webp',
      },
    ],
  },
};
const getPayload = action => PayloadMap[action] || {};
it('should export action function', () => {
  expect(typeof getPayload).toBe('function');
});
export default getPayload;
