version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.12.0-browsers
    working_directory: ~/shaadi-react/Nightwatch-Web-Testing/
    steps:
    - checkout
    - restore_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

    - run:
        name : Execute E2E depending on the branch name
        command: |
          if [[ "${CIRCLE_BRANCH}" =~ "google" ]]; then
            cd Nightwatch-Web-Testing && npm install  && mkdir -p Result  && node nightwatch.js google.js
          fi
workflows:
  version: 2
  workflow:
    jobs:
    - build