version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.12.0-browsers
    working_directory: ~/shaadi-react/Nightwatch-Web-Testing/
    steps:
    - checkout

    - restore_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

    - run:
        name: Install deps
        command: |
          python --version
          cp yarn.lock orig-yarn-lock-file
          yarn
          yarn cache dir
    - save_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "orig-yarn-lock-file"
          }}-{{ checksum "package.json" }}
        paths:
        - node_modules
    
    - run:
        name: change setting
        command: chmod +x wait-for.sh

    - run:
        name: start shaadi site
        command: yarn start
        background: true

    - run:
        name: wait for shaadi branch
        command: ./wait-for.sh
        when: on_success
    
    - run:
        name : Execute E2E depending on the branch name
        command: |

          if [[ "${CIRCLE_BRANCH}" =~ "master" ]]; then
            cd Nightwatch-Web-Testing && npm install  && mkdir -p Result  && cd Monetization/Batch_Execution/ && chmod +x pp1-regression.sh && xvfb-run -a ./pp1-regression.sh
          fi

          if [[ "${CIRCLE_BRANCH}" =~ "google" ]]; then
            cd Nightwatch-Web-Testing && npm install  && mkdir -p Result  && node nightwatch.js google.js
          fi

          if [[ "${CIRCLE_BRANCH}" =~ "amazon" ]]; then
            cd Nightwatch-Web-Testing && npm install  && mkdir -p Result  && node nightwatch.js amazon.js
          fi

          if [[ "${CIRCLE_BRANCH}" =~ "netflix" ]]; then
            cd Nightwatch-Web-Testing && npm install  && mkdir -p Result  && node nightwatch.js netflix.js
          fi
    
    - store_artifacts:
        path: Nightwatch-Web-Testing/Result
    
    - store_test_results:
        path: Nightwatch-Web-Testing/Result
    
workflows:
  version: 2
  workflow:
    jobs:
    - build