version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.12.0-browsers
    working_directory: ~/shaadi-react
    steps:
    - checkout
    - restore_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum
          "package.json" }}
    
    - run:
        name: ls
        command: ls
        
    - run:
        name: Change folder to NW
        command: cd Nightwatch-Web-Testing/
        
    - run:
        name: ls
        command: ls
        
    - run:
        name: Install dependency
        command: yarn install  && mkdir -p Result
        
    - run:
        name: ls
        command: ls
        
    - run:
        name: move to batch folder
        command: cd Monetization/Batch_Execution/
    
    - run:
        name: change PP1 regression
        command: chmod +x pp1-regression.sh
        
    - run:
        name: start PP1 regression
        command: ./pp1-regression.sh
        
        
        
        
workflows:
  version: 2
  workflow:
    jobs:
    - build