version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.12.0-browsers
    working_directory: ~/shaadi-react
    steps:
    - checkout
    - restore_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum
          "package.json" }}
    - run:
        name: Install deps
        command: |
          python --version
          cp yarn.lock orig-yarn-lock-file
          yarn
          yarn cache dir
    - save_cache:
        key: shaadi-react-10.12.0-v1-{{ arch }}-{{ checksum "orig-yarn-lock-file"
          }}-{{ checksum "package.json" }}
        paths:
        - node_modules
        
    - run:
        name: change setting
        command: chmod +x wait-for.sh
        
    - run:
        name: start shaadi site
        command: yarn start
        background: true
    
    - run:
        name: wait for shaadi branch
        command:  ./wait-for.sh
        when: on_success
        
    - run:
        name: Change folder to NW
        command: cd Nightwatch-Web-Testing
        
    - run:
        name: Install dependency
        command: yarn install  && mkdir -p Result
        
    - run:
        name: move to batch folder
        command: cd Monetization/Batch_Execution/
    
    - run:
        name: change PP1 regression
        command: chmod +x pp1-regression.sh
        
    - run:
        name: start PP1 regression
        command: ./pp1-regression.sh
        
        
        
        
workflows:
  version: 2
  workflow:
    jobs:
    - build