const props = {
  match: {
    path: '/profile',
    url: '/profile',
    isExact: true,
    params: {},
  },
  location: {
    pathname: '/profile',
    search:
      '?profileid=gSH77642635&ubt=L2luYm94L3BlbmRpbmcvcGhvdG8tcmVxdWVzdHN8aW5ib3g6YzlkOWNhNWI1MDM3MWI2MjFhODhlMzI1YTI3NGFiNDh8ZjJiOTJlMGM0MGI3NmI0MzIwZDVjYmYxMTRkOTEyZTU%3D&source=unified&evt_ref=aW5ib3gtcmVxdWVzdHM%3D&datasrc=api',
    hash: '',
  },
  history: {
    length: 3,
    action: 'POP',
    location: {
      pathname: '/profile',
      search:
        '?profileid=gSH77642635&ubt=L2luYm94L3BlbmRpbmcvcGhvdG8tcmVxdWVzdHN8aW5ib3g6YzlkOWNhNWI1MDM3MWI2MjFhODhlMzI1YTI3NGFiNDh8ZjJiOTJlMGM0MGI3NmI0MzIwZDVjYmYxMTRkOTEyZTU%3D&source=unified&evt_ref=aW5ib3gtcmVxdWVzdHM%3D&datasrc=api',
      hash: '',
    },
  },
  isLoggedOut: false,
  item: {
    uid: 'gSH77642635',
    loading: false,
    loadingText: 'Loading...',
    flash: null,
    toast: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    topToast: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    photoLoading: false,
    eoiLoadingStyle: 'none',
    justNow: false,
    justNowText: null,
    justNowIcon: null,
    isPreferredMatch: false,
    connectMessages: [],
    contact: {
      profileid: 'gSH77642635',
      convenient_time: '',
      from_time_hours: 0,
      from_time_min: 0,
      last_update_date: 20180319114531,
      mobile_country: 'United Kingdom',
      mobile_verified: 'Y',
      name: '',
      relation: '',
      telephone_country: 'Germany',
      telephone_verified: 'N',
      timezone: '',
      to_time_hours: 0,
      to_time_min: 0,
      contact_details_status: 'free_member',
      contact_details_title_status: 'show_all',
    },
    modalShowCount: 0,
    request: {
      photo: [
        {
          type: 'photo',
          accept_viewed: 'N',
          filtered: '',
          temp: '',
          from: 'gSH77642635',
          to: 'FSH80117296',
          record_date: 20180319125725,
          viewed: 'N',
          deleted_by_to: 0,
          deleted_by_from: 0,
          accepted_date: 0,
          status: 'received',
          viewed_date: 0,
          accepted_viewed_date: 0,
          status_updated_date: '2018-03-19 12:57:25',
        },
      ],
      details: {
        count: 1,
        request_type: ['photo'],
      },
    },
    justNowClass: null,
    pageTitle: 'SH77642635 View and Contact Hindu, Hindi Matches',
    triggerReportMisuse: false,
    isAstroStatusError: false,
    interestsAndMore: {},
  },
  similarMatches: {
    uid: 'gSH77642635',
    loading: false,
    flash: null,
    count: 39,
    results_id: 'search:dc0b4db4eaa9539b70ddbac7c538509e',
    items: [
      {
        uid: 'dSH78478399',
      },
    ],
  },
  newMatches: {
    uid: 'gSH77642635',
    loading: false,
    flash: null,
    count: 5,
    results_id: 'search:c538dc5dbe5a9afde0f5fca0cc1bcafa',
    items: [
      {
        uid: 'iSH30270397',
      },
    ],
  },
  pagination: {
    count: 181,
    profileUid: 'gSH77642635',
    prevText: 'Prev',
    prevUrl:
      '/profile?profileid=4SH70193652&ubt=L2luYm94L3BlbmRpbmcvcGhvdG8tcmVxdWVzdHN8aW5ib3g6YzlkOWNhNWI1MDM3MWI2MjFhODhlMzI1YTI3NGFiNDh8NmJkMDVhZjA4MzYzMzg2MzRhOTdkYTI1ZTdkMGRjM2M%3D&source=unified&evt_ref=aW5ib3gtcmVxdWVzdHM%3D&datasrc=api&np=via-prev',
    backUrl:
      '/inbox/pending/photo-requests?pg_searchresults_id=inbox%3Ac9d9ca5b50371b621a88e325a274ab48&page=1&evt_ref=aW5ib3gtcmVxdWVzdHM%3D',
    backText: 'Back',
    nextUrl:
      '/profile?profileid=pSH25877670&ubt=L2luYm94L3BlbmRpbmcvcGhvdG8tcmVxdWVzdHN8aW5ib3g6YzlkOWNhNWI1MDM3MWI2MjFhODhlMzI1YTI3NGFiNDh8MmIzMWM0MDRkNzdhNzRmYjA4OWI1YTEzOTE0YzY3YTQ%3D&source=unified&evt_ref=aW5ib3gtcmVxdWVzdHM%3D&datasrc=api&np=via-next',
    nextText: 'Next',
    prevUid: '4SH70193652',
    nextUid: 'pSH25877670',
    isVisible: true,
    source: 'unified',
    prevSectionInfo: {
      icon: 'https://img2.shaadi.com/imgs/profiles/60-request-photo-f.gif',
      iconStatus: 'photo_request',
    },
    nextSectionInfo: {
      icon: 'https://img1.shaadi.com/2017/12/05/rSH82531497-d6fa28-female.jpg',
      iconStatus: 'show_photo',
    },
  },
  gamification: {
    loading: false,
    flash: null,
  },
  isChatOpen: false,
  successStories: {
    loading: false,
    flash: null,
    items: [
      {
        id: '1',
        title: 'Nagarajan & Premakuamri',
        photo: 'https://img.shaadi.com/success-story/nagarajan-premakuamri-big.jpg',
        description:
          'It is a great pleasure that Shaadi.com brought us together. We are very much gratitude to the service which shaadi.com has been providing all these ye',
      },
      {
        id: '2',
        title: 'Samir & Ila',
        photo: 'https://img.shaadi.com/success-story/samir-ila-big.jpg',
        description:
          'Thanks to shaadi.com. Due to this site i was able to find my soulmate my truelove and my handsome &amp; cute husband. We met on 2nd week of march and on 1',
      },
      {
        id: '3',
        title: 'Firdause & Nasser',
        photo: 'https://img.shaadi.com/success-story/nasser-firdause-big.jpg',
        description:
          'Wedding Date : 10th April 2006 It has been a Wonderful Experience meeting each other on Shaadi.com It is said that Dreams mostly do not co',
      },
    ],
  },
  profiles: {
    default: {
      base: {
        infoMap: [],
        infoList: [],
        detailList: [],
        cardInfo: [],
        premiumInfo: [],
        miniList: [],
        miniNriList: [],
      },
      flags: {
        isFree: false,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'unknown',
        connectionAction: 'not_contacted',
        connectionJustNowText: null,
        contactAction: 'none',
        contactStatus: 'none',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: false,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'none',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: true,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        canViewPhotosOnConnectOnly: false,
        canPremiumMemberViewPhoto: false,
        canCommunicate: false,
      },
      presence: {
        onlineStatus: 'invisible',
        onlineStatusDetails: '...',
        onlineAt: 0,
        device: 'none',
        platform: 'none',
        lastOnline: '...',
        lastOnlineDetails: '...',
        lastOnlineStatus: '...',
        lastOnlineText: '...',
        ready: false,
        chatIcon: 'none',
      },
      summary: {
        infoMap: [],
        infoMapNonIndian: [],
        infoMapIndian: [],
        infoMapNri: [],
        listAlbum: [],
        gridAlbum: [],
        photosLoading: true,
      },
      detailed: {
        album: [],
        albumRevamp: [],
        infoMap: [],
        infoMapRevamp: [],
        about: {
          title: 'About',
          titleRevamp: 'About',
          icon: 'about',
          desc: '',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mLifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mBackground: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [],
          hasCollegeOrEmployer: false,
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
        },
        family: {
          title: 'Family Details',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [],
        },
        trustBadges: [],
        commonInterests: [],
        conversationStarters: {
          items: [],
        },
        ready: false,
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
      photos: {
        count: 0,
        items: [],
        status: '',
        hasPhotos: false,
        canAddPhotos: false,
        isDefault: true,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
      },
      contactSummary: {
        sms: '',
        contact: {
          mobile_verified: 'yes',
          telephone_verified: 'yes',
          contact_number: '9737666147',
        },
        actionDate: '',
        dnd: '',
        hidden: '',
        hiddenReason: '',
        tempKey: '',
        contactType: '',
        photoStatus: '',
        photoCount: 0,
        profileContactStatus: '',
        contactDetailsStatusString: '',
        contactDetailsTitleStatusString: '',
      },
      connectMessages: [],
      thumbnailBlur: '/assets/default-thumbnail.png',
      thumbnail: '/assets/default-thumbnail.png',
      photoBlur: '/assets/default-photo.png',
      photoMedium: '/assets/default-photo.png',
      photo: '/assets/default-photo.png',
      fullPhotoBlur: '/assets/default-full-photo.png',
      fullPhoto: '/assets/default-full-photo.png',
      drAction: {},
      heShe: '...',
      himHer: '...',
      hisHer: '...',
      gender: null,
      tempId: '',
      verification: {
        count: 0,
        shield_state: '',
        derived_text: '',
        verified_proofs: [],
      },
      uid: null,
      name: '...',
    },
    self: {
      base: {
        infoMap: [
          {
            key: 'info-0',
            label: 'Age / Height',
            value: '27, 5\' 2"',
          },
          {
            key: 'info-1',
            label: 'Religion/Community',
            value: 'Hindu, Agri',
          },
          {
            key: 'info-2',
            label: 'Mother Tounge',
            value: 'Hindi',
          },
          {
            key: 'info-3',
            label: 'Profession',
            value: 'Not Specified',
          },
          {
            key: 'info-4',
            label: 'Location',
            value: 'Gurgaon, India',
          },
        ],
        infoList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 2", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Lives in Gurgaon, India',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
        ],
        detailList: [
          {
            key: 'age-height',
            value: '27, 5\' 2"',
          },
          {
            key: 'religion-caste',
            value: 'Hindu, Agri',
          },
          {
            key: 'profession',
            value: 'Not specified',
          },
          {
            key: 'location',
            value: 'Gurgaon, India',
          },
        ],
        cardInfo: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 2"',
          },
          {
            key: 'religion-caste',
            value: 'Hindi, Hindu',
          },
          {
            key: 'profession',
            value: 'Not specified',
          },
          {
            key: 'location',
            value: 'Gurgaon, India',
          },
        ],
        premiumInfo: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 2", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Gurgaon, India',
          },
        ],
        miniList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 2", Hindu, Hindi',
          },
          {
            key: 'religion-caste',
            value: 'Agri',
          },
          {
            key: 'location',
            value: 'Lives in Gurgaon, India',
          },
        ],
        miniNriList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 2", Hindu, Hindi',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
          {
            key: 'location',
            value: 'Lives in Gurgaon, India',
          },
        ],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'Free',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'unknown',
        connectionAction: 'not_contacted',
        connectionJustNowText: null,
        contactAction: 'none',
        contactStatus: 'none',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: false,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: true,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        canViewPhotosOnConnectOnly: false,
        canPremiumMemberViewPhoto: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'noPhoto',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: true,
        isAstroReady: false,
        isHidden: false,
        hiddenReason: null,
        isBothPartyPayUser: false,
        canCommunicate: false,
      },
      presence: {
        onlineStatus: 'invisible',
        onlineStatusDetails: '...',
        onlineAt: 0,
        device: 'none',
        platform: 'none',
        lastOnline: '...',
        lastOnlineDetails: '...',
        lastOnlineStatus: '...',
        lastOnlineText: '...',
        ready: false,
        chatIcon: 'none',
      },
      summary: {
        infoMap: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '27, 5\' 2"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'community',
            label: 'Community',
            value: 'Agri',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Gurgaon, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Arts',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapNonIndian: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '27, 5\' 2"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'location_nri_info',
            label: 'Location',
            value: 'Gurgaon,Haryana, India',
          },
          {
            key: 'info-6',
            label: 'Grew up in',
            value: 'India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Arts',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '27 yrs, 5\' 2"',
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
          {
            key: 'religion_caste_list',
            label: 'Religion',
            value: 'Hindu, Agri',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Gurgaon, India',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapNri: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '27 yrs, 5\' 2"',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
          {
            key: 'religion_mother_tongue_list',
            label: 'Mother Tongue',
            value: 'Hindu, Hindi',
          },
          {
            key: 'location_nri_info_list',
            label: 'Location',
            value: 'Lives in Gurgaon,Haryana, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Arts',
          },
          {
            key: 'grew_up_in_info',
            label: 'Grew up in',
            value: 'Grew up in India',
          },
        ],
        listAlbum: [],
        gridAlbum: [],
        photosLoading: true,
        shortBio:
          'It is a pleasure sharing a few words about my daughter.\r\nShe has completed her Bachelors.Over the years with time and experience, attributes like accommodating and maturity have become part of her personality.\r\nI wish all the very best to everyone in finding their perfect matches.',
        createdBy: 'Parent / Guardian',
        profileCreatedBy: 'Parent',
        shortlistCount: -1,
      },
      detailed: {
        album: ['https://img2.shaadi.com/imgs/my-shaadi/ver2/250-photo-not-added-f.gif'],
        albumRevamp: ['https://img2.shaadi.com/imgs/my-shaadi/ver2/250-photo-not-added-f.gif'],
        infoMap: [],
        infoMapRevamp: [],
        about: {
          title: 'About',
          titleRevamp: 'About',
          icon: 'about',
          desc: '',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mLifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mBackground: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [],
          hasCollegeOrEmployer: false,
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
        },
        family: {
          title: 'Family Details',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [],
        },
        trustBadges: [],
        commonInterests: [],
        conversationStarters: {
          items: [],
        },
        ready: false,
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
      photos: {
        count: 0,
        items: [],
        status: 'add_photo',
        hasPhotos: false,
        canAddPhotos: true,
        isDefault: false,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: 'partial_name',
        horoscope_status: 'None',
        memberlogin: 'FSH80117296',
        phone: 'Show All',
        photo: 'Show All',
        photo_password: 'null',
        profile_privacy: 'Show All',
        shortlist_setting: 'N',
        sms_alert: 0,
        visitors_setting: 'N',
        isDefault: false,
      },
      contactSummary: {
        sms: '',
        contact: {
          mobile_verified: 'yes',
          telephone_verified: 'yes',
          contact_number: '9737666147',
        },
        actionDate: '',
        dnd: '',
        hidden: '',
        hiddenReason: '',
        tempKey: '',
        contactType: '',
        photoStatus: '',
        photoCount: 0,
        profileContactStatus: '',
        contactDetailsStatusString: '',
        contactDetailsTitleStatusString: '',
      },
      connectMessages: [],
      thumbnailBlur: 'https://img2.shaadi.com/imgs/my-shaadi/ver2/60-add-ph-female-v2.gif',
      thumbnail: 'https://img2.shaadi.com/imgs/profiles/60-no-border-female.gif',
      photoBlur: 'https://img2.shaadi.com/imgs/profile/photoclicktoupload.gif',
      photoMedium: '/assets/default-photo.png',
      photo: 'https://img2.shaadi.com/imgs/profiles/150-no-border-female.gif',
      fullPhotoBlur: 'https://img2.shaadi.com/imgs/my-shaadi/ver2/250-photo-not-added-f.gif',
      fullPhoto: '/assets/60-add-ph-female-v2.gif',
      drAction: {},
      heShe: 'She',
      himHer: 'Her',
      hisHer: 'Her',
      gender: 'Female',
      tempId: '',
      verification: {
        count: 0,
        shield_state: '',
        derived_text: '',
        verified_proofs: [],
      },
      uid: 'FSH80117296',
      name: 'Sonu B',
      fullName: 'sonu bangdi',
      firstName: 'sonu',
      lastName: 'bangdi',
      slug: 'FSH80117296',
      userHandle: 'SH80117296',
      location: 'Gurgaon, India',
      mrMs: 'Ms.',
    },
    gSH77642635: {
      base: {
        infoMap: [
          {
            key: 'info-0',
            label: 'Age / Height',
            value: '28, 5\' 9"',
          },
          {
            key: 'info-1',
            label: 'Religion/Community',
            value: 'Hindu, Baniya',
          },
          {
            key: 'info-2',
            label: 'Mother Tounge',
            value: 'Hindi',
          },
          {
            key: 'info-3',
            label: 'Profession',
            value: 'Not Specified',
          },
          {
            key: 'info-4',
            label: 'Location',
            value: 'Ratlam, India',
          },
        ],
        infoList: [
          {
            key: 'age-height',
            value: '28 yrs, 5\' 9", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Lives in Ratlam, India',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
        ],
        detailList: [
          {
            key: 'age-height',
            value: '28, 5\' 9"',
          },
          {
            key: 'religion-caste',
            value: 'Hindu, Baniya',
          },
          {
            key: 'profession',
            value: 'Not specified',
          },
          {
            key: 'location',
            value: 'Ratlam, India',
          },
        ],
        cardInfo: [
          {
            key: 'age-height',
            value: '28 yrs, 5\' 9"',
          },
          {
            key: 'religion-caste',
            value: 'Hindi, Hindu',
          },
          {
            key: 'profession',
            value: 'Not specified',
          },
          {
            key: 'location',
            value: 'Ratlam, India',
          },
        ],
        premiumInfo: [
          {
            key: 'age-height',
            value: '28 yrs, 5\' 9", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Ratlam, India',
          },
        ],
        miniList: [
          {
            key: 'age-height',
            value: '28 yrs, 5\' 9", Hindu, Hindi',
          },
          {
            key: 'religion-caste',
            value: 'Baniya',
          },
          {
            key: 'location',
            value: 'Lives in Ratlam, India',
          },
        ],
        miniNriList: [
          {
            key: 'age-height',
            value: '28 yrs, 5\' 9", Hindu, Hindi',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
          {
            key: 'location',
            value: 'Lives in Ratlam, India',
          },
        ],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'Free',
        connectionNote: 'You do not match his partner requirements.',
        connectionError: false,
        connectionStatus: 'default',
        connectionAction: 'member_filtered',
        connectionJustNowText: null,
        contactAction: 'free',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: true,
        isMaskedProfile: true,
        canCallSendSMS: true,
        canSendEmail: true,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: true,
        showPostOnWall: true,
        isFiltered: true,
        isSkipped: false,
        isProfileViewed: false,
        canViewPhotosOnConnectOnly: false,
        canPremiumMemberViewPhoto: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: true,
        isAstroReady: false,
        isHidden: false,
        hiddenReason: null,
        isBothPartyPayUser: false,
        canCommunicate: false,
      },
      presence: {
        onlineStatus: 'Idle',
        onlineStatusDetails: '...',
        onlineAt: 1521464436000,
        device: 'none',
        platform: 'none',
        lastOnline: 'Last online, 46 mins ago',
        lastOnlineDetails: 'Online 1h ago',
        lastOnlineStatus: 'Online few mins ago',
        lastOnlineText: '1h ago',
        ready: true,
        chatIcon: 'web_idle',
      },
      summary: {
        infoMap: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '28, 5\' 9"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'community',
            label: 'Community',
            value: 'Baniya',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Ratlam, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapNonIndian: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '28, 5\' 9"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'location_nri_info',
            label: 'Location',
            value: 'Ratlam,Madhya Pradesh, India',
          },
          {
            key: 'info-6',
            label: 'Grew up in',
            value: 'India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '28 yrs, 5\' 9"',
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
          {
            key: 'religion_caste_list',
            label: 'Religion',
            value: 'Hindu, Baniya',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Ratlam, India',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
        ],
        infoMapNri: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '28 yrs, 5\' 9"',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Not Specified',
          },
          {
            key: 'religion_mother_tongue_list',
            label: 'Mother Tongue',
            value: 'Hindu, Hindi',
          },
          {
            key: 'location_nri_info_list',
            label: 'Location',
            value: 'Lives in Ratlam,Madhya Pradesh, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'grew_up_in_info',
            label: 'Grew up in',
            value: 'Grew up in India',
          },
        ],
        listAlbum: ['https://img1.shaadi.com/2018/03/19/gSH77642635-0fcf1b-male.webp'],
        gridAlbum: ['https://img1.shaadi.com/2018/03/19/gSH77642635-25d8a9-male.webp'],
        photosLoading: true,
        shortBio:
          'It is a pleasure sharing a few words about my son.\rHe has completed his Bachelors.He enjoys being around people and believes in living life with positivity.\rWishing you the best for your partner search.',
        createdBy: 'Parent / Guardian',
        profileCreatedBy: 'Parent',
        shortlistCount: -1,
      },
      detailed: {
        album: ['https://img1.shaadi.com/2018/03/19/gSH77642635-25d8a9-male.webp'],
        albumRevamp: ['https://img1.shaadi.com/2018/03/19/gSH77642635-25d8a9-male.webp'],
        infoMap: [
          {
            key: 'info-0',
            icon: 'height_sunsign',
            value: '28 yrs, 5\' 9", Gemini',
          },
          {
            key: 'info-1',
            icon: 'marital_status',
            value: 'Never Married ',
          },
          {
            key: 'info-2',
            icon: 'profile_religion',
            value: 'Hindu, Hindi',
          },
          {
            key: 'info-3',
            icon: 'profile_community',
            value: 'Baniya',
          },
          {
            key: 'info-4',
            icon: 'edu_qualification',
            value: 'Bachelors degree in Engineering/ Technology',
          },
          {
            key: 'info-6',
            icon: 'profile_living_in',
            value: 'Lives in Ratlam, India',
          },
        ],
        infoMapRevamp: [
          { key: 'info-0', value: '25 yrs, 5\'9"' },
          { key: 'info-1', value: 'Never Married ' },
          { key: 'info-2', value: 'Gujarati' },
          { key: 'info-3', value: 'Lives in Himmatnagar, India' },
          { key: 'info-4', value: 'Hindu, Patel' },
          { key: 'info-5', value: 'Business Owner / Entrepreneur' },
          { key: 'info-6', value: 'Diploma in Management' },
          { key: 'info-7', value: "Doesn't wish to specify his income" },
        ],
        about: {
          title: 'About Him',
          titleRevamp: 'About Him',
          icon: 'about',
          desc:
            'It is a pleasure sharing a few words about my son.\rHe has completed his Bachelors.He enjoys being around people and believes in living life with positivity.\rWishing you the best for your partner search.',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [
            {
              key: 'lifestyle-item-0',
            },
            {
              key: 'lifestyle-item-1',
              icon: 'no_drink',
              desc: "Doesn't Drink",
              title: "Doesn't Drink",
            },
            {
              key: 'lifestyle-item-2',
              icon: 'dont_smoke',
              desc: "Doesn't Smoke",
              title: "Doesn't Smoke",
            },
            {
              key: 'lifestyle-item-3',
              icon: 'body_type',
              desc: 'Fair skinned, Athletic build',
              title: 'Fair skinned, Athletic build',
            },
          ],
        },
        mLifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [
            {
              key: 'lifestyle-item-0',
              icon: 'male_small',
              desc: '28 yrs, 5\' 9", Gemini',
            },
            {
              key: 'lifestyle-item-1',
              icon: 'ring',
              desc: 'Never Married ',
            },
            {
              key: 'lifestyle-item-2',
              icon: 'location',
              desc: 'Lives in Ratlam, Madhya Pradesh, India ',
            },
            {
              key: 'lifestyle-item-3',
              icon: 'profession',
              desc: '',
            },
            {
              key: 'lifestyle-item-4',
            },
            {
              key: 'lifestyle-item-5',
              icon: 'drinks',
              desc: "Doesn't Smoke, Doesn't Smoke",
            },
            {
              key: 'lifestyle-item-9',
              icon: 'body_type',
              desc: 'Fair skinned, Athletic build',
              title: 'Fair skinned, Athletic build',
            },
          ],
        },
        mBackground: {
          title: 'Background',
          icon: 'background',
          items: [
            {
              key: 'background-item-0',
              icon: 'profile_religion',
              desc: 'Hindu, Hindi',
              title: 'Religion',
            },
            {
              key: 'background-item-1',
              icon: 'profile_community',
              desc: 'Baniya',
              title: 'Community',
            },
          ],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
          extra: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [
            {
              key: 'background-item-0',
              icon: 'profile_religion',
              desc: 'Hindu, Hindi',
              title: 'Religion',
            },
            {
              key: 'background-item-1',
              icon: 'profile_community',
              desc: 'Baniya',
              title: 'Community',
            },
            {
              key: 'background-item-4',
              icon: 'profile_living_in',
              desc: 'Lives in Ratlam, Madhya Pradesh, India ',
            },
          ],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [
            {
              key: 'education-item-0',
              icon: 'edu_qualification',
              desc: 'Bachelors degree in Engineering/ Technology',
            },
            {
              key: 'education-item-1',
              icon: 'profession',
              desc: '',
            },
            {
              key: 'education-item-5',
              icon: 'income',
              desc: 'Earns INR 15 Lakh to 20 Lakh annually',
            },
          ],
          hasCollegeOrEmployer: '',
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
          horoscopeMatch: {},
          info: '',
          link: {},
        },
        family: {
          title: 'His Family',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [
            {
              key: 'preference-age',
              preferenceKey: 'age',
              term: 'Age',
              desc: '24 to 28',
              isMatch: true,
            },
            {
              key: 'preference-height',
              preferenceKey: 'height',
              term: 'Height',
              desc: '5\' 0"(152cm) to 5\' 9"(175cm)',
              isMatch: true,
            },
            {
              key: 'preference-maritalStatus',
              preferenceKey: 'marital_status',
              term: 'Marital Status',
              desc: 'Never Married',
              isMatch: true,
            },
            {
              key: 'preference-match-2',
              preferenceKey: 'caste',
              term: 'Religion / Community',
              desc: 'Hindu: Agarwal, Hindu: Baniya, Hindu: Barnwal, Hindu: Varshney',
              isMatch: false,
            },
            {
              key: 'preference-motherTongue',
              preferenceKey: 'mother_tongue',
              term: 'Mother Tongue',
              desc: 'Hindi',
              isMatch: true,
            },
            {
              key: 'preference-country',
              preferenceKey: 'country',
              term: 'Country Living in',
              desc: 'India',
              isMatch: true,
            },
          ],
          matchCount: 5,
        },
        trustBadges: [
          {
            key: 'trustbadge-info-item-0',
            label: 'Contact Info Verified',
            category: 'Mobile',
            icon: 'contact',
          },
        ],
        commonInterests: ['He is a Gemini too', "He has done his Bachelor's degree as well", 'You both are from the Hindi community'],
        conversationStarters: {
          items: [
            {
              key: 'conv-0',
              icon: 'discover_connect',
              desc: 'He is a Gemini too',
            },
            {
              key: 'conv-1',
              icon: 'discover_connect',
              desc: "He has done his Bachelor's degree as well",
            },
            {
              key: 'conv-2',
              icon: 'discover_connect',
              desc: 'You both are from the Hindi community',
            },
          ],
        },
        ready: true,
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: true,
        count: 0,
      },
      photos: {
        count: 1,
        items: [
          {
            status: 'Y',
            photo_order: 0,
            profile_photo: true,
            '60X60': '/2018/03/19/gSH77642635-09ffaf-male.webp',
            '450X600': '/2018/03/19/gSH77642635-0fcf1b-male.webp',
            '40X40': '/2018/03/19/gSH77642635-d9f011-male.webp',
            '60X60_nb': '/2018/03/19/gSH77642635-09ffaf-male.webp',
            '750X1333_nb': '/2018/03/19/gSH77642635-2a9d24-male.webp',
            semilarge: '/2018/03/19/gSH77642635-25d8a9-male.jpg',
            '250X310': '/2018/03/19/gSH77642635-25d8a9-male.webp',
            '150X200': '/2018/03/19/gSH77642635-886379-Male.webp',
            '40X40_nb': '/2018/03/19/gSH77642635-d9f011-male.webp',
            medium: '/2018/03/19/gSH77642635-886379-Male.jpg',
            '720X1006_nb': '',
            '400X500': '/2018/03/19/gSH77642635-4d3023-male.webp',
            small_nb: '/2018/03/19/gSH77642635-09ffaf-male.jpg',
            medium_nb: '/2018/03/19/gSH77642635-886379-Male.jpg',
            semilarge_nb: '/2018/03/19/gSH77642635-25d8a9-male.jpg',
            '150X200_nb': '/2018/03/19/gSH77642635-886379-Male.webp',
            '450X600_nb': '/2018/03/19/gSH77642635-0fcf1b-male.webp',
            '720X1006': '',
            '120X120': '/2018/03/19/gSH77642635-445a18-male.webp',
            '400X500_nb': '/2018/03/19/gSH77642635-4d3023-male.webp',
            small: '/2018/03/19/gSH77642635-09ffaf-male.jpg',
            '750X1333': '/2018/03/19/gSH77642635-2a9d24-male.webp',
            '120X120_nb': '/2018/03/19/gSH77642635-445a18-male.webp',
            '250X310_nb': '/2018/03/19/gSH77642635-25d8a9-male.webp',
            domain_name: 'https://img1.shaadi.com',
            domain_name_nb: 'https://img1.shaadi.com',
            isProfilePhoto: true,
            isPhotoScreened: true,
            isPhotoUnderScreening: false,
            isPhotoRejected: false,
            canShowMakeProfilePhotoOpt: false,
            canShowPhotoOpts: true,
            cantMakeProfilePhotoReason: false,
            isGroupPhoto: false,
            isPhotoOptsOpen: false,
            isImgComingSoonSilhouette: false,
            getCaption: 'Profile Photo',
            getUrlForAlbumPage: 'https://img1.shaadi.com/2018/03/19/gSH77642635-886379-Male.webp',
            rejectedMsg: 'Please refer to Photo Guidelines',
            isScaledDownImage: false,
          },
        ],
        status: 'show_photo',
        hasPhotos: true,
        canAddPhotos: true,
        isDefault: false,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
      },
      contactSummary: {
        sms: '',
        contact: {
          mobile_verified: 'yes',
          telephone_verified: 'yes',
          contact_number: '9737666147',
        },
        actionDate: '',
        dnd: '',
        hidden: '',
        hiddenReason: '',
        tempKey: '',
        contactType: '',
        photoStatus: '',
        photoCount: 0,
        profileContactStatus: '',
        contactDetailsStatusString: '',
        contactDetailsTitleStatusString: '',
      },
      connectMessages: [],
      thumbnailBlur: 'https://img1.shaadi.com/2018/03/19/gSH77642635-445a18-male.webp',
      thumbnail: 'https://img1.shaadi.com/2018/03/19/gSH77642635-445a18-male.webp',
      photoBlur: 'https://img1.shaadi.com/2018/03/19/gSH77642635-0fcf1b-male.webp',
      photoMedium: '/assets/default-photo.png',
      photo: 'https://img1.shaadi.com/2018/03/19/gSH77642635-0fcf1b-male.webp',
      fullPhotoBlur: 'https://img1.shaadi.com/2018/03/19/gSH77642635-25d8a9-male.webp',
      fullPhoto: 'https://img1.shaadi.com/2018/03/19/gSH77642635-25d8a9-male.webp',
      drAction: {},
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      gender: 'Male',
      tempId: '',
      verification: {
        count: 1,
        shield_state: 'HOLLOW',
        derived_text: 'Mobile number verified',
        verified_proofs: ['Mobile number Verified'],
      },
      se: '7085fe192a542a5a54336250151a96ac',
      uid: 'gSH77642635',
      name: 'Chirag M',
      fullName: 'chirag mohan',
      firstName: 'chirag',
      lastName: 'mohan',
      slug: 'gSH77642635',
      userHandle: 'SH77642635',
      location: 'Ratlam, India',
      mrMs: 'Mr.',
    },
    iSH30270397: {
      base: {
        infoMap: [
          {
            key: 'info-0',
            label: 'Age / Height',
            value: '27, 5\' 8"',
          },
          {
            key: 'info-1',
            label: 'Religion/Community',
            value: 'Hindu, Gupta',
          },
          {
            key: 'info-2',
            label: 'Mother Tounge',
            value: 'Hindi',
          },
          {
            key: 'info-3',
            label: 'Profession',
            value: 'Dentist',
          },
          {
            key: 'info-4',
            label: 'Location',
            value: 'Sydney, Australia',
          },
        ],
        infoList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 8", Hindu, Hindi',
          },
          {
            key: 'profession',
            value: 'Dentist',
          },
          {
            key: 'location',
            value: 'Lives in Sydney, Australia',
          },
          {
            key: 'grew up in',
            value: 'Grew up in Australia',
          },
        ],
        detailList: [
          {
            key: 'age-height',
            value: '27, 5\' 8"',
          },
          {
            key: 'religion-caste',
            value: 'Hindu, Gupta',
          },
          {
            key: 'profession',
            value: 'Dentist',
          },
          {
            key: 'location',
            value: 'Sydney, Australia',
          },
        ],
        cardInfo: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 8"',
          },
          {
            key: 'religion-caste',
            value: 'Hindi, Hindu',
          },
          {
            key: 'profession',
            value: 'Dentist',
          },
          {
            key: 'location',
            value: 'Sydney, Australia',
          },
        ],
        premiumInfo: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 8", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Sydney, Australia',
          },
        ],
        miniList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 8", Hindu, Hindi',
          },
          {
            key: 'religion-caste',
            value: 'Gupta',
          },
          {
            key: 'location',
            value: 'Lives in Sydney, Australia',
          },
        ],
        miniNriList: [
          {
            key: 'age-height',
            value: '27 yrs, 5\' 8", Hindu, Hindi',
          },
          {
            key: 'grew up in',
            value: 'Grew up in Australia',
          },
          {
            key: 'location',
            value: 'Lives in Sydney, Australia',
          },
        ],
      },
      flags: {
        isFree: false,
        isPremium: true,
        membershipLevel: 'Premium',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'default',
        connectionAction: 'not_contacted',
        connectionJustNowText: null,
        contactAction: 'none',
        contactStatus: 'none',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: true,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'gold',
        isNameLocked: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        canViewPhotosOnConnectOnly: false,
        canPremiumMemberViewPhoto: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'visibleOnAccept',
        isIndianDiaspora: false,
        isHoroscopeApplicable: true,
        isFamilyGamified: true,
        isAstroReady: false,
        isHidden: false,
        hiddenReason: null,
        isBothPartyPayUser: false,
        canCommunicate: false,
      },
      presence: {
        onlineStatus: 'invisible',
        onlineStatusDetails: '...',
        onlineAt: 0,
        device: 'none',
        platform: 'none',
        lastOnline: '...',
        lastOnlineDetails: '...',
        lastOnlineStatus: '...',
        lastOnlineText: '...',
        ready: false,
        chatIcon: 'none',
      },
      summary: {
        infoMap: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '27, 5\' 8"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'community',
            label: 'Community',
            value: 'Gupta',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Sydney, Australia',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Honours degree - Medicine',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Dentist',
          },
        ],
        infoMapNonIndian: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '27, 5\' 8"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'location_nri_info',
            label: 'Location',
            value: 'Sydney,New South Wales, Australia',
          },
          {
            key: 'info-6',
            label: 'Grew up in',
            value: 'Australia',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Honours degree - Medicine',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Dentist',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '27 yrs, 5\' 8"',
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
          {
            key: 'religion_caste_list',
            label: 'Religion',
            value: 'Hindu, Gupta',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Sydney, Australia',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Dentist',
          },
        ],
        infoMapNri: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '27 yrs, 5\' 8"',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Dentist',
          },
          {
            key: 'religion_mother_tongue_list',
            label: 'Mother Tongue',
            value: 'Hindu, Hindi',
          },
          {
            key: 'location_nri_info_list',
            label: 'Location',
            value: 'Lives in Sydney,New South Wales, Australia',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Honours degree - Medicine',
          },
          {
            key: 'grew_up_in_info',
            label: 'Grew up in',
            value: 'Grew up in Australia',
          },
        ],
        listAlbum: ['https://img1.shaadi.com/2018/03/18/iSH30270397-e8de06-male.webp'],
        gridAlbum: ['https://img1.shaadi.com/2018/03/18/iSH30270397-869de0-male.webp'],
        photosLoading: true,
        shortBio: 'He is a kind a and caring person. He is very nice at heart',
        createdBy: 'Parent / Guardian',
        profileCreatedBy: 'Parent',
        shortlistCount: -1,
      },
      detailed: {
        album: ['https://img1.shaadi.com/2018/03/18/iSH30270397-869de0-male.webp'],
        albumRevamp: ['https://img1.shaadi.com/2018/03/18/iSH30270397-869de0-male.webp'],
        infoMap: [],
        infoMapRevamp: [],
        about: {
          title: 'About',
          titleRevamp: 'About',
          icon: 'about',
          desc: '',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mLifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mBackground: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [],
          hasCollegeOrEmployer: false,
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
        },
        family: {
          title: 'Family Details',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [],
        },
        trustBadges: [],
        commonInterests: [],
        conversationStarters: {
          items: [],
        },
        ready: false,
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
      photos: {
        count: 0,
        items: [],
        status: '',
        hasPhotos: false,
        canAddPhotos: false,
        isDefault: true,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
      },
      contactSummary: {
        sms: '',
        contact: {
          mobile_verified: 'yes',
          telephone_verified: 'yes',
          contact_number: '9737666147',
        },
        actionDate: '',
        dnd: '',
        hidden: '',
        hiddenReason: '',
        tempKey: '',
        contactType: '',
        photoStatus: '',
        photoCount: 0,
        profileContactStatus: '',
        contactDetailsStatusString: '',
        contactDetailsTitleStatusString: '',
      },
      connectMessages: [],
      thumbnailBlur: 'https://img1.shaadi.com/2018/03/18/iSH30270397-57cb23-male.webp',
      thumbnail: 'https://img1.shaadi.com/2018/03/18/iSH30270397-57cb23-male.webp',
      photoBlur: 'https://img1.shaadi.com/2018/03/18/iSH30270397-e8de06-male.webp',
      photoMedium: '/assets/default-photo.png',
      photo: 'https://img1.shaadi.com/2018/03/18/iSH30270397-e8de06-male.webp',
      fullPhotoBlur: 'https://img1.shaadi.com/2018/03/18/iSH30270397-869de0-male.webp',
      fullPhoto: 'https://img1.shaadi.com/2018/03/18/iSH30270397-869de0-male.webp',
      drAction: {},
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      gender: 'Male',
      tempId: '',
      verification: {
        count: 0,
        shield_state: '',
        derived_text: '',
        verified_proofs: [],
      },
      se: 'e31cc92cef0fe014cf12cc1ea17eee24',
      uid: 'iSH30270397',
      name: 'SH30270397',
      fullName: 'Ankur Gupta',
      firstName: 'Ankur',
      lastName: 'Gupta',
      slug: 'iSH30270397',
      userHandle: 'SH30270397',
      location: 'Sydney, Australia',
      mrMs: 'Mr.',
    },
    dSH78478399: {
      base: {
        infoMap: [
          {
            key: 'info-0',
            label: 'Age / Height',
            value: '30, 6\' 2"',
          },
          {
            key: 'info-1',
            label: 'Religion/Community',
            value: 'Hindu, Agarwal',
          },
          {
            key: 'info-2',
            label: 'Mother Tounge',
            value: 'Hindi',
          },
          {
            key: 'info-3',
            label: 'Profession',
            value: 'Sr. Manager / Manager',
          },
          {
            key: 'info-4',
            label: 'Location',
            value: 'Delhi, India',
          },
        ],
        infoList: [
          {
            key: 'age-height',
            value: '30 yrs, 6\' 2", Hindu, Hindi',
          },
          {
            key: 'profession',
            value: 'Sr. Manager / Manager',
          },
          {
            key: 'location',
            value: 'Lives in Delhi, India',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
        ],
        detailList: [
          {
            key: 'age-height',
            value: '30, 6\' 2"',
          },
          {
            key: 'religion-caste',
            value: 'Hindu, Agarwal',
          },
          {
            key: 'profession',
            value: 'Sr. Manager / Manager',
          },
          {
            key: 'location',
            value: 'Delhi, India',
          },
        ],
        cardInfo: [
          {
            key: 'age-height',
            value: '30 yrs, 6\' 2"',
          },
          {
            key: 'religion-caste',
            value: 'Hindi, Hindu',
          },
          {
            key: 'profession',
            value: 'Sr. Manager / Manager',
          },
          {
            key: 'location',
            value: 'Delhi, India',
          },
        ],
        premiumInfo: [
          {
            key: 'age-height',
            value: '30 yrs, 6\' 2", Hindu, Hindi',
          },
          {
            key: 'location',
            value: 'Delhi, India',
          },
        ],
        miniList: [
          {
            key: 'age-height',
            value: '30 yrs, 6\' 2", Hindu, Hindi',
          },
          {
            key: 'religion-caste',
            value: 'Agarwal',
          },
          {
            key: 'location',
            value: 'Lives in Delhi, India',
          },
        ],
        miniNriList: [
          {
            key: 'age-height',
            value: '30 yrs, 6\' 2", Hindu, Hindi',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
          {
            key: 'location',
            value: 'Lives in Delhi, India',
          },
        ],
      },
      flags: {
        isFree: false,
        isPremium: true,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'default',
        connectionAction: 'not_contacted',
        connectionJustNowText: null,
        contactAction: 'none',
        contactStatus: 'none',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: true,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'gold_plus',
        isNameLocked: true,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        canViewPhotosOnConnectOnly: false,
        canPremiumMemberViewPhoto: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: false,
        isHidden: false,
        hiddenReason: null,
        isBothPartyPayUser: false,
        canCommunicate: false,
      },
      presence: {
        onlineStatus: 'invisible',
        onlineStatusDetails: '...',
        onlineAt: 0,
        device: 'none',
        platform: 'none',
        lastOnline: '...',
        lastOnlineDetails: '...',
        lastOnlineStatus: '...',
        lastOnlineText: '...',
        ready: false,
        chatIcon: 'none',
      },
      summary: {
        infoMap: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '30, 6\' 2"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'community',
            label: 'Community',
            value: 'Agarwal',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Delhi, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Masters - Management',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Sr. Manager / Manager',
          },
        ],
        infoMapNonIndian: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '30, 6\' 2"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'location_nri_info',
            label: 'Location',
            value: 'Delhi,Delhi-NCR, India',
          },
          {
            key: 'info-6',
            label: 'Grew up in',
            value: 'India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Masters - Management',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Sr. Manager / Manager',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '30 yrs, 6\' 2"',
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
          {
            key: 'religion_caste_list',
            label: 'Religion',
            value: 'Hindu, Agarwal',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Delhi, India',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Hindi',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Sr. Manager / Manager',
          },
        ],
        infoMapNri: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '30 yrs, 6\' 2"',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Sr. Manager / Manager',
          },
          {
            key: 'religion_mother_tongue_list',
            label: 'Mother Tongue',
            value: 'Hindu, Hindi',
          },
          {
            key: 'location_nri_info_list',
            label: 'Location',
            value: 'Lives in Delhi,Delhi-NCR, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Masters - Management',
          },
          {
            key: 'grew_up_in_info',
            label: 'Grew up in',
            value: 'Grew up in India',
          },
        ],
        listAlbum: ['https://img1.shaadi.com/2017/11/27/dSH78478399-55e3ae-male.webp'],
        gridAlbum: ['https://img1.shaadi.com/2017/11/27/dSH78478399-5c97a4-male.webp'],
        photosLoading: true,
        shortBio: 'My son is highly qualifiedI am a businessman, now mostly part-time',
        createdBy: 'Parent / Guardian',
        profileCreatedBy: 'Parent',
        shortlistCount: -1,
      },
      detailed: {
        album: ['https://img1.shaadi.com/2017/11/27/dSH78478399-5c97a4-male.webp'],
        albumRevamp: ['https://img1.shaadi.com/2017/11/27/dSH78478399-5c97a4-male.webp'],
        infoMap: [],
        infoMapRevamp: [],
        about: {
          title: 'About',
          titleRevamp: 'About',
          icon: 'about',
          desc: '',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mLifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        mBackground: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [],
          hasCollegeOrEmployer: false,
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
        },
        family: {
          title: 'Family Details',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [],
        },
        trustBadges: [],
        commonInterests: [],
        conversationStarters: {
          items: [],
        },
        ready: false,
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
      photos: {
        count: 0,
        items: [],
        status: '',
        hasPhotos: false,
        canAddPhotos: false,
        isDefault: true,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
      },
      contactSummary: {
        sms: '',
        contact: {
          mobile_verified: 'yes',
          telephone_verified: 'yes',
          contact_number: '9737666147',
        },
        actionDate: '',
        dnd: '',
        hidden: '',
        hiddenReason: '',
        tempKey: '',
        contactType: '',
        photoStatus: '',
        photoCount: 0,
        profileContactStatus: '',
        contactDetailsStatusString: '',
        contactDetailsTitleStatusString: '',
      },
      connectMessages: [],
      thumbnailBlur: 'https://img1.shaadi.com/2017/11/27/dSH78478399-bf927d-male.webp',
      thumbnail: 'https://img1.shaadi.com/2017/11/27/dSH78478399-bf927d-male.webp',
      photoBlur: 'https://img1.shaadi.com/2017/11/27/dSH78478399-55e3ae-male.webp',
      photoMedium: '/assets/default-photo.png',
      photo: 'https://img1.shaadi.com/2017/11/27/dSH78478399-55e3ae-male.webp',
      fullPhotoBlur: 'https://img1.shaadi.com/2017/11/27/dSH78478399-5c97a4-male.webp',
      fullPhoto: 'https://img1.shaadi.com/2017/11/27/dSH78478399-5c97a4-male.webp',
      drAction: {},
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      gender: 'Male',
      tempId: '',
      verification: {
        count: 0,
        shield_state: '',
        derived_text: '',
        verified_proofs: [],
      },
      se: '1a05c6b1002feb9bac7dd4a502fa028e',
      uid: 'dSH78478399',
      name: 'Rohan G',
      fullName: 'Rohan Gupta',
      firstName: 'Rohan',
      lastName: 'Gupta',
      slug: 'dSH78478399',
      userHandle: 'SH78478399',
      location: 'Delhi, India',
      mrMs: 'Mr.',
    },
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  topSpace: 0,
  windowWidth: 1197,
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: false,
    showUpgradeBanner: true,
    canAccessChat: true,
    canInitiateChat: false,
    hasUploadedPhoto: false,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: null,
    contactsRemaining: null,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: true,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '9379732670',
    wasPaidUser: false,
    expiryDate: '',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'B',
      },
      offline_otp: {
        bucket: 'B',
      },
      inbox_revamp: {
        bucket: 'A',
      },
      track_events: {
        bucket: 'A',
      },
      profilepage_revamp_abc: {
        bucket: 'A',
      },
      profile_contact_card: {
        bucket: 'A',
      },
    },
    membershipTags: 'free',
    offerCode: 'octbd60h2',
    offer_details: [
      {
        type: 'perc',
        value: 60,
      },
    ],
  },
  shortlistItems: [
    {
      key: 'sl-6761137',
      id: '6761137',
      label: "My Maybe's",
    },
  ],
  profilePageLeftBanner: {
    img: {
      src: '',
      alt: '',
      title: '',
      height: 0,
      width: 0,
    },
    url: '',
    isExternal: true,
    isVisible: false,
  },
  membership: 'Free',
  onProfileInit() {},
  doProfileAction() {},
  doDaTracking() {},
  layout: 'desktop',
};

const factory = { props };

it('should export profiles and props', () => {
  expect(factory.props).not.toBeFalsy();
});

export default factory;
/* eslint-enable max-len */
