import DEVICE from '../helpers/device';

export default {
  MAX_PHOTO_COUNTS: 20,
  DEVICE,
  NODE_API_ENDPOINT: 'https://ww4.shaadi.com/api/',
  UPLOAD_FILE_URL: 'https://upload-file.shaadi.com/api/',
  PHOTO_DISPLAY_SETTING: {
    SHOW_ALL: 'Show All',
    WHEN_I_CONTACT: 'When I Contact',
    ONLY_WHEN_I_CONTACT: 'Only When I Contact',
    SHOW_ALL_LC: 'show all',
    WHEN_I_CONTACT_LC: 'when i contact',
    ONLY_WHEN_I_CONTACT_LC: 'only when i contact',
  },
  PHOTO_STATUS: {
    COMING_SOON: 'coming_soon',
    SHOW_PHOTO: 'show_photo',
    ADD_PHOTO: 'add_photo',
  },
  SHAADI_URL: 'www.shaadi.com',
  URI: {
    loginPage: '/registration/user/login',
    incompleteProfilePage: '/registration/profile/incomplete',
    myShaadi: '/my-shaadi',
  },
  validProfileFieldSet: [
    'account',
    'basic',
    'lifestyle',
    'health_info',
    'appearance',
    'family',
    'trait',
    'origin',
    'doctrine',
    'account',
    'location',
    'profession',
    'education',
    'interests_and_more',
    'activity_factor',
  ],
  validProfilePhotoFieldSet: ['count', 'photos'],
  validPhotoSizes: [
    'small',
    'medium',
    'semilarge',
    'large',
    '40X40',
    '60X60',
    '120X120',
    '150X200',
    '250X310',
    '400X500',
    '450X600',
    '720X1006',
    '750X1333',
  ],
  isStoppage: /^\/stop-page\//i.test(window.location.pathname),
  isRegPage: /^\/registration\//i.test(window.location.pathname),
  isMyShaadiPage: /^\/my-shaadi\//i.test(window.location.pathname),
  isPaymentCart: ['/cart', '/payment', '/payment/thankyou'],
  LITE_APP_PLATFORM: 'lite-native-android',
  isPaymentPage: ['/payment'],
  mobileNumberMaxLength: {
    Austria: 12,
    Malaysia: 10,
    Germany: 11,
    Brazil: 11,
    China: 11,
    'United Kingdom': 10,
    India: 10,
    Canada: 10,
    USA: 10,
    Indonesia: 12,
  },
  mobileNumberMinLength: {
    India: 10,
    Canada: 10,
    USA: 10,
  },
  descriptionPlaceholder:
    'Example: I am a successful professional working with a well known company. We are a close-knit family with modern values. I enjoy reading and music and I am looking or someone who believes that marriage is a journey for growth and fulfilment.',
};
