const singleItem = {
  uid: 'uid-test1',
  fullPhoto: '',
  name: 'test1',
  justNow: false,
  photoLoading: false,
  eoiLoadingStyle: 'none',
  eoiClose: false,
};

const singleProfile = {
  uid: 'uid-test2',
  fullPhoto: '',
  name: 'test2',
  heShe: 'He',
  himHer: 'Him',
  hisHer: 'His',
  isSameGender: false,
  presence: {
    lastOnlineDetails: 'Online now',
    onlineStatus: 'Online',
    chatIcon: 'web_online',
  },
  base: {
    premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
  },
  summary: {
    createdBy: 'Self',
    gridAlbum: [],
    shortBio: '',
    infoMap: [
      {
        key: 'location',
        label: 'Location',
        value: 'Vadodara, India',
      },
    ],
    infoMapIndian: [
      {
        key: 'age_height_list',
        label: 'Age / Height',
        value: "28 yrs, 5' 6",
      },
      {
        key: 'marital_status',
        label: 'Marital Status',
        value: 'Never Married',
      },
    ],
    infoMapNri: [
      { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
      { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
      { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
      { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
      { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
      { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
    ],
    infoMapPremiumCarousel: [],
  },
  flags: {
    isFree: true,
    isPremium: false,
    membershipLevel: 'none',
    connectionNote: null,
    connectionError: false,
    connectionStatus: 'accepted',
    connectionAction: 'member_accepted',
    connectionJustNowText: null,
    contactAction: 'available',
    contactStatus: 'available',
    horoscopeStatus: 'none',
    loading: 'none',
    isDeleted: false,
    isNri: false,
    isWatermarked: true,
    isTwoWayMatch: false,
    isBoldListing: false,
    canUnblock: false,
    unblockMessage: null,
    canUnignore: false,
    canRemind: false,
    canCancelInvite: true,
    isSameGender: false,
    activeStatus: 'default',
    isPreferredMatch: false,
    isConnectLimitExceeded: false,
    showHistory: false,
    membershipTags: 'free',
    isNameLocked: false,
    isMaskedProfile: false,
    canCallSendSMS: false,
    canSendEmail: false,
    canSendEmailReminder: false,
    canSendSMS: false,
    canViewPhoneNo: false,
    isPhoneNoViewed: false,
    isSmsAlreadySent: false,
    showChatNow: false,
    showPostOnWall: false,
    isFiltered: false,
    horoscopeStyle: 'l/HIN/hs/1',
    albumStatus: 'photoRequestSent',
    isIndianDiaspora: true,
    isHoroscopeApplicable: true,
    isFamilyGamified: false,
    isAstroReady: true,
    isHidden: false,
    isBothPartyPayUser: false,
  },
  requests: {
    count: 0,
  },
  shortlists: {
    selected: [],
    ready: false,
    count: 0,
  },
};
const premiumCarouselProps = {
  profiles: {},
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [],
    justNow: false,
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
      premium_carousel: {
        bucket: 'B',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};
const lessThreeItemProps = {
  profiles: {
    'uid-test1': {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        uid: 'uid-test1',
        fullPhoto: '',
        name: 'test1',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        eoiClose: false,
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};
const threeItemProps = {
  profiles: {
    'uid-test1': {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test2': {
      uid: 'uid-test2',
      fullPhoto: '',
      name: 'test2',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test3': {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        uid: 'uid-test1',
        fullPhoto: '1',
        name: 'test1',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        eoiClose: false,
      },
      {
        uid: 'uid-test2',
        fullPhoto: '2',
        name: 'test2',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        eoiClose: false,
      },
      {
        uid: 'uid-test3',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        eoiClose: false,
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};
const greaterThreeItemProps = {
  profiles: {
    'uid-test1': {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test2': {
      uid: 'uid-test2',
      fullPhoto: '',
      name: 'test2',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test3': {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test4': {
      uid: 'uid-test4',
      fullPhoto: '',
      name: 'test4',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [
          {
            key: 'location',
            label: 'Location',
            value: 'Vadodara, India',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: "28 yrs, 5' 6",
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '24 yrs, 5\' 0"' },
          { key: 'profession', label: 'Profession', value: 'Training Professional (Others)' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Hindu, Tamil' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Chennai,Tamil Nadu, India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Engineering/ Technology' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'none',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    'uid-test5': {
      ...singleProfile,
      uid: 'uid-test5',
      name: 'test5',
    },
    'uid-test6': {
      ...singleProfile,
      uid: 'uid-test6',
      name: 'test6',
    },
    'uid-test7': {
      ...singleProfile,
      uid: 'uid-test7',
      name: 'test7',
    },
    'uid-test8': {
      ...singleProfile,
      uid: 'uid-test8',
      name: 'test8',
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        ...singleItem,
      },
      {
        ...singleItem,
        uid: 'uid-test2',
        name: 'test2',
      },
      {
        ...singleItem,
        uid: 'uid-test3',
        name: 'test3',
      },
      {
        ...singleItem,
        uid: 'uid-test4',
        name: 'test4',
      },
      {
        ...singleItem,
        uid: 'uid-test5',
        name: 'test5',
      },
      {
        ...singleItem,
        uid: 'uid-test6',
        name: 'test6',
      },
      {
        ...singleItem,
        uid: 'uid-test7',
        name: 'test7',
      },
      {
        ...singleItem,
        uid: 'uid-test8',
        name: 'test8',
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};

const factory = {
  premiumCarouselProps,
  lessThreeItemProps,
  threeItemProps,
  greaterThreeItemProps,
};
it('should export premiumCarouselProps', () => {
  expect(factory.premiumCarouselProps).not.toBeFalsy();
  expect(factory.lessThreeItemProps).not.toBeFalsy();
  expect(factory.greaterThreeItemProps).not.toBeFalsy();
});
export default factory;
