const props = {
  profileUrl:
    '/profile?profileid=qSH73251586&pg_show_from=1&np=search-result&evt_ref=bWF0Y2hlcy1uZXdfbWF0Y2hlc191bnZpZXdlZA==&navigation=1&profileNumber=2&pg_searchresults_id=search:42efdd941783200f7ab8e98cae39a461&datasrc=api&pg_ubt=L3NlYXJjaC9uZXctbWF0Y2hlc3x8MjA=&featured=N',
  albumUrl:
    'https://www.shaadi.com/profile/index/view-album-photos/profileid/qSH73251586/navigation/1/profileNumber/2/evt_ref/bWF0Y2hlcy1uZXdfbWF0Y2hlc191bnZpZXdlZA==/pg_searchresults_id/search:42efdd941783200f7ab8e98cae39a461',
  isSpotLight: false,
  isSelected: false,
  isHovered: false,
  isNewMatchHovered: false,
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: false,
    showUpgradeBanner: true,
    canAccessChat: true,
    canInitiateChat: false,
    hasUploadedPhoto: false,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: null,
    contactsRemaining: null,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: true,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '9379732670',
    wasPaidUser: false,
    expiryDate: '',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'B',
      },
      offline_otp: {
        bucket: 'B',
      },
      inbox_revamp: {
        bucket: 'A',
      },
      track_events: {
        bucket: 'A',
      },
    },
    membershipTags: 'free',
    offerCode: '',
    offer_details: '',
  },
  profile: {
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '28, 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Hindu, Kashyap',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Hindi',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Software Professional (Others)',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Sydney, Australia',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 8", Hindu, Hindi',
        },
        {
          key: 'profession',
          value: 'Software Professional (Others)',
        },
        {
          key: 'location',
          value: 'Lives in Sydney, Australia',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '28, 5\' 8"',
        },
        {
          key: 'religion-caste',
          value: 'Hindu, Kashyap',
        },
        {
          key: 'profession',
          value: 'Software Professional (Others)',
        },
        {
          key: 'location',
          value: 'Sydney, Australia',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 8", Hindu, Hindi',
        },
        {
          key: 'location',
          value: 'Sydney, Australia',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 8", Hindu, Hindi',
        },
        {
          key: 'religion-caste',
          value: 'Kashyap',
        },
        {
          key: 'location',
          value: 'Lives in Sydney, Australia',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '28 yrs, 5\' 8", Hindu, Hindi',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
        {
          key: 'location',
          value: 'Lives in Sydney, Australia',
        },
      ],
    },
    flags: {
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'default',
      connectionAction: 'not_contacted',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'availableOnVerification',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: true,
      isWatermarked: true,
      isTwoWayMatch: true,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      isMaskedProfile: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/undefined/hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: true,
      isFamilyGamified: false,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Idle',
      onlineStatusDetails: '...',
      onlineAt: 1521705542000,
      device: 'web',
      platform: 'web',
      lastOnline: 'Last online, 48 mins ago',
      lastOnlineDetails: 'Online 1h ago',
      ready: true,
      chatIcon: 'web_idle',
    },
    summary: {
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '28, 5\' 8"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Hindi',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Kashyap',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Sydney, Australia',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Computers/ IT',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Software Professional (Others)',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '28, 5\' 8"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Hindi',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Sydney,New South Wales, Australia',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Computers/ IT',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Software Professional (Others)',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '28 yrs, 5\' 8"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Hindu, Kashyap',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Sydney, Australia',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Hindi',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Software Professional (Others)',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '28 yrs, 5\' 8"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Software Professional (Others)',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Hindu, Hindi',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Sydney,New South Wales, Australia',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Computers/ IT',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India',
        },
      ],
      listAlbum: [
        'https://img1.shaadi.com/2018/03/22/qSH73251586-65e46d-male.webp',
        'https://img1.shaadi.com/2018/03/22/qSH73251586-819f9b-male.webp',
        'https://img1.shaadi.com/2018/03/22/qSH73251586-1b3d1f-male.webp',
        'https://img2.shaadi.com/imgs/profiles/150-photo-coming-soon-m.gif',
      ],
      gridAlbum: [
        'https://img1.shaadi.com/2018/03/22/qSH73251586-edb5d5-male.webp',
        'https://img1.shaadi.com/2018/03/22/qSH73251586-fa24af-male.webp',
        'https://img1.shaadi.com/2018/03/22/qSH73251586-fdc10b-male.webp',
        'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-m.gif',
      ],
      shortBio: 'Smart, I am living in Australia from last 3 years, currently living in Sydney, Australia and intend to settle here only.',
      createdBy: 'Parent / Guardian',
      profileCreatedBy: 'Parent',
      shortlistCount: 0,
    },
    detailed: {
      album: ['https://img1.shaadi.com/2018/03/22/qSH73251586-edb5d5-male.webp'],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: true,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2018/03/22/qSH73251586-85e5b4-male.webp',
    thumbnail: 'https://img1.shaadi.com/2018/03/22/qSH73251586-85e5b4-male.webp',
    photoBlur: 'https://img1.shaadi.com/2018/03/22/qSH73251586-65e46d-male.webp',
    photoMedium: '/assets/default-photo.png',
    photo: 'https://img1.shaadi.com/2018/03/22/qSH73251586-65e46d-male.webp',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/03/22/qSH73251586-edb5d5-male.webp',
    fullPhoto: 'https://img1.shaadi.com/2018/03/22/qSH73251586-edb5d5-male.webp',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 0,
      shield_state: '',
      derived_text: '',
      verified_proofs: [],
    },
    se: '69477495232f1556b264e7c2f22b1802',
    uid: 'qSH73251586',
    name: 'Sahil C',
    fullName: 'Sahil Chaudhary',
    firstName: 'Sahil',
    lastName: 'Chaudhary',
    slug: 'qSH73251586',
    userHandle: 'SH73251586',
    location: 'Sydney, Australia',
    mrMs: 'Mr.',
  },
  tooltip: {
    key: 'none',
    page: 'none',
    position: 'none',
    title: null,
    body: [],
    loading: false,
  },
  item: {
    uid: 'qSH73251586',
    justNow: false,
    eoiLoadingStyle: 'none',
    photoLoading: false,
    actionType: '',
    displayStatusMessage: '',
  },
  shortlistItems: [
    {
      key: 'sl-6761137',
      id: '6761137',
      label: "My Maybe's",
    },
  ],
  wwwBaseUrl: 'https://www.shaadi.com',
  membershipTags: 'free',
  onAction() {},
  onMouseEnter() {},
  onMouseLeave() {},
  onShowContactDetails() {},
  onChatNow() {},
  onShowWatermarkInfo() {},
  onEoiTooltipClose() {},
  onPhotoTooltipClose() {},
  onRequestPhoto() {},
  onRequestPassword() {},
  onShortlistOpen() {},
  onDirectlyShortlist() {},
  onDirectlyRemoveShortlist() {},
  onDirectlyIgnore() {},
  onNewMatchMouseEnter() {},
  onNewMatchMouseLeave() {},
  daTracking() {},
  onCallConsultantInvited() {},
  onClick() {},
};

export default props;
