const factory = {
  match: {
    path: '/profile-creation/step/:stepNumber',
    url: '/profile-creation/step/1',
    isExact: true,
    params: {
      stepNumber: '1',
    },
  },
  location: {
    pathname: '/profile-creation/step/1',
    search: '',
    hash: '',
  },
  history: {
    block() {},
    createHref() {},
    go() {},
    goBack() {},
    goForward() {},
    listen() {},
    push() {},
    replace() {},
    action: '',
    length: 0,
    location: {
      pathname: '/profile-creation/step/1',
      search: '',
      hash: '',
    },
  },
  loading: false,
  getDrawerOpenedFor() {},
  getDrawerField() {},
  addressUserBy() {},
  lookup: {
    countries: [],
    states: {},
    cities: {
      Qatar: {
        Kuwait: {
          frequent: [],
          other: [{}, {}],
        },
      },
    },
    districts: {
      Qatar: {
        Kuwait: {
          frequent: [],
          other: [{}, {}],
        },
      },
    },
    zipcode: [],
    caste: {},
    subCaste: {},
    height: {},
    income: [],
    domains: [],
    gotra: [],
    nakshatras: [],
    rashis: [],
    doshamTypes: [],
    ethnicity: [],
  },
  user: {
    casteForGotraNakshatra: [
      'Baidya',
      'Banik',
      'Barujibi',
      'Brahmin',
      'Brahmin - Anavil',
      'Brahmin - Audichya',
      'Brahmin - Bengali',
      'Brahmin - Bhatt',
      'Brahmin - Bhumihar',
      'Brahmin - Daivadnya',
      'Brahmin - Deshastha',
      'Brahmin - Garhwali',
      'Brahmin - Gour',
      'Brahmin - Gowd Saraswat',
      'Brahmin - Havyaka',
      'Brahmin - Himachali',
      'Brahmin - Iyengar',
      'Brahmin - Iyer',
      'Brahmin - Jhijhotiya',
      'Brahmin - Kannada Madhva',
      'Brahmin - Kanyakubja',
      'Brahmin - Kokanastha',
      'Brahmin - Kulin',
      'Brahmin - Kumaoni',
      'Brahmin - Madhwa',
      'Brahmin - Maharashtrian',
      'Brahmin - Maithili',
      'Brahmin - Nagar',
      'Brahmin - Panda',
      'Brahmin - Punjabi',
      'Brahmin - Sanadya',
      'Brahmin - Saraswat',
      'Brahmin - Saryuparin',
      'Brahmin - Smartha',
      'Brahmin - Sri Vaishnava',
      'Brahmin - Telugu',
      'Brahmin - Vaidiki',
      'Chandravanshi Kahar',
      'CKP',
      'Kalinga',
      'Kalita',
      'Karana',
      'Kashyap',
      'Khandayat',
      'Leva Patil',
      'Jetty Malla',
      'Maratha - Gomantak',
      'Namasudra',
      'Patra',
      'Rajput - Garhwali',
      'Sadgop',
      'Saha',
      'Sundhi',
      'Varshney',
      'Viswabrahmi',
    ],
    isLoggedIn: true,
    isLoggedOut: false,
    uid: 'qSH60666724',
    gender: 'male',
    complexion: '',
    built: '',
    height: '',
    diet: '',
    drink: '',
    smoke: '',
    aboutMe: '',
    hasProfilePhoto: false,
    photos: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    mrMs: 'Mr.',
    heSheOrYou: 'You',
    himHerOrYou: 'You',
    hisHerOrYou: 'You',
    mrMsOrYou: 'You',
    heSheOrYour: 'Your',
    himHerOrYour: 'Your',
    hisHerOrYour: 'Your',
    mrMsOrYour: 'Your',
    location: {
      country: 'Qatar',
      state: 'Al Ghuwariyah',
      district: '',
      residency_status: 'Citizen',
      zip_code: '',
      zip_status: '',
      google_city_id: 0,
      living_since: '',
      city: 'Other',
    },
    doctrine: {
      religion: 'Hindu',
      caste: 'Brahmin - Iyengar',
      sub_caste: '',
      mother_tongue: 'Tamil',
      gotra: 'Aatharvas',
    },
    account: {
      posted_by: 'Self',
      status: 'Incomplete',
    },
    basic: {
      gender: 'Male',
      date_of_birth: '19970101',
      marital_status: 'Never Married',
      first_name: '',
      last_name: '',
    },
    family: {
      children: '',
      no_of_kids: '',
      father_profession: '',
      mother_profession: '',
      brothers_unmarried: '',
      brothers_married: '',
      sisters_unmarried: '',
      sisters_married: '',
      located: '',
      type: '',
      family_income: '',
      family_values: '',
    },
    appearance: {
      complexion: '',
      built: '',
      height: '',
    },
    education: {
      education: '',
      education_stream: '',
      college_1: '',
      education_alias: '',
      education_field: '',
    },
    profession: {
      occupation: '',
      working_with: '',
      employer: '',
      income: '',
    },
    trait: {
      about_me: '',
      personality: [],
    },
    health_info: {
      special_cases: 'None',
    },
    lifestyle: {
      diet: '',
      drink: '',
      smoke: '',
    },
    grewupIn: {},
    hasLocation: true,
    hasDoctrine: false,
    hasAccount: false,
    hasBasic: true,
    hasFamily: false,
    hasEducation: true,
    hasProfession: true,
    hasPhotoDetails: false,
    hasTrait: true,
    hasHealthInfo: true,
    hasAppearance: true,
    hasLifestyle: true,
    form: {},
    family_details: [],
    metadata: {
      domain: 'www.shaadi.com',
    },
    'astro-details': {
      birth_star_nakshatra: 'Chitra',
      moon_sign: '',
      manglik: '',
      other_dosham: '',
      suddha_jadhagam: '',
    },
    origin: {
      native_place: '',
      ethnicity: 'Other',
      grewup_in: ['Australia', 'Canada', 'Australia', 'Canada'],
    },
    'contact-details': {
      mobile_country: '',
      mobile_isd: '',
      mobile_std: '',
      mobile: '',
      tel_std: '',
      telephone: '',
      contact_settings: '',
    },
    error: {
      error: 'Y',
      error_page_name: '#reg2_2',
    },
    interests_and_more: {
      interests: [],
    },
    hasMetaData: true,
    firstName: '',
    lastName: '',
    maritalStatus: 'Never Married',
    dateOfBirth: 19970101,
    personality: [],
    specialCased: 'None',
    highestQualification: '',
    graduationCollege: '',
    currentIncome: '',
    currentEmployer: '',
    occupation: '',
    country: 'Qatar',
    state: 'Al Ghuwariyah',
    city: 'Other',
    isIndian: () => false,
    isNRI: () => true,
    countryISO: 'QAT',
    canShowZip: () => true,
    canShowEthnicity: () => true,
    domain: 'www.shaadi.com',
    isCommunityDomain: false,
    status: 'Incomplete',
    postedBy: 'Self',
    district: '',
    google_city_id: 0,
    livingSince: '',
    residency_status: 'Citizen',
    zipCode: '',
    zip_status: '',
    religion: 'Hindu',
    caste: 'Brahmin - Iyengar',
    sub_caste: '',
    motherTongue: 'Tamil',
    gotra: 'Aatharvas',
    children: '',
    father_profession: '',
    mother_profession: '',
    brothers_married: '',
    sisters_married: '',
    no_of_kids: '',
    type: '',
    located: '',
    family_income: '',
    maritalStatusKnown: true,
    isUnmarried: true,
    hasChildren: false,
    isPostedBySelf: () => true,
    isPostedByParent: () => false,
    isPostedByRelative: () => false,
    isPostedByFriend: () => false,
    relationWithProfileCreator: 'yourself',
    isMale: () => true,
    isFemale: () => false,
    doOrDoes: () => 'Do',
    isHindu: () => true,
    isMuslim: () => false,
    isChristian: () => false,
    isJain: () => false,
    isSikh: () => false,
    isParsi: () => false,
    isTamil: () => true,
    isTelugu: () => true,
    isMalyalam: () => true,
    isHinduTamil: () => true,
    isIndianHinduMallu: () => () => true,
    isReligiousSouthIndian: () => true,
    birthYear: 1997,
    birthMonth: 1,
    birthData: 1,
    nakshatra: 'Chitra',
    getLivingSinceList: [
      {
        id: 'birth',
        text: 'Birth',
      },
      {
        id: 1998,
        text: 1998,
      },
      {
        id: 1999,
        text: 1999,
      },
      {
        id: 2000,
        text: 2000,
      },
      {
        id: 2001,
        text: 2001,
      },
      {
        id: 2002,
        text: 2002,
      },
      {
        id: 2003,
        text: 2003,
      },
      {
        id: 2004,
        text: 2004,
      },
      {
        id: 2005,
        text: 2005,
      },
      {
        id: 2006,
        text: 2006,
      },
      {
        id: 2007,
        text: 2007,
      },
      {
        id: 2008,
        text: 2008,
      },
      {
        id: 2009,
        text: 2009,
      },
      {
        id: 2010,
        text: 2010,
      },
      {
        id: 2011,
        text: 2011,
      },
      {
        id: 2012,
        text: 2012,
      },
      {
        id: 2013,
        text: 2013,
      },
      {
        id: 2014,
        text: 2014,
      },
      {
        id: 2015,
        text: 2015,
      },
      {
        id: 2016,
        text: 2016,
      },
      {
        id: 2017,
        text: 2017,
      },
      {
        id: 2018,
        text: 2018,
      },
    ],
  },
  completedStepNumber: 1,
  canShowStepper: () => false,
  currentStep: 1,
  session: {
    uid: 'qSH60666724',
    document: {
      title: '',
    },
    experiments: {},
    areExperimentsFetched: false,
    exitIntent: null,
    settings: {
      defaultSearchFormat: 'list',
      isPaidUser: false,
      showUpgradeBanner: false,
      canAccessChat: false,
      canInitiateChat: false,
      hasUploadedPhoto: true,
      canConnectWithMessage: false,
      showUpgradeLinks: true,
      canSendPasswordOnConnect: false,
      contactsTotal: 0,
      contactsRemaining: 0,
      isUnderScreening: false,
      isAstroGamified: false,
      gender: 'none',
      canViewCollegeAndEmployer: false,
      canViewHoroscope: false,
      horoscopeStyle: 'l/ENG/hs/1',
      isFamilyGamified: false,
      isHidden: false,
      isBothPartyPayUser: false,
      isMobileVerified: false,
      mobileNumber: '',
    },
    shortlists: {
      items: [],
    },
    isLoggedIn: true,
    isLoggedOut: false,
    searchPremiumBanner: {
      isPremiumBannerVisible: false,
      premiumBanner: {},
    },
    nextUrl: '/my-shaadi',
    isNative: false,
    isStoppage: false,
    canShowSkip: () => false,
    canShowChat: () => false,
    showPageLoader: false,
    isUserFetchComplete: true,
    isRegPhotoPage: false,
    isCartPage: false,
    isMyShaadiPage: false,
    isProfileCreationPage: true,
    isPaymentPage: false,
    canCallAppInit: false,
    needMainPadding: false,
  },
  config: {
    app: {
      platform: 'web',
      wwwBaseUrl: 'https://www.shaadi.com',
      domainName: 'shaadi.com',
    },
  },
  title: 'Matrimonial link India - Free matrimonials for hindu muslim sikh christian -',
  controlInput() {},
  renderErrorField() {},
  getBasicAttributes() {},
  doLookUp() {},
  onSave() {},
  createProfile() {},
  doDomActions() {},
  getBasicDrawerField() {},
  closeDrawer() {},
  isDrawerOpen() {},
  isAPIFailed: false,
  layout: 'desktop',
  isMobile: false,
  drawerProps: {
    openDrawer() {},
    layout: '',
  },
};

it('should export profiles and props', () => {
  expect(factory).not.toBeFalsy();
});

export default factory;
