const allData = {
  chat: {
    settings: {
      status: 'offline',
      page: 'on',
      isOpen: false,
      activeTab: 'online',
      profileCardDisplay: false,
    },
  },
  config: {
    app: {
      wwwBaseUrl: 'https://www.shaadi.com',
      webp: '1',
    },
  },
  session: {
    isLoggedOut: false,
  },
  profiles: {
    self: {
      photos: {
        count: 0,
        items: [],
        status: '',
        hasPhotos: false,
        canAddPhotos: true,
        isDefault: true,
        isRejectedPhotosFetched: true,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
        isDefault: true,
        isRejectedPhotosFetched: true,
      },
      gender: 'Male',
    },
  },
  view: {
    width: 1106,
    topSpace: 0,
  },
  location: {
    path: '/my-shaadi/photos',
    pathname: 'My Photos',
    search: '',
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  isLoggedOut: false,
  isChatOpen: true,
  topSpace: 0,
  windowWidth: 1000,
  webp: '1',
};

const profileWithPhotos = {
  selfProfile: {
    photos: {
      count: 4,
      items: [
        {
          status: 'Y',
          photo_order: 0,
          profile_photo: true,
          domain_name: 'https://img2.shaadi.com',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          isProfilePhoto: true,
          cantDeletePhotoReason: 'Please make another album photo as profile photo first!',
          isPhotoScreened: true,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: false,
          canMakeProfilePhoto: false,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
        {
          domain_name: 'https://img2.shaadi.com',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          status: 'Y',
          photo_order: 1,
          profile_photo: false,
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          isProfilePhoto: true,
          isPhotoScreened: true,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: false,
          canMakeProfilePhoto: false,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
        {
          domain_name: 'https://img2.shaadi.com',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          status: 'Y',
          photo_tag: 'group',
          photo_order: 2,
          profile_photo: false,
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          isProfilePhoto: true,
          isPhotoScreened: true,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: false,
          cantMakeProfilePhotoReason: true,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
        {
          status: 'P',
          photo_order: 3,
          profile_photo: false,
          domain_name: 'https://img2.shaadi.com',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          isProfilePhoto: true,
          isPhotoScreened: false,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: false,
          canMakeProfilePhoto: false,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
        {
          status: 'N',
          photo_order: 4,
          photo_tag: 'group',
          profile_photo: false,
          domain_name: 'https://img2.shaadi.com',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          isProfilePhoto: true,
          isPhotoScreened: false,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: true,
          canMakeProfilePhoto: false,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
      ],
      status: 'coming_soon',
      hasPhotos: true,
      canAddPhotos: true,
      isDefault: false,
      isRejectedPhotosFetched: true,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
      isDefault: true,
      isRejectedPhotosFetched: true,
    },
    gender: 'Male',
  },
};

const profileWithProfilePhoto = {
  selfProfile: {
    photos: {
      count: 4,
      items: [
        {
          domain_name: 'https://img2.shaadi.com',
          small: '/imgs/profiles/60-photo-coming-soon-f.gif',
          medium: '/imgs/profiles/150-photo-coming-soon-f.gif',
          semilarge: '/imgs/profiles/250-photo-coming-soon-f.gif',
          large: '/imgs/profiles/photo-400-coming-soon-f.jpg',
          status: 'P',
          photo_order: 0,
          profile_photo: true,
          '40X40': '',
          '60X60': '/imgs/profiles/60-photo-coming-soon-f.gif',
          '120X120': '',
          '150X200': '/imgs/profiles/150-photo-coming-soon-f.gif',
          '250X310': '/imgs/profiles/250-photo-coming-soon-f.gif',
          '400X500': '/imgs/profiles/photo-400-coming-soon-f.jpg',
          '450X600': '',
          '750X1333': '',
          isProfilePhoto: true,
          isPhotoScreened: false,
          isPhotoUnderScreening: true,
          isProfilePhotoScreened: false,
          isPhotoRejected: false,
          canMakeProfilePhoto: false,
          canShowPhotoOpts: true,
          isGroupPhoto: false,
          isPhotoOptsOpen: false,
          getPhotoName: 'Profile Photo',
          getUrlForAlbumPage: 'https://img2.shaadi.com/imgs/profiles/250-photo-coming-soon-f.gif',
        },
      ],
      status: 'coming_soon',
      hasPhotos: true,
      canAddPhotos: true,
      isDefault: false,
      isRejectedPhotosFetched: true,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
      isDefault: true,
      isRejectedPhotosFetched: true,
    },
    gender: 'Male',
  },
};

const getChangeEvent = value => ({
  target: {
    value,
  },
});

const getLocation = hash => ({
  hash,
});

const factory = { allData, profileWithPhotos, profileWithProfilePhoto, getLocation, getChangeEvent };

it('should export profiles and props', () => {
  expect(factory.allData).not.toBeFalsy();
});

export default factory;
