const profile = {
  account: {
    status: 'Active',
    last_login_date: 20170801195814,
    profile_created: 20130827010312,
    profile_activated: 20130827011406,
    posted_by: 'Parent / Guardian',
    membership: ['Gold Plus  Member', 'Bold Listing'],
    hide_till: 0,
    screened: 'Y',
    hidden: 'N',
    astro_profile: 'Y',
    memberlogin: 'rSH58638172',
  },
  basic: {
    username: 'SH58638172',
    display_name: 'Ankit G',
    first_name: 'Ankit',
    last_name: 'Garg',
    gender: 'Male',
    age: '30',
    marital_status: 'Never Married',
    date_of_birth: 19860925,
  },
  trait: {
    personal_values: 'Moderate',
    about_me: "Hello and welcome to my son's profile!\r\n\r\nAnkit is an affectionate and fun-loving gentleman nurtured with good values. ",
    personality: [],
  },
  health_info: {
    special_cases: 'None',
    blood_group: '',
    ailments: 'No Health Problems',
  },
  appearance: {
    complexion: 'Fair',
    built: 'Average',
    height: 66,
    weight: '70|kgs',
  },
  lifestyle: {
    diet: 'Veg',
    drink: 'No',
    smoke: 'No',
  },
  doctrine: {
    religion: 'Hindu',
    caste: 'Agarwal',
    sub_caste: 'Bisa agarwal',
    mother_tongue: 'Hindi',
    gotra: 'Garg',
    amritdhari: '',
    dastar: '',
    fasting: '',
    keshdhari: '',
    muslim_from_birth: '',
    namaaz: '',
    religious_values: '',
    zakaat: '',
    caste_no_bar: '',
  },
  location: {
    country: 'India',
    state: 'Delhi-NCR',
    district: 'Delhi',
    residency_status: 'Citizen',
    zip_code: '201012',
    country_code: '',
    city_google: '',
    living_since: '',
    city: 'Delhi',
    locality: '',
  },
  education: {
    education: 'Bachelors - Engineering/ Technology',
    education_stream: 'Engineering/ Technology',
    college_university: '',
    college_1: 'Punjab technical University',
    valid_college_1: 'No',
    college_2: '',
    valid_college_2: 'No',
  },
  profession: {
    occupation: 'Software Consultant',
    industry: 'IT & Software Engineering',
    working_with: 'Private Company',
    income_old: 'Rs 10 lakhs to 15 lakhs',
    income: 'INR 10 Lakh to 15 Lakh',
    income_currency: 'INR',
    linkedin_employerid: 0,
    employer: 'null',
    valid_employer: 'No',
    income_hidden: '',
  },
  family: {
    children: 'No',
    cultural_values: 'Moderate',
    about: 'null',
    father_profession: 'Retired',
    mother_profession: 'Homemaker',
    brothers: '1',
    brothers_married: '1',
    sisters: '0',
    sisters_married: '0',
    affluence: 'Upper Middle Class',
    no_of_kids: '0',
    type: 'Joint',
    located: 'NCR',
    father_employer: 'State Bank of India',
    father_designation: 'Manager',
    about_father: 'His father retired from State Bank of India as Manager.',
    mother_employer: '',
    mother_designation: '',
    about_mother: '',
    family_income: '',
  },
  origin: {
    grewup_in: ['India'],
    native_place: 'Kasganj',
    ethnicity: 'India',
  },
  interests_and_more: {
    hobbies: ['null'],
    interests: ['null'],
    cuisine: ['North Indian', 'South Indian'],
    music: ['Enjoy most forms of music'],
    movies: ['Love all kinds of movies'],
    reads: ['Magazines & Newspapers'],
    sports: ['Badminton'],
    dress_style: ['Business casual - semi-formal office wear', 'Casual - usually in jeans and T-shirts'],
    can_speak: ['English', 'Hindi'],
  },
  photo_details: {
    count: 1,
    photos: [
      {
        domain_name: 'https://img1.shaadi.com',
        small: '/2017/01/22/rSH58638172-674abe.jpg',
        medium: '/2017/01/22/rSH58638172-38aa77.jpg',
        semilarge: '/2017/01/22/rSH58638172-a98987.jpg',
        status: 'Y',
        photo_order: 0,
        profile_photo: true,
        small_nb: '/2017/01/22/rSH58638172-674abe.jpg',
        domain_name_nb: 'https://img1.shaadi.com',
        medium_nb: '/2017/01/22/rSH58638172-38aa77.jpg',
        semilarge_nb: '/2017/01/22/rSH58638172-a98987.jpg',
      },
    ],
    status: 'show_photo',
  },
  connect: {
    filtered: 'N',
    connect_status: 'not_contacted',
  },
  other: {
    se: '1ef4b5654f70c0f6e7bb9f4426748584',
    show_history: 'N',
    match_tag: 'preferred',
  },
  astro: {
    details: {
      city_of_birth: 'Delhi',
      state_of_birth: 'NCT',
      country_of_birth: 'India',
      time_of_birth: '10:45:00',
      time_quality: 'accurate',
      astro_status: 'Astro Ready',
      prefer_horoscope_matching: 'Yes',
      system_manglik: 'Slightly Manglik',
      suddha_jadhagam: '',
      sarpa_dosham: 'No',
      kaalsarpa_dosham: 'No',
      rahu_dosham: 'No',
      ketu_dosham: 'No',
      kalathra_dosham: 'No',
      birth_star_nakshatra: 'Mrigasira',
      moon_sign: 'Vrishabh (Taurus)',
      charan: 2,
      language_format: 'ENG',
      horoscope_style: 'North Indian',
      manual_horo_url: 'None',
      manual_horo_status: 'None',
      ss: '6',
      dc: '10-03-2025,10-03-2044,10-03-2061,10-03-2068',
      tp: '6',
      pts_l: '0',
      pts_s: '0',
      pts_c: '0',
      pos_l: '2',
      pos_s: '3',
      pos_c: '8',
      ras_s: '7',
      ras_k: '9',
      ras_l: '8',
      manglik: 'No',
    },
    horoscope_status: 'show_generated',
    status: 'show_generated',
  },
  intents: {
    shortlisted: {},
    ignored: {
      record_date: 20170801200536,
    },
  },
  contact: {
    profileid: 'rSH58638172',
    convenient_time: '',
    from_time_hours: 9,
    from_time_min: 0,
    last_update_date: 20140107112609,
    mobile_country: 'India',
    mobile_verified: 'Y',
    name: 'R P Garg',
    relation: 'Parent',
    telephone_country: 'India',
    telephone_verified: 'N',
    timezone: '',
    to_time_hours: 21,
    to_time_min: 0,
    contact_details_status: 'show_all',
    contact_details_title_status: 'show_all',
  },
  relationship_actions: {
    se: '1ef4b5654f70c0f6e7bb9f4426748584',
    contacts_status: 'not_contacted',
    contactstatus_title: 'Show All',
    call_sms: 'CALL / SMS',
    can_cancel: false,
    can_send_reminder: true,
    no_action: false,
    maybe_action: false,
    can_chat: true,
  },
  chat_details: {
    chat_status: 'Online on Android App',
    lastonlinestatus: 'Online now',
    lastonlinestatus_time: 1501583451,
  },
  score: {
    astro: {
      rankdata: 24,
      maxscore: 36,
    },
    partner: {
      age: true,
      marital_status: true,
      children: true,
      height: true,
      body_type: true,
      complexion: true,
      country: true,
      residency_status: true,
      caste: false,
      education: true,
      working_with: true,
      industry: true,
      occupation: true,
      family_values: true,
      smoke: true,
      drink: true,
      diet: true,
      manglik: true,
      gotra: true,
      income: true,
      ethnicity: true,
      mother_tongue: false,
      special_cases: true,
      hiv: true,
      state: false,
      district: true,
      grewup_in: true,
      relationship: true,
    },
  },
  derived_text: {
    family_details: {
      details:
        'Ours is an upper middle class family, originally from Kasganj, with moderate values. His father is retired and his mother is a homemaker. He has 1 brother (married).',
    },
    matching_data: {
      diet: 'You both are vegetarians',
      sun_sign_group: 'He is a Libran - you both share the "Air" zodiac element',
    },
  },
};

const discoverGpsType = ['broader', 'reverse', 'discovery_recent_visitors', 'discovery_premium'];
const intentGpsType = ['shortlisted', 'blocked', 'ignored', 'full-profile'];
const searchResult = { uid: 'abc', data: {}, discoverSearchType: discoverGpsType };
const seacrhParam = {
  code: 200,
  data: [],
  paginator: { key: '', page: '1', limit_per_page: 20, total_count: 1 },
  request_count: 1,
  responseType: 'viewed',
  search: { count: 1 },
};
discoverGpsType.forEach(type => {
  searchResult.data[type] = { ...seacrhParam, data: [profile], search_type: type };
});
intentGpsType.forEach(type => {
  searchResult.data[type] = { ...seacrhParam, data: { profile }, search_type: type };
});
const factory = { searchResult };
it('should export seacrhResult', () => {
  expect(Object.keys(factory).length).toEqual(1);
});

export default factory;
