export default {
  FormNames: {
    1: 'basic',
    2: 'biodata',
    3: 'lifestyle',
    4: 'description',
  },
  step1FormFieldNamesValidate: [
    'zip',
    'state',
    'city',
    'district',
    'livingSince',
    'residencyStatus',
    'grewUpIn',
    'ethnicity',
    'regionalSite',
    'maritalStatus',
    'haveChildren',
    'noOfChildren',
    'caste',
    'subCaste',
    'subCasteOther',
    'gotra',
    'gotraOther',
    'nakshatra',
    'rashi',
    'dosham',
    'doshamTypes',
    'regionalSite',
  ],
  step2FormFieldNamesValidate: ['educationLevel', 'educationField', 'workingWith', 'workingAs', 'income'],
  step3FormFieldNamesValidate: ['smokeHabbit', 'drinkHabbit', 'height'],
  step4FormFieldNamesValidate: ['description', 'countryCode', 'mobileNumber'],
};
