/* eslint-disable camelcase, max-len */
const profile0Response = {
  profile: {
    code: 200,
    request_count: 0,
    data: {
      rSH58638172: {
        account: {
          status: 'Active',
          last_login_date: 20170801195814,
          profile_created: 20130827010312,
          profile_activated: 20130827011406,
          posted_by: 'Parent / Guardian',
          membership: ['Gold Plus  Member', 'Bold Listing'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'rSH58638172',
        },
        basic: {
          username: 'SH58638172',
          display_name: 'Ankit G',
          first_name: 'Ankit',
          last_name: 'Garg',
          gender: 'Male',
          age: '30',
          marital_status: 'Never Married',
          date_of_birth: 19860925,
        },
        trait: {
          personal_values: 'Moderate',
          about_me:
            "Hello and welcome to my son's profile!\r\n\r\nAnkit is an affectionate and fun-loving gentleman nurtured with good values. Hardworking and career driven, he has a zeal for achieving success in every frame of life. Family comes first for him and he leaves no stone unturned to keep us happy. We are astounded by his ability to maintain a perfect balance between personal and professional life. In leisure, he enjoys travelling and listening to music.\r\n\r\nHe completed B. Tech. in Computer Science and Engineering from I.E.T Bhaddal. He is employed as an SAP Consultant with a U.S. based MNC.\r\n\r\nOurs is a close-knit family hailing from Kasganj, Uttar Pradesh, wherein I retired as a Manager from the State Bank of India and my wife is a wonderful homemaker. My other son is a Vice President at Kotak Mahindra Bank and my daughter-in-law is an Operations Manager of Taj Mansingh Hotel. It gives me great pleasure to see my children flourish in their careers while leading fulfilling personal lives.\r\n\r\nA bride who understands the essence of marriage and will bind our family together would be an ideal match. We are a progressive family and prefer to have a working professional as Ankit's life partner.\r\n\r\nThanks for your interest and if you wish to take things forward, please feel free to drop a message.",
          personality: [],
        },
        health_info: {
          special_cases: 'None',
          blood_group: '',
          ailments: 'No Health Problems',
        },
        appearance: {
          complexion: 'Fair',
          built: 'Average',
          height: 66,
          weight: '70|kgs',
        },
        lifestyle: {
          diet: 'Veg',
          drink: 'No',
          smoke: 'No',
        },
        doctrine: {
          religion: 'Hindu',
          caste: 'Agarwal',
          sub_caste: 'Bisa agarwal',
          mother_tongue: 'Hindi',
          gotra: 'Garg',
          amritdhari: '',
          dastar: '',
          fasting: '',
          keshdhari: '',
          muslim_from_birth: '',
          namaaz: '',
          religious_values: '',
          zakaat: '',
          caste_no_bar: '',
        },
        location: {
          country: 'India',
          state: 'Delhi-NCR',
          district: 'Delhi',
          residency_status: 'Citizen',
          zip_code: '201012',
          country_code: '',
          city_google: '',
          living_since: '',
          city: 'Delhi',
          locality: '',
        },
        education: {
          education: 'Bachelors - Engineering/ Technology',
          education_stream: 'Engineering/ Technology',
          college_university: '',
          college_1: 'Punjab technical University',
          valid_college_1: 'No',
          college_2: '',
          valid_college_2: 'No',
        },
        profession: {
          occupation: 'Software Consultant',
          industry: 'IT & Software Engineering',
          working_with: 'Private Company',
          income_old: 'Rs 10 lakhs to 15 lakhs',
          income: 'INR 10 Lakh to 15 Lakh',
          income_currency: 'INR',
          linkedin_employerid: 0,
          employer: 'null',
          valid_employer: 'No',
          income_hidden: '',
        },
        family: {
          children: 'No',
          cultural_values: 'Moderate',
          about: 'null',
          father_profession: 'Retired',
          mother_profession: 'Homemaker',
          brothers: '1',
          brothers_married: '1',
          sisters: '0',
          sisters_married: '0',
          affluence: 'Upper Middle Class',
          no_of_kids: '0',
          type: 'Joint',
          located: 'NCR',
          father_employer: 'State Bank of India',
          father_designation: 'Manager',
          about_father: 'His father retired from State Bank of India as Manager.',
          mother_employer: '',
          mother_designation: '',
          about_mother: '',
          family_income: '',
        },
        origin: {
          grewup_in: ['India'],
          native_place: 'Kasganj',
          ethnicity: 'India',
        },
        interests_and_more: {
          hobbies: ['null'],
          interests: ['null'],
          cuisine: ['North Indian', 'South Indian'],
          music: ['Enjoy most forms of music'],
          movies: ['Love all kinds of movies'],
          reads: ['Magazines & Newspapers'],
          sports: ['Badminton'],
          dress_style: ['Business casual - semi-formal office wear', 'Casual - usually in jeans and T-shirts'],
          can_speak: ['English', 'Hindi'],
        },
        photo_details: {
          count: 1,
          photos: [
            {
              domain_name: 'https://img1.shaadi.com',
              small: '/2017/01/22/rSH58638172-674abe.jpg',
              medium: '/2017/01/22/rSH58638172-38aa77.jpg',
              semilarge: '/2017/01/22/rSH58638172-a98987.jpg',
              status: 'Y',
              photo_order: 0,
              profile_photo: true,
              small_nb: '/2017/01/22/rSH58638172-674abe.jpg',
              domain_name_nb: 'https://img1.shaadi.com',
              medium_nb: '/2017/01/22/rSH58638172-38aa77.jpg',
              semilarge_nb: '/2017/01/22/rSH58638172-a98987.jpg',
            },
          ],
          status: 'show_photo',
        },
        connect: {
          filtered: 'N',
          connect_status: 'not_contacted',
        },
        other: {
          se: '1ef4b5654f70c0f6e7bb9f4426748584',
          show_history: 'N',
          match_tag: 'preferred',
        },
        astro: {
          details: {
            city_of_birth: 'Delhi',
            state_of_birth: 'NCT',
            country_of_birth: 'India',
            time_of_birth: '10:45:00',
            time_quality: 'accurate',
            astro_status: 'Astro Ready',
            prefer_horoscope_matching: 'Yes',
            system_manglik: 'Slightly Manglik',
            suddha_jadhagam: '',
            sarpa_dosham: 'No',
            kaalsarpa_dosham: 'No',
            rahu_dosham: 'No',
            ketu_dosham: 'No',
            kalathra_dosham: 'No',
            birth_star_nakshatra: 'Mrigasira',
            moon_sign: 'Vrishabh (Taurus)',
            charan: 2,
            language_format: 'ENG',
            horoscope_style: 'North Indian',
            manual_horo_url: 'None',
            manual_horo_status: 'None',
            ss: '6',
            dc: '10-03-2025,10-03-2044,10-03-2061,10-03-2068',
            tp: '6',
            pts_l: '0',
            pts_s: '0',
            pts_c: '0',
            pos_l: '2',
            pos_s: '3',
            pos_c: '8',
            ras_s: '7',
            ras_k: '9',
            ras_l: '8',
            manglik: 'No',
          },
          horoscope_status: 'show_generated',
          status: 'show_generated',
        },
        intents: {
          shortlisted: {},
          ignored: {
            record_date: 20170801200536,
          },
        },
        contact: {
          profileid: 'rSH58638172',
          convenient_time: '',
          from_time_hours: 9,
          from_time_min: 0,
          last_update_date: 20140107112609,
          mobile_country: 'India',
          mobile_verified: 'Y',
          name: 'R P Garg',
          relation: 'Parent',
          telephone_country: 'India',
          telephone_verified: 'N',
          timezone: '',
          to_time_hours: 21,
          to_time_min: 0,
          contact_details_status: 'show_all',
          contact_details_title_status: 'show_all',
        },
        relationship_actions: {
          se: '1ef4b5654f70c0f6e7bb9f4426748584',
          contacts_status: 'not_contacted',
          contactstatus_title: 'Show All',
          call_sms: 'CALL / SMS',
          can_cancel: false,
          can_send_reminder: true,
          no_action: false,
          maybe_action: false,
          can_chat: true,
        },
        chat_details: {
          chat_status: 'Online on Android App',
          lastonlinestatus: 'Online now',
          lastonlinestatus_time: 1501583451,
        },
        score: {
          astro: {
            rankdata: 24,
            maxscore: 36,
          },
          partner: {
            age: true,
            marital_status: true,
            children: true,
            height: true,
            body_type: true,
            complexion: true,
            country: true,
            residency_status: true,
            caste: false,
            education: true,
            working_with: true,
            industry: true,
            occupation: true,
            family_values: true,
            smoke: true,
            drink: true,
            diet: true,
            manglik: true,
            gotra: true,
            income: true,
            ethnicity: true,
            mother_tongue: false,
            special_cases: true,
            hiv: true,
            state: false,
            district: true,
            grewup_in: true,
            relationship: true,
          },
        },
        derived_text: {
          family_details: {
            details:
              'Ours is an upper middle class family, originally from Kasganj, with moderate values. His father is retired and his mother is a homemaker. He has 1 brother (married).',
          },
          matching_data: {
            diet: 'You both are vegetarians',
            sun_sign_group: 'He is a Libran - you both share the "Air" zodiac element',
          },
        },
      },
    },
  },
  photos: {
    code: 200,
    request_count: 0,
    data: {
      rSH58638172: {
        account: {
          status: 'Active',
          last_login_date: 20170801195814,
          profile_created: 20130827010312,
          profile_activated: 20130827011406,
          posted_by: 'Parent / Guardian',
          membership: ['Gold Plus  Member', 'Bold Listing'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'rSH58638172',
        },
        photo_details: {
          count: 1,
          photos: [],
          status: 'show_photo',
        },
        connect: {
          filtered: 'N',
          connect_status: 'not_contacted',
        },
        other: {
          se: '1ef4b5654f70c0f6e7bb9f4426748584',
          show_history: 'N',
        },
      },
    },
  },
  trustBadge: {
    code: 200,
    request_count: 0,
    data: [
      {
        memberlogin: 'rSH58638172',
        contact: {
          mobile: 'Y',
          email: 'N',
        },
        social: {
          facebook: 'N',
          facebook_badge_by: null,
          linkedin: 'N',
        },
        id_proof: {
          passport: 'N',
          driving_license: 'N',
          others: [],
        },
      },
    ],
  },
  ignoredCount: {
    code: 200,
    request_count: 0,
    data: {
      count: 1,
      intents: {
        rSH58638172: {
          record_date: 20170801200536,
        },
      },
    },
  },
  preferences: {
    code: 200,
    request_count: 0,
    data: {
      rSH58638172: {
        partner: {
          memberlogin: 'rSH58638172',
          photograph: 'null',
          relationship: 'null',
          gender: 'Female',
          age_from: 24,
          age_to: 30,
          marital_status: ['Never Married'],
          children: 'null',
          height_from: 59,
          height_to: 65,
          body_type: 'null',
          complexion: 'null',
          country: ['India'],
          state: ['Delhi-NCR'],
          district: 'null',
          residency_status: 'null',
          community: ['Hindu'],
          caste: [
            {
              religion: 'Hindu',
              caste: 'Agarwal',
            },
            {
              religion: 'Hindu',
              caste: 'Baniya',
            },
          ],
          caste_no_bar: 'null',
          sub_caste: 'null',
          education: 'null',
          working_with: 'null',
          industry: 'null',
          occupation: 'null',
          family_values: 'null',
          personal_values: 'null',
          smoke: 'null',
          drink: 'null',
          diet: ['Veg'],
          manglik: ['No'],
          income: 'null',
          mother_tongue: ['Hindi'],
          special_cases: 'No',
          disability: 'No',
          hiv: 'No',
          astro_profile: 'null',
          more_partner_profile: 'N',
          grewup_in: 'null',
          country_of_birth: 'null',
          record_date: 20130827010313,
          ethnicity: 'null',
          gotra: 'null',
          updated_date: 0,
          basecurrency: 'null',
          willing_to_relocate: 'null',
          income_range: 'null',
          include_notspecified_income: 'N',
          smart_income_search: 'N',
        },
        contact_filter: {
          memberlogin: 'rSH58638172',
          relationship: 'null',
          age_from: 21,
          age_to: 30,
          marital_status: ['Never Married'],
          children: 'null',
          height_from: 0,
          height_to: 0,
          body_type: 'null',
          complexion: 'null',
          country: 'null',
          state: 'null',
          district: 'null',
          residency_status: 'null',
          community: ['Hindu'],
          caste: [
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
          ],
          sub_caste: 'null',
          education: 'null',
          working_with: 'null',
          industry: 'null',
          occupation: 'null',
          family_values: 'null',
          personal_values: 'null',
          smoke: 'null',
          drink: 'null',
          diet: 'null',
          manglik: 'null',
          income: 'null',
          mother_tongue: 'null',
          special_cases: 'No',
          disability: 'No',
          hiv: 'No',
          astro_profile: 'null',
          grewup_in: 'null',
          country_of_birth: 'null',
          updated_date: 20160705225241,
          record_date: 20130827010313,
          basecurrency: 'null',
        },
      },
    },
  },
  profileQueue: {
    code: 200,
    request_count: 0,
    data: [
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195814,
          profile_created: 20130827010312,
          profile_activated: 20130827011406,
          posted_by: 'Parent / Guardian',
          membership: ['Gold Plus  Member', 'Bold Listing'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'rSH58638172',
        },
        connect: {},
        other: {
          se: '1ef4b5654f70c0f6e7bb9f4426748584',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801200020,
          profile_created: 20160330185152,
          profile_activated: 20160330235016,
          posted_by: 'Parent / Guardian',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'USH89425763',
        },
        connect: {},
        other: {
          se: 'cf312f8426648f356abca57687fe2986',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801200007,
          profile_created: 20170728200806,
          profile_activated: 20170728201742,
          posted_by: 'Self',
          membership: ['Free Member', 'Bold Listing'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '0SH41990681',
        },
        connect: {},
        other: {
          se: '428989c06047a115f1e4abe5c142efb7',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195909,
          profile_created: 20160302145235,
          profile_activated: 20160302182440,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'eSH21967199',
        },
        connect: {},
        other: {
          se: '891343dd672d86812a61c57a19474b9c',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195908,
          profile_created: 20160325031003,
          profile_activated: 20160325045411,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'CSH45565610',
        },
        connect: {},
        other: {
          se: 'fb60741d32ea4abeeb721db56d3ab502',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195814,
          profile_created: 20130514094450,
          profile_activated: 20130514100019,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'QSH62966582',
        },
        connect: {},
        other: {
          se: '5a869fcda52fe42c712b3e8188791dfc',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195812,
          profile_created: 20140311095554,
          profile_activated: 20140311095738,
          posted_by: 'Self',
          membership: ['Solitaire Plus  Member', 'Bold Listing'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'kSH84700278',
        },
        connect: {},
        other: {
          se: '0da24925b8b14c15b2a3ad0cd73cb663',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195705,
          profile_created: 20160730233135,
          profile_activated: 20160731020250,
          posted_by: 'Parent / Guardian',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: '5SH50333828',
        },
        connect: {},
        other: {
          se: '547effa1eb700e86effeb00e7faa725c',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195651,
          profile_created: 20140829161502,
          profile_activated: 20140829161514,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'SH18544055',
        },
        connect: {},
        other: {
          se: 'e9446f8266f3da7025d3b8f34d273ef9',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195616,
          profile_created: 20161023193952,
          profile_activated: 20161023205324,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'sSH11992137',
        },
        connect: {},
        other: {
          se: '85c301eb4175cb728ef6ab545d83ee8b',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195612,
          profile_created: 20151129053202,
          profile_activated: 20151129071808,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'KSH12534029',
        },
        connect: {},
        other: {
          se: '9ae14ce944afeb0495da2602f360d638',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195612,
          profile_created: 20120802110602,
          profile_activated: 20120802110936,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'KSH15759017',
        },
        connect: {},
        other: {
          se: '9c2e880500cc2eac34cf3cb0d7f71f34',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195516,
          profile_created: 20140725024258,
          profile_activated: 20140725032449,
          posted_by: 'Parent / Guardian',
          membership: ['was Diamond  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'tSH28485574',
        },
        connect: {},
        other: {
          se: '77a6d66c9190d06d8a1bf8958897dbc7',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195512,
          profile_created: 20160518064246,
          profile_activated: 20160520055752,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'hSH31324909',
        },
        connect: {},
        other: {
          se: '3bea26d1fef34ba4563f76cc2cee92ca',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195512,
          profile_created: 20160809220254,
          profile_activated: 20160810015451,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'hSH34130872',
        },
        connect: {},
        other: {
          se: 'c4fcfb1f6b2ded95d13cd880226eaa92',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195415,
          profile_created: 20170601141229,
          profile_activated: 20170601142955,
          posted_by: 'Self',
          membership: ['Diamond  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'mSH02704365',
        },
        connect: {},
        other: {
          se: 'b3568d2b78c931a112910f56b3806d6a',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195414,
          profile_created: 20170705225947,
          profile_activated: 20170705231307,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'lSH12580717',
        },
        connect: {},
        other: {
          se: 'daae4b91f1203df19ac669930fb6b9f1',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195405,
          profile_created: 20170610212026,
          profile_activated: 20170610214035,
          posted_by: 'Parent / Guardian',
          membership: ['Diamond  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '1SH50768047',
        },
        connect: {},
        other: {
          se: '2509acb4d98893686008e0c9cdf60e61',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195316,
          profile_created: 20120829084034,
          profile_activated: 20120829094734,
          posted_by: 'Self',
          membership: ['was Gold  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'xSH01809655',
        },
        connect: {},
        other: {
          se: '3b886678ee2081b39fcd28a992159557',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170801195312,
          profile_created: 20140612224258,
          profile_activated: 20140612224337,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'NSH99570818',
        },
        connect: {},
        other: {
          se: '45d2abf66bce1ad46004c7bda02a4f7e',
        },
      },
    ],
    search: {
      search_type: 'preferred',
      sort: '-member2_dummy7',
      count: 10324,
    },
  },
};

const EXP_profile0Preferences = {
  items: [
    { desc: '24 to 30', isMatch: true, key: 'preference-age', preferenceKey: 'age', term: 'Age' },
    { desc: '4\' 11"(149cm) to 5\' 5"(165cm)', isMatch: true, key: 'preference-height', preferenceKey: 'height', term: 'Height' },
    {
      desc: 'Never Married',
      isMatch: true,
      key: 'preference-maritalStatus',
      preferenceKey: 'marital_status',
      term: 'Marital Status',
    },
    {
      desc: 'Hindu: Agarwal, Hindu: Baniya',
      isMatch: false,
      key: 'preference-match-2',
      preferenceKey: 'caste',
      term: 'Religion / Community',
    },
    { desc: 'Hindi', isMatch: false, key: 'preference-motherTongue', preferenceKey: 'mother_tongue', term: 'Mother Tongue' },
    { desc: 'No Mangliks', isMatch: true, key: 'preference-manglik', preferenceKey: 'manglik', term: 'Manglik / Chevvai dosham' },
    { desc: 'India', isMatch: true, key: 'preference-country', preferenceKey: 'country', term: 'Country Living in' },
    { desc: 'Delhi-NCR', isMatch: false, key: 'preference-state', preferenceKey: 'state', term: 'State Living in' },
    { desc: 'Veg', isMatch: true, key: 'preference-match-11', preferenceKey: 'diet', term: 'Diet' },
  ],
  matchCount: 6,
};

const profile1Response = {
  profile: {
    code: 200,
    request_count: 0,
    data: {
      dSH74588765: {
        account: {
          status: 'Active',
          last_login_date: 20170817233154,
          profile_created: 20160429070205,
          profile_activated: 20160429075642,
          posted_by: 'Self',
          membership: ['was Gold  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'dSH74588765',
        },
        basic: {
          username: 'SH74588765',
          display_name: 'Ajay P',
          first_name: 'Ajay',
          last_name: 'Pant',
          gender: 'Male',
          age: '30',
          marital_status: 'Divorced',
          date_of_birth: 19861112,
        },
        trait: {
          personal_values: '',
          about_me:
            'I am a Chartered Accountant. Looking for a suitable life partner . Have 1 child from previous marriage which is not staying with me.',
          personality: [],
        },
        health_info: {
          special_cases: 'None',
          blood_group: '',
          ailments: '',
        },
        appearance: {
          complexion: 'Dark',
          built: 'Average',
          height: 67,
          weight: '',
        },
        lifestyle: {
          diet: 'Occasionally Non-Veg',
          drink: 'Occasionally',
          smoke: 'No',
        },
        doctrine: {
          religion: 'Hindu',
          caste: 'Brahmin - Deshastha',
          sub_caste: '-',
          mother_tongue: 'Marathi',
          gotra: '-',
          amritdhari: '',
          dastar: '',
          fasting: '',
          keshdhari: '',
          muslim_from_birth: '',
          namaaz: '',
          religious_values: '',
          zakaat: '',
          caste_no_bar: '',
        },
        location: {
          country: 'India',
          state: 'Maharashtra',
          district: 'Pune',
          residency_status: 'Citizen',
          zip_code: '',
          country_code: '',
          city_google: '',
          living_since: '',
          city: 'Pune',
          locality: '',
        },
        education: {
          education: 'Masters - Commerce',
          education_stream: 'Commerce',
          college_university: '',
          college_1: 'Institute of Chartered Accountants of India',
          valid_college_1: 'Yes',
          college_2: 'null',
          valid_college_2: 'No',
        },
        profession: {
          occupation: 'Finance Professional',
          industry: 'Accounting, Banking & Finance',
          working_with: 'Private Company',
          income_old: 'Rs 10 lakhs to 15 lakhs',
          income: 'INR 10 Lakh to 15 Lakh',
          income_currency: 'INR',
          linkedin_employerid: 0,
          employer: 'null',
          valid_employer: 'No',
          income_hidden: '',
        },
        family: {
          children: 'Yes. Not living together',
          cultural_values: '',
          about: 'null',
          father_profession: 'Business',
          mother_profession: 'Homemaker',
          brothers: '1',
          brothers_married: '0',
          sisters: '0',
          sisters_married: '0',
          affluence: 0,
          no_of_kids: '1',
          type: '',
          located: '',
          father_employer: '',
          father_designation: '',
          about_father: '',
          mother_employer: '',
          mother_designation: '',
          about_mother: '',
          family_income: '',
        },
        origin: {
          grewup_in: ['India'],
          native_place: '',
          ethnicity: 'India',
        },
        interests_and_more: {
          hobbies: ['null'],
          interests: ['null'],
          cuisine: ['null'],
          music: ['null'],
          movies: ['null'],
          reads: ['null'],
          sports: ['null'],
          dress_style: ['null'],
          can_speak: ['null'],
        },
        photo_details: {
          count: 1,
          photos: [
            {
              domain_name: 'https://img1.shaadi.com',
              small: '/2017/07/21/dSH74588765-c38a46-male.jpg',
              medium: '/2017/07/21/dSH74588765-081953-Male.jpg',
              semilarge: '/2017/07/21/dSH74588765-35d9bc-male.jpg',
              status: 'Y',
              photo_order: 0,
              profile_photo: true,
              small_nb: '/2017/07/21/dSH74588765-c38a46-male.jpg',
              domain_name_nb: 'https://img1.shaadi.com',
              medium_nb: '/2017/07/21/dSH74588765-081953-Male.jpg',
              semilarge_nb: '/2017/07/21/dSH74588765-35d9bc-male.jpg',
            },
          ],
          status: 'show_photo',
        },
        connect: {
          filtered: 'N',
          connect_status: 'not_contacted',
        },
        other: {
          se: '7bb48c0dd8bffea1ebb44159d9f96dff',
          show_history: 'N',
          match_tag: '',
        },
        astro: {
          details: {
            city_of_birth: '',
            state_of_birth: '',
            country_of_birth: '',
            time_of_birth: '',
            time_quality: 'accurate',
            astro_status: 'To Get Astro',
            prefer_horoscope_matching: '',
            system_manglik: '',
            suddha_jadhagam: '',
            sarpa_dosham: "Don't Know",
            kaalsarpa_dosham: "Don't Know",
            rahu_dosham: "Don't Know",
            ketu_dosham: "Don't Know",
            kalathra_dosham: "Don't Know",
            birth_star_nakshatra: 0,
            moon_sign: 0,
            charan: 0,
            language_format: '',
            horoscope_style: 'None',
            manual_horo_url: 'None',
            manual_horo_status: 'None',
            ss: '',
            dc: '',
            tp: '',
            pts_l: '',
            pts_s: '',
            pts_c: '',
            pos_l: '',
            pos_s: '',
            pos_c: '',
            ras_s: '',
            ras_k: '',
            ras_l: '',
            manglik: "Don't Know",
          },
          horoscope_status: 'not_available',
          status: 'show_screening',
        },
        intents: {
          shortlisted: {},
          ignored: {},
        },
        contact: {
          profileid: 'dSH74588765',
          convenient_time: '',
          from_time_hours: 0,
          from_time_min: 0,
          last_update_date: 20160429071120,
          mobile_country: 'India',
          mobile_verified: 'Y',
          name: '',
          relation: '',
          telephone_country: 'India',
          telephone_verified: 'N',
          timezone: '',
          to_time_hours: 0,
          to_time_min: 0,
          contact_details_status: 'free_member',
          contact_details_title_status: 'hide_my_number',
        },
        relationship_actions: {
          se: '7bb48c0dd8bffea1ebb44159d9f96dff',
          contacts_status: 'not_contacted',
          contactstatus_title: 'Show All',
          call_sms: 'CALL / SMS',
          can_cancel: false,
          can_send_reminder: true,
          no_action: true,
          maybe_action: true,
          can_chat: false,
        },
        chat_details: {
          chat_status: 'Last online, 19 mins ago',
          lastonlinestatus: 'Online few mins ago',
          lastonlinestatus_time: 1502993513,
        },
        score: {
          astro: {
            rankdata: 0,
            maxscore: 100,
          },
          partner: {
            age: true,
            marital_status: false,
            children: true,
            height: true,
            body_type: true,
            complexion: true,
            country: true,
            residency_status: true,
            caste: true,
            education: true,
            working_with: true,
            industry: true,
            occupation: true,
            family_values: true,
            smoke: true,
            drink: true,
            diet: true,
            manglik: true,
            gotra: true,
            income: true,
            ethnicity: true,
            mother_tongue: false,
            special_cases: true,
            hiv: true,
            state: true,
            district: true,
            grewup_in: true,
            relationship: true,
          },
        },
        derived_text: {
          family_details: {
            details: 'My father runs a business and my mother is a homemaker. I have 1 brother (unmarried).',
          },
          matching_data: {
            occupation: 'You both are Finance Professionals',
            diet_nonveg: 'He enjoys non-vegetarian food too',
            location_state: 'He lives in Maharashtra as well',
          },
        },
      },
    },
  },
  photos: {
    code: 200,
    request_count: 0,
    data: {
      dSH74588765: {
        account: {
          status: 'Active',
          last_login_date: 20170817233154,
          profile_created: 20160429070205,
          profile_activated: 20160429075642,
          posted_by: 'Self',
          membership: ['was Gold  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'dSH74588765',
        },
        photo_details: {
          count: 1,
          photos: [],
          status: 'show_photo',
        },
        connect: {
          filtered: 'N',
          connect_status: 'not_contacted',
        },
        other: {
          se: '7bb48c0dd8bffea1ebb44159d9f96dff',
          show_history: 'N',
        },
      },
    },
  },
  trustBadge: {
    code: 200,
    request_count: 0,
    data: [
      {
        memberlogin: 'dSH74588765',
        contact: {
          mobile: 'Y',
          email: 'N',
        },
        social: {
          facebook: 'N',
          facebook_badge_by: null,
          linkedin: 'N',
        },
        id_proof: {
          passport: 'N',
          driving_license: 'N',
          others: [],
        },
      },
    ],
  },
  ignoredCount: {
    code: 200,
    request_count: 0,
    data: {
      count: 0,
    },
  },
  preferences: {
    code: 200,
    request_count: 0,
    data: {
      dSH74588765: {
        partner: {
          memberlogin: 'dSH74588765',
          photograph: 'null',
          relationship: 'null',
          gender: 'Female',
          age_from: 23,
          age_to: 32,
          marital_status: ['Divorced', 'Awaiting Divorce'],
          children: ['No'],
          height_from: 60,
          height_to: 67,
          body_type: 'null',
          complexion: 'null',
          country: ['India'],
          state: ['Maharashtra'],
          district: 'null',
          residency_status: 'null',
          community: ['Hindu'],
          caste: [
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
          ],
          caste_no_bar: '1',
          sub_caste: 'null',
          education: 'null',
          working_with: 'null',
          industry: 'null',
          occupation: 'null',
          family_values: 'null',
          personal_values: 'null',
          smoke: 'null',
          drink: 'null',
          diet: 'null',
          manglik: 'null',
          income: 'null',
          mother_tongue: ['Marathi'],
          special_cases: 'No',
          disability: 'No',
          hiv: 'No',
          astro_profile: 'null',
          more_partner_profile: 'N',
          grewup_in: 'null',
          country_of_birth: 'null',
          record_date: 20160429070206,
          ethnicity: 'null',
          gotra: 'null',
          updated_date: 0,
          basecurrency: 'null',
          willing_to_relocate: 'null',
          income_range: 'null',
          include_notspecified_income: 'N',
          smart_income_search: 'N',
        },
        contact_filter: {
          memberlogin: 'dSH74588765',
          relationship: 'null',
          age_from: 22,
          age_to: 34,
          marital_status: 'null',
          children: 'null',
          height_from: 0,
          height_to: 0,
          body_type: 'null',
          complexion: 'null',
          country: 'null',
          state: 'null',
          district: 'null',
          residency_status: 'null',
          community: ['Hindu'],
          caste: [
            {
              religion: 'Hindu',
              caste: 'Hindu',
            },
          ],
          sub_caste: 'null',
          education: 'null',
          working_with: 'null',
          industry: 'null',
          occupation: 'null',
          family_values: 'null',
          personal_values: 'null',
          smoke: 'null',
          drink: 'null',
          diet: 'null',
          manglik: 'null',
          income: 'null',
          mother_tongue: 'null',
          special_cases: 'No',
          disability: 'No',
          hiv: 'No',
          astro_profile: 'null',
          grewup_in: 'null',
          country_of_birth: 'null',
          updated_date: 20160429071422,
          record_date: 20160429070206,
          basecurrency: 'null',
        },
      },
    },
  },
  profileQueue: {
    code: 200,
    request_count: 0,
    data: [
      {
        account: {
          status: 'Active',
          last_login_date: 20170817233154,
          profile_created: 20160429070205,
          profile_activated: 20160429075642,
          posted_by: 'Self',
          membership: ['was Gold  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'dSH74588765',
        },
        connect: {},
        other: {
          se: '7bb48c0dd8bffea1ebb44159d9f96dff',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170817210819,
          profile_created: 20170311195303,
          profile_activated: 20170311201038,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'KSH92236244',
        },
        connect: {},
        other: {
          se: 'bed40f896148eb8d01fb00196e6023d8',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170817170212,
          profile_created: 20161210085437,
          profile_activated: 20161210112120,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'mSH80308447',
        },
        connect: {},
        other: {
          se: '614d5b3fca233b45795831d75ca0d8e9',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170816212318,
          profile_created: 20170413130703,
          profile_activated: 20170413132048,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'oSH54007376',
        },
        connect: {},
        other: {
          se: 'd093488d7724fecbf5471619528f8980',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170817035400,
          profile_created: 20160226120832,
          profile_activated: 20160226131525,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'sSH64546148',
        },
        connect: {},
        other: {
          se: 'ec0508d3329eb413a07b6cb5634c18d3',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170816224920,
          profile_created: 20150723071516,
          profile_activated: 20150723080524,
          posted_by: 'Self',
          membership: ['Diamond  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'pSH40991205',
        },
        connect: {},
        other: {
          se: '68761157239d756bc53350a5efb6668b',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170817022503,
          profile_created: 20170720094824,
          profile_activated: 20170720101038,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '8SH29991185',
        },
        connect: {},
        other: {
          se: 'e7f6856a370406bf1f881b240132bd48',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170816071206,
          profile_created: 20170204180302,
          profile_activated: 20170204214420,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'FSH17588534',
        },
        connect: {},
        other: {
          se: '11cae79ba9d3a76bdc6fb5d779412ea7',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170814230446,
          profile_created: 20170814230439,
          profile_activated: 20170814234924,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'zSH10575056',
        },
        connect: {},
        other: {
          se: '1b3ded3e1fbe885fc8a8f6ee5f4f5a87',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170814122105,
          profile_created: 20170110165232,
          profile_activated: 20170110181339,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '2SH53455373',
        },
        connect: {},
        other: {
          se: 'baae5b011367eb7bcf87616fc4d305ad',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170814000104,
          profile_created: 20150506124535,
          profile_activated: 20150506125036,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: '1SH47856756',
        },
        connect: {},
        other: {
          se: 'b46ac831daf1284bc2f0a1ce2ae3259a',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170812221010,
          profile_created: 20170812220956,
          profile_activated: 20170812222222,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'RSH81560903',
        },
        connect: {},
        other: {
          se: '43b32b4bbf4179500f125955f3396128',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170811204638,
          profile_created: 20150406104636,
          profile_activated: 20150406125051,
          posted_by: 'Self',
          membership: ['was Gold  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'dSH04908064',
        },
        connect: {},
        other: {
          se: '6198fc81f025ee7bcbc877b4957e9919',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170809120905,
          profile_created: 20160812223306,
          profile_activated: 20160813012508,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '2SH71533401',
        },
        connect: {},
        other: {
          se: '5707901bd87bad3a4c30db6cb9c3dd57',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170808002355,
          profile_created: 20150705105326,
          profile_activated: 20150705114024,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: '2SH14873218',
        },
        connect: {},
        other: {
          se: '8a2fbf804ee550438bb4420e52a18d47',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170804184810,
          profile_created: 20160127041833,
          profile_activated: 20160127042932,
          posted_by: 'Parent / Guardian',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'Y',
          memberlogin: 'ISH13188095',
        },
        connect: {},
        other: {
          se: '279253e802e2c2bd2566fda206c51346',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170731171619,
          profile_created: 20170324182759,
          profile_activated: 20170324185006,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'NSH26535467',
        },
        connect: {},
        other: {
          se: '550211d8279f69a5b9e87b793e1f80fd',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170731074608,
          profile_created: 20170703123946,
          profile_activated: 20170703152057,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'LSH52044997',
        },
        connect: {},
        other: {
          se: '04f6e46e74e66aa067b552144aae16f2',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170730161219,
          profile_created: 20170514201059,
          profile_activated: 20170514204006,
          posted_by: 'Self',
          membership: ['Free Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: 'mSH18080823',
        },
        connect: {},
        other: {
          se: 'c948921248aa0febf2d88e3f9531d29f',
        },
      },
      {
        account: {
          status: 'Active',
          last_login_date: 20170723091204,
          profile_created: 20170122170146,
          profile_activated: 20170122192219,
          posted_by: 'Self',
          membership: ['was Diamond  Member'],
          hide_till: 0,
          screened: 'Y',
          hidden: 'N',
          astro_profile: 'N',
          memberlogin: '3SH60504134',
        },
        connect: {},
        other: {
          se: 'c34fb10f0b15c16f5b38ac23647779a4',
        },
      },
    ],
    search: {
      search_type: 'most_preferred',
      sort: '-member2_dummy7',
      count: 34,
    },
  },
};

const EXP_profile1Preferences = {
  items: [
    { desc: '23 to 32', isMatch: true, key: 'preference-age', preferenceKey: 'age', term: 'Age' },
    { desc: '5\' 0"(152cm) to 5\' 7"(170cm)', isMatch: true, key: 'preference-height', preferenceKey: 'height', term: 'Height' },
    {
      desc: 'Divorced, Awaiting Divorce',
      isMatch: false,
      key: 'preference-maritalStatus',
      preferenceKey: 'marital_status',
      term: 'Marital Status',
    },
    { desc: 'No', isMatch: true, key: 'preference-children', preferenceKey: 'children', term: 'Children' },
    { desc: 'Hindu', isMatch: true, key: 'preference-match-2', preferenceKey: 'caste', term: 'Religion / Community' },
    { desc: 'Marathi', isMatch: false, key: 'preference-motherTongue', preferenceKey: 'mother_tongue', term: 'Mother Tongue' },
    { desc: 'India', isMatch: true, key: 'preference-country', preferenceKey: 'country', term: 'Country Living in' },
    { desc: 'Maharashtra', isMatch: true, key: 'preference-state', preferenceKey: 'state', term: 'State Living in' },
  ],
  matchCount: 6,
};

const profileArgs = profileResponse => {
  const { profile, trustBadge, ignoredCount, preferences } = profileResponse;
  const userProfile = profile.data;
  const { count, intents } = ignoredCount.data || {};

  return [
    userProfile[Object.keys(userProfile)[0]],
    {
      trustBadge: trustBadge.data[0],
      ignoredCount: count,
      ignoredDate: ((intents || {})[Object.keys(intents || {})[0]] || {}).record_date || 0,
      preferences: preferences.data[Object.keys(preferences.data)[0]],
    },
  ];
};

const factory = { profile0Response, EXP_profile0Preferences, profile1Response, EXP_profile1Preferences, profileArgs };

it('should export profiles and props', () => {
  expect(Object.keys(factory).length).toEqual(5);
});

export default factory;
