const props = {
  data: {
    loading: false,
    disabled: false,
    flash: null,
    flashType: 'default',
    uid: '2SH09841790',
    self: null,
    name: 'Hina Khan',
    hisHer: 'Her',
    heShe: 'She',
    himHer: 'Her',
    message:
      'Msg from Magan M (SH92265540): Hi, I liked the Profile that you have posted on Shaadi.com. Please visit my Profile and respond.',
    preferredName: '-',
    preferredTime: ' - ',
    landline: '-',
    mobile: '+91  9571750717',
    status: 'available',
    eoiFailed: false,
    verificationRequested: false,
    source: 'profile',
    photo: 'https://img1.shaadi.com/2018/02/17/2SH09841790-57893f-female.webp',
    photoBlur: 'https://img1.shaadi.com/2018/02/17/2SH09841790-57893f-female.webp',
    email: 'armankhan24404@gmail.com',
    profileCreatedBy: 'Sibling',
    profileAlbumStatus: 'default',
    thumbnail: '',
    thumbnailBlur: '',
    isMisuseReported: false,
    getSMSLoading: false,
    disabledGetSms: false,
    getSMSText: 'Send to Your Phone',
    getSMSSend: false,
    isLoggerMobileVerified: true,
    membershipTags: 'free',
    loggerMembership: 'Free',
  },
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: true,
    showUpgradeBanner: false,
    canAccessChat: true,
    canInitiateChat: true,
    hasUploadedPhoto: true,
    canConnectWithMessage: true,
    showUpgradeLinks: false,
    canSendPasswordOnConnect: false,
    contactsTotal: 150,
    contactsRemaining: 54,
    isUnderScreening: false,
    isAstroGamified: false,
    gender: 'Male',
    canViewCollegeAndEmployer: true,
    canViewHoroscope: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: false,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: true,
    mobileNumber: '9699259697',
    mobileCountry: 'India',
    wasPaidUser: false,
    expiryDate: '04-Jul-18',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'C',
      },
      offline_otp: {
        bucket: 'B',
      },
      inbox_revamp: {
        bucket: 'A',
      },
    },
    membershipTags: 'diamond',
    offerCode: 'flat15r',
    offer_details: [
      {
        type: 'perc',
        value: 15,
      },
    ],
  },
  connectionFlags: {
    isFree: true,
    isPremium: false,
    membershipLevel: 'Free',
    connectionNote: "Invitation sent on 23 Feb 2018. She hasn't Viewed your Invitation yet.",
    connectionError: false,
    connectionStatus: 'default',
    connectionAction: 'default',
    connectionJustNowText: null,
    contactAction: 'available',
    contactStatus: 'available',
    horoscopeStatus: 'none',
    loading: 'none',
    isDeleted: false,
    isNri: false,
    isWatermarked: true,
    isTwoWayMatch: false,
    isBoldListing: true,
    canUnblock: false,
    unblockMessage: null,
    canUnignore: false,
    canRemind: false,
    canCancelInvite: false,
    isSameGender: false,
    activeStatus: 'default',
    isPreferredMatch: false,
    isConnectLimitExceeded: false,
    showHistory: true,
    membershipTags: 'free',
    isNameLocked: false,
    canCallSendSMS: false,
    canSendEmail: true,
    canSendEmailReminder: false,
    canSendSMS: false,
    canViewPhoneNo: true,
    isPhoneNoViewed: true,
    isSmsAlreadySent: false,
    showChatNow: true,
    showPostOnWall: false,
    isFiltered: false,
    isSkipped: false,
    isProfileViewed: true,
    horoscopeStyle: 'l/undefined/hs/1',
    albumStatus: 'default',
    isIndianDiaspora: true,
    isHoroscopeApplicable: false,
    isFamilyGamified: true,
    isAstroReady: false,
    isHidden: false,
    hiddenReason: null,
    isBothPartyPayUser: false,
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  onModalClose() {},
  doProfileAction() {},
  getSMS() {},
};

const factory = { props };
it('should export props', () => {
  expect(factory.props).not.toBeFalsy();
});

export default factory;
