const data = {
  match: {
    path: '/stop-page/:pageName',
    url: '/stop-page/csat-survey',
    isExact: true,
    params: {
      pageName: 'csat-survey',
    },
  },
  layout: 'desktop',
  history: {
    length: 7,
    action: 'POP',
    location: {
      pathname: '/stop-page/csat-survey',
      search: '',
      hash: '',
    },
  },
  location: {
    pathname: '/stop-page/csat-survey',
    search: '',
    hash: '',
  },
  isLoggedOut: false,
  isNative: false,
  pageName: 'csat-survey',
  user: {
    isLoggedIn: true,
    isLoggedOut: false,
    errusr: '',
    uid: 'vSH88709866',
    gender: '',
    firstName: '',
    lastName: '',
    religion: '',
    motherTongue: '',
    country: '',
    complexion: '',
    built: '',
    height: '',
    weight: '',
    diet: '',
    drink: '',
    smoke: '',
    aboutMe: '',
    hasProfilePhoto: false,
    photos: {},
    heShe: '',
    himHer: '',
    hisHer: '',
    mrMs: '',
    heSheOrYou: '',
    himHerOrYou: '',
    hisHerOrYou: '',
    mrMsOrYou: '',
    heSheOrYour: '',
    himHerOrYour: '',
    hisHerOrYour: '',
    mrMsOrYour: '',
    doOrDoes: '',
    ptnr: 'direct_homepage',
    sessionId: '6BC042D1E12D335D756D56A469B435FB1522823161vSH88709866',
  },
  nextUrl: '/my-shaadi',
  csatSurvey: {
    questions: [
      {
        id: '1',
        display_order: '1',
        type: 'multichoice',
        title: 'What do you like about Shaadi.com?',
        placeHolder: '',
        isRequired: false,
        choices: {
          '20': 'Easy to Use',
          '21': 'Quality of Matches',
          '22': 'Lots of Matches',
        },
      },
      {
        id: '2',
        display_order: '3',
        type: 'textarea',
        title: 'Can you tell us what can we do better?',
        placeHolder: 'Write your feedback here',
        isRequired: false,
        choices: {},
      },
      {
        id: '3',
        display_order: '2',
        type: 'rating',
        title: 'Please rate your Experience with us',
        placeHolder: '',
        isRequired: false,
        choices: {
          '1': 'Hated it',
          '2': 'Disliked it',
          '3': "It's OK",
          '4': 'Liked it',
          '5': 'Loved it',
        },
      },
    ],
    loading: false,
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  documentUpload: {
    uid: null,
    source: null,
    attachments: {},
    redirectToAlbums: false,
    isModalClosed: false,
    isUploadFailed: false,
    uploadingPhotoCount: 0,
  },
  doCsatSurvey() {},
};

export default data;
