const premiumCarouselProps = {
  profiles: {},
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [],
    justNow: false,
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
      premium_carousel: {
        bucket: 'B',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};
const lessThreeItemProps = {
  profiles: {
    'uid-test1': {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'Free',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        uid: 'uid-test1',
        fullPhoto: '',
        name: 'test1',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        eoiClose: false,
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};
const fiveItemProps = {
  profiles: {
    zSH31057997: {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: 'aaaa',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057995: {
      uid: 'uid-test2',
      fullPhoto: '',
      name: 'test2',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057996: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057998: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057999: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',

      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        uid: 'zSH31057997',
        fullPhoto: '1',
        name: 'test1',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057997',
        eoiClose: false,
      },
      {
        uid: 'zSH31057995',
        fullPhoto: '2',
        name: 'test2',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057995',
        eoiClose: false,
      },
      {
        uid: 'zSH31057996',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057996',
        eoiClose: false,
      },
      {
        uid: 'zSH31057998',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057998',
        eoiClose: false,
      },
      {
        uid: 'zSH31057999',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057999',
        eoiClose: false,
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};

const greaterFiveItemProps = {
  profiles: {
    zSH31057997: {
      uid: 'uid-test1',
      fullPhoto: '',
      name: 'test1',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: 'aaaa',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057995: {
      uid: 'uid-test2',
      fullPhoto: '',
      name: 'test2',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057996: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057998: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      tempId: '',
      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057999: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',

      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    zSH31057910: {
      uid: 'uid-test3',
      fullPhoto: '',
      name: 'test3',
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',

      isSameGender: false,
      presence: {
        lastOnlineDetails: 'Online now',
        onlineStatus: 'Online',
        chatIcon: 'web_online',
      },
      base: {
        premiumInfo: [{ key: 'age-height', value: '' }, { key: 'location', value: '' }],
      },
      summary: {
        createdBy: 'Self',
        gridAlbum: [],
        shortBio: '',
        infoMap: [],
        infoMapIndian: [],
        infoMapNri: [],
        infoMapPremiumCarousel: [],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'accepted',
        connectionAction: 'member_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: false,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        isMaskedProfile: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        horoscopeStyle: 'l/HIN/hs/1',
        albumStatus: 'photoRequestSent',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      requests: {
        count: 0,
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
    },
    self: {
      gender: 'Male',
      flags: {
        isPremium: true,
      },
    },
  },
  shortlistItems: [],
  loading: false,
  wwwBaseUrl: '',
  results: {
    results_id: 'test',
    pg_ubt: '',
    permalink: 'test',
    items: [
      {
        uid: 'zSH31057997',
        fullPhoto: '1',
        name: 'test1',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057997',
        eoiClose: false,
      },
      {
        uid: 'zSH31057995',
        fullPhoto: '2',
        name: 'test2',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057995',
      },
      {
        uid: 'zSH31057996',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057996',
      },
      {
        uid: 'zSH31057998',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057998',
      },
      {
        uid: 'zSH31057999',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057999',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
      {
        uid: 'zSH31057910',
        fullPhoto: '3',
        name: 'test3',
        justNow: false,
        photoLoading: false,
        eoiLoadingStyle: 'none',
        tempId: 'zSH31057910',
      },
    ],
    evt: '',
    evt_ref: '',
    query: {},
    tooltip: {
      body: [],
      loading: false,
      position: 'none',
    },
    goPremiumRef: '',
  },
  settings: {
    canAccessChat: true,
    canConnectWithMessage: false,
    canInitiateChat: false,
    canSendPasswordOnConnect: false,
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    contactsRemaining: null,
    contactsTotal: null,
    defaultSearchFormat: 'list',
    experiments: {
      premium_tag: {
        bucket: 'C',
      },
    },
    expiryDate: '',
    gender: 'Female',
    hasUploadedPhoto: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isAstroGamified: true,
    isBothPartyPayUser: false,
    isFamilyGamified: true,
    isHidden: false,
    isIndianDiaspora: true,
    isMobileVerified: false,
    isNri: false,
    isPaidUser: false,
    isUnderScreening: false,
    membershipTags: 'free',
    mobileNumber: '9046546465',
    showUpgradeBanner: true,
    showUpgradeLinks: true,
    wasPaidUser: false,
  },
};

const factory = {
  premiumCarouselProps,
  lessThreeItemProps,
  fiveItemProps,
  greaterFiveItemProps,
};
it('should export premiumCarouselProps', () => {
  expect(factory.premiumCarouselProps).not.toBeFalsy();
  expect(factory.lessThreeItemProps).not.toBeFalsy();
  expect(factory.fiveItemProps).not.toBeFalsy();
  expect(factory.greaterFiveItemProps).not.toBeFalsy();
});
export default factory;
