const allData = {
  queue: [
    {
      se: 'd90c171deb2fc2a0a2e1bda07b7db74a',
      uid: 'hSH62872162',
      name: 'Sikander Singh Sekhon',
      slug: 'hSH62872162',
      thumbnail: 'https://img1.shaadi.com//2017/11/18/hSH62872162-e8c391-male.jpg',
      photo: 'https://img1.shaadi.com//2017/11/18/hSH62872162-8e8cbe-male.jpg',
      fullPhoto: 'https://img1.shaadi.com//2017/11/18/hSH62872162-cbd4c8-male.jpg',
      thumbnailBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-e8c391-male.jpg',
      photoBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-8e8cbe-male.jpg',
      fullPhotoBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-cbd4c8-male.jpg',
      userHandle: 'SH62872162',
      gender: 'Male',
      marital_status: 'Never Married',
      connectMessages: [],
      contact: {},
      horoscopeScore: {},
      flags: {
        membershipLevel: 'PremiumPlus',
        membershipTags: 'diamond_plus',
        isBoldListing: true,
        isDeleted: false,
        connectionStatus: 'theyAccepted',
        connectionAction: 'profile_accepted',
        connectionNote: null,
        contactStatus: null,
        contactAction: null,
        horoscopeStatus: null,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isWatermarked: true,
        isTwoWayMatch: false,
        activeStatus: 'default',
        isNri: true,
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: true,
        isAstroReady: true,
        isSameGender: false,
        canCancelInvite: true,
        canRemind: false,
        canUnblock: false,
        isHidden: false,
        isBothPartyPayUser: false,
        isNameLocked: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
      },
      base: {
        infoMap: [
          { key: 'info-0', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'info-1', label: 'Religion/Community', value: 'Sikh, Jat' },
          { key: 'info-2', label: 'Mother Tounge', value: 'Punjabi' },
          { key: 'info-3', label: 'Profession', value: 'Civil Engineer' },
          { key: 'info-4', label: 'Location', value: 'Ealing, United Kingdom' },
        ],
        infoList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'profession', value: 'Civil Engineer' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
          { key: 'grew up in', value: 'Grew up in India' },
        ],
        miniNriList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'grew up in', value: 'Grew up in India' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
        ],
        miniList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'religion-caste', value: 'Jat' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
        ],
        detailList: [
          { key: 'age-height', value: '26, 5\' 11"' },
          { key: 'religion-caste', value: 'Sikh, Jat' },
          { key: 'profession', value: 'Civil Engineer' },
          { key: 'location', value: 'Ealing, United Kingdom' },
        ],
        premiumInfo: [{ key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' }, { key: 'location', value: 'Ealing, United Kingdom' }],
      },
      presence: {
        onlineStatus: 'away',
        onlineAt: 1516096214000,
        device: 'mobile_native-iphone',
        platform: 'mobile',
        lastOnline: 'Online on iPhone App',
        lastOnlineDetails: 'Online now',
        onlineStatusDetails: 'Away',
      },
      summary: {
        shortBio:
          "Hello, am glad you chose to visit my profile.\r\nI have completed my Bachelors.I value honesty, integrity and simplicity a lot.I don't expect perfection, would just like to find someone 'perfect' for me.",
        createdBy: 'Self',
        profileCreatedBy: 'Self',
        shortlistCount: -1,
        infoMap: [
          { key: 'age_height', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'religion', label: 'Religion', value: 'Sikh' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'community', label: 'Community', value: 'Jat' },
          { key: 'location', label: 'Location', value: 'Ealing, United Kingdom' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapNonIndian: [
          { key: 'age_height', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'religion', label: 'Religion', value: 'Sikh' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'location_nri_info', label: 'Location', value: 'Ealing,Greater London / Middlesex, United Kingdom' },
          { key: 'info-6', label: 'Grew up in', value: 'India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapIndian: [
          { key: 'age_height_list', label: 'Age / Height', value: '26 yrs, 5\' 11"' },
          { key: 'marital_status', label: 'Marital Status', value: 'Never Married' },
          { key: 'religion_caste_list', label: 'Religion', value: 'Sikh, Jat' },
          { key: 'location', label: 'Location', value: 'Ealing, United Kingdom' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '26 yrs, 5\' 11"' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Sikh, Punjabi' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Ealing,Greater London / Middlesex, United Kingdom' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
      },
      detailed: {
        createdBy: 'Self',
        shortlistCount: 0,
        infoMap: [
          { key: 'info-0', icon: 'height_sunsign', value: '26 yrs, 5\' 11", Taurus' },
          { key: 'info-1', icon: 'marital_status', value: 'Never Married ' },
          { key: 'info-2', icon: 'profile_religion', value: 'Sikh, Punjabi' },
          { key: 'info-3', icon: 'profile_community', value: 'Jat' },
          { key: 'info-5', icon: 'profile_profession', value: 'Civil Engineer' },
          { key: 'info-6', icon: 'profile_living_in', value: 'Lives in Ealing, United Kingdom' },
          { key: 'info-7', icon: 'profile_born_detail', value: 'Grew up in India' },
        ],
        about:
          "Hello, am glad you chose to visit my profile.\r\nI have completed my Bachelors.I value honesty, integrity and simplicity a lot.I don't expect perfection, would just like to find someone 'perfect' for me.",
        interests: {},
        lifestyle: { diet: 'Veg', drink: 'No', smoke: 'No', complexion: 'Very Fair', body_built: 'Average' },
        background: [
          { key: 'background-item-0', icon: 'profile_religion', desc: 'Sikh, Punjabi', title: 'Religion' },
          { key: 'background-item-1', icon: 'profile_community', desc: 'Jat', title: 'Community' },
          {
            key: 'background-item-4',
            icon: 'profile_living_in',
            desc: 'Lives in Ealing, Greater London / Middlesex, United Kingdom  (Student Visa)',
          },
          { key: 'background-item-5', icon: 'born_brought_up', desc: 'Grew up in India, India ethnic origin' },
        ],
        education: {
          items: [
            { key: 'education-item-0', icon: 'edu_qualification', desc: 'Bachelors degree in Arts' },
            { key: 'education-item-1', icon: 'profession', desc: 'Civil Engineer - own business/self employed' },
            { key: 'education-item-5', icon: 'income', desc: 'Earns GBP 30K to 40K annually' },
          ],
          hasCollegeOrEmployer: '',
        },
        commonInterests: ['You both grew up in India', 'He has a Bachelors degree in Arts too', 'He is a Taurus as well'],
        horoscope: { is_gamified: false },
        family: { desc: "I don't have any siblings." },
      },
      isAstroStatusError: false,
      tempId: '',
      fullName: 'Sikander singh Sekhon',
      firstName: 'Sikander singh',
      lastName: 'Sekhon',
      location: 'Ealing, United Kingdom',
      request: {},
      recommendation: { memberlogin: 'hSH62872162', action: 'yes', action_date: 20180116123504 },
    },
  ],
  profiles: {
    hSH62872162: {
      base: {
        infoMap: [
          { key: 'info-0', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'info-1', label: 'Religion/Community', value: 'Sikh, Jat' },
          { key: 'info-2', label: 'Mother Tounge', value: 'Punjabi' },
          { key: 'info-3', label: 'Profession', value: 'Civil Engineer' },
          { key: 'info-4', label: 'Location', value: 'Ealing, United Kingdom' },
        ],
        infoList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'profession', value: 'Civil Engineer' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
          { key: 'grew up in', value: 'Grew up in India' },
        ],
        detailList: [
          { key: 'age-height', value: '26, 5\' 11"' },
          { key: 'religion-caste', value: 'Sikh, Jat' },
          { key: 'profession', value: 'Civil Engineer' },
          { key: 'location', value: 'Ealing, United Kingdom' },
        ],
        premiumInfo: [{ key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' }, { key: 'location', value: 'Ealing, United Kingdom' }],
        miniList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'religion-caste', value: 'Jat' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
        ],
        miniNriList: [
          { key: 'age-height', value: '26 yrs, 5\' 11", Sikh, Punjabi' },
          { key: 'grew up in', value: 'Grew up in India' },
          { key: 'location', value: 'Lives in Ealing, United Kingdom' },
        ],
      },
      flags: {
        isFree: false,
        isPremium: true,
        membershipLevel: 'PremiumPlus',
        connectionNote: null,
        connectionError: false,
        connectionStatus: 'theyAccepted',
        connectionAction: 'profile_accepted',
        connectionJustNowText: null,
        contactAction: 'available',
        contactStatus: 'available',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: true,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: true,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: true,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'diamond_plus',
        isNameLocked: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: true,
        isAstroReady: true,
        isHidden: false,
        isBothPartyPayUser: false,
      },
      presence: {
        onlineStatus: 'away',
        onlineStatusDetails: 'Away',
        onlineAt: 1516096214000,
        device: 'mobile_native-iphone',
        platform: 'mobile',
        lastOnline: 'Online on iPhone App',
        lastOnlineDetails: 'Online now',
        ready: false,
      },
      summary: {
        infoMap: [
          { key: 'age_height', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'religion', label: 'Religion', value: 'Sikh' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'community', label: 'Community', value: 'Jat' },
          { key: 'location', label: 'Location', value: 'Ealing, United Kingdom' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapNonIndian: [
          { key: 'age_height', label: 'Age / Height', value: '26, 5\' 11"' },
          { key: 'religion', label: 'Religion', value: 'Sikh' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'location_nri_info', label: 'Location', value: 'Ealing,Greater London / Middlesex, United Kingdom' },
          { key: 'info-6', label: 'Grew up in', value: 'India' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapIndian: [
          { key: 'age_height_list', label: 'Age / Height', value: '26 yrs, 5\' 11"' },
          { key: 'marital_status', label: 'Marital Status', value: 'Never Married' },
          { key: 'religion_caste_list', label: 'Religion', value: 'Sikh, Jat' },
          { key: 'location', label: 'Location', value: 'Ealing, United Kingdom' },
          { key: 'mother_tongue', label: 'Mother Tongue', value: 'Punjabi' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
        ],
        infoMapNri: [
          { key: 'age_height_list', label: 'Age / Height', value: '26 yrs, 5\' 11"' },
          { key: 'profession', label: 'Profession', value: 'Civil Engineer' },
          { key: 'religion_mother_tongue_list', label: 'Mother Tongue', value: 'Sikh, Punjabi' },
          { key: 'location_nri_info_list', label: 'Location', value: 'Lives in Ealing,Greater London / Middlesex, United Kingdom' },
          { key: 'education', label: 'Education', value: 'Bachelors - Arts' },
          { key: 'grew_up_in_info', label: 'Grew up in', value: 'Grew up in India' },
        ],
        listAlbum: [],
        gridAlbum: [],
        shortBio:
          "Hello, am glad you chose to visit my profile.\r\nI have completed my Bachelors.I value honesty, integrity and simplicity a lot.I don't expect perfection, would just like to find someone 'perfect' for me.",
        createdBy: 'Self',
        profileCreatedBy: 'Self',
        shortlistCount: -1,
      },
      detailed: {
        album: [],
        infoMap: [],
        about: { title: 'About', icon: 'about', desc: '' },
        lifestyle: { title: 'Lifestyle & Appearance', icon: 'lifestyle', items: [] },
        interests: { title: 'Interests & More', icon: 'interests', items: [] },
        background: { title: 'Background', icon: 'background', items: [] },
        education: { title: 'Education & Career', icon: 'education', items: [], hasCollegeOrEmployer: false },
        horoscope: { title: 'Horoscope Details', icon: 'astro', isGamified: false, items: [] },
        family: { title: 'Family Details', icon: 'family', isGamified: false, desc: '' },
        preferences: { title: 'Preferences Details', icon: 'preferences', isGamified: false, items: [] },
        trustBadges: [],
        commonInterests: [],
      },
      requests: { count: 0, items: [] },
      shortlists: { selected: [], ready: false, count: 0 },
      photos: { count: 0, items: [], status: '', hasPhotos: false, canAddPhotos: false, isDefault: true },
      astro: { details: {}, chart: {}, hasAstro: false },
      thumbnailBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-e8c391-male.jpg',
      thumbnail: 'https://img1.shaadi.com//2017/11/18/hSH62872162-e8c391-male.jpg',
      photoBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-8e8cbe-male.jpg',
      photo: 'https://img1.shaadi.com//2017/11/18/hSH62872162-8e8cbe-male.jpg',
      fullPhotoBlur: 'https://img1.shaadi.com//2017/11/18/hSH62872162-cbd4c8-male.jpg',
      fullPhoto: 'https://img1.shaadi.com//2017/11/18/hSH62872162-cbd4c8-male.jpg',
      drAction: { drAction: 'yes' },
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      gender: 'Male',
      tempId: '',
      se: 'd90c171deb2fc2a0a2e1bda07b7db74a',
      uid: 'hSH62872162',
      name: 'Sikander Singh Sekhon',
      fullName: 'Sikander singh Sekhon',
      firstName: 'Sikander singh',
      lastName: 'Sekhon',
      slug: 'hSH62872162',
      userHandle: 'SH62872162',
      location: 'Ealing, United Kingdom',
      mrMs: 'Mr.',
    },
  },
  firstActive: 'pSH37692174',
  defaultProfileId: '4SH57854000',
  evt_ref: 'ZGFpbHk1',
  disablePros: ['hSH62872162'],
};

const factory = { allData };

it('should export profiles and props', () => {
  expect(factory.allData).not.toBeFalsy();
});

export default factory;
