const FreeUserConnectChatWindow = {
  item: {
    uid: '6SH10710989',
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    hasUnread: false,
    photoLoading: false,
    eoiLoadingStyle: 'none',
    gamifiedCount: 0,
    order: -100,
    status: 'opened',
  },
  wwwBaseUrl: 'https://www.shaadi.com',
  canInitiateChat: false,
  settings: {
    defaultSearchFormat: 'list',
    isPaidUser: false,
    showUpgradeBanner: true,
    canAccessChat: true,
    canInitiateChat: false,
    hasUploadedPhoto: false,
    canConnectWithMessage: false,
    showUpgradeLinks: true,
    canSendPasswordOnConnect: false,
    contactsTotal: null,
    contactsRemaining: null,
    isUnderScreening: false,
    isAstroGamified: true,
    gender: 'Female',
    canViewCollegeAndEmployer: false,
    canViewHoroscope: true,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: true,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '9658567455',
    wasPaidUser: false,
    expiryDate: '',
    isNri: false,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: {
        bucket: 'A',
      },
      near_me: {
        bucket: 'A',
      },
      webCTA_Dec2017: {
        bucket: 'B',
      },
      premium_carousel: {
        bucket: 'A',
      },
      cartpage: {
        bucket: 'A',
      },
      cartpagenew: {
        bucket: 'A',
      },
      profile_verification: {
        bucket: 'B',
      },
      offline_otp: {
        bucket: 'B',
      },
      inbox_revamp: {
        bucket: 'A',
      },
      track_events: {
        bucket: 'A',
      },
      profilepage_revamp_abc: {
        bucket: 'A',
      },
      profilebooster_ab: {
        bucket: 'B',
      },
      featured_invite: {
        bucket: 'A',
      },
    },
    membershipTags: 'free',
    offerCode: 'octbd60h2',
    offer_details: [
      {
        type: 'perc',
        value: 60,
      },
    ],
  },
  flash: null,
  skew: {
    socket: 0,
    api: 609,
  },
  profile: {
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '32, 5\' 8"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Hindu, Brahmin - Madhwa',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Tamil',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Media Professional',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Chennai, India',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '32 yrs, 5\' 8", Hindu, Tamil',
        },
        {
          key: 'profession',
          value: 'Media Professional',
        },
        {
          key: 'location',
          value: 'Lives in Chennai, India',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '32, 5\' 8"',
        },
        {
          key: 'religion-caste',
          value: 'Hindu, Brahmin - Madhwa',
        },
        {
          key: 'profession',
          value: 'Media Professional',
        },
        {
          key: 'location',
          value: 'Chennai, India',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '32 yrs, 5\' 8", Hindu, Tamil',
        },
        {
          key: 'location',
          value: 'Chennai, India',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '32 yrs, 5\' 8", Hindu, Tamil',
        },
        {
          key: 'religion-caste',
          value: 'Brahmin - Madhwa',
        },
        {
          key: 'location',
          value: 'Lives in Chennai, India',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '32 yrs, 5\' 8", Hindu, Tamil',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
        {
          key: 'location',
          value: 'Lives in Chennai, India',
        },
      ],
    },
    flags: {
      canCommunicate: false,
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: "Invitation sent on 05 Apr 2018. He hasn't Viewed your Invitation yet.",
      connectionError: false,
      connectionStatus: 'contacted',
      connectionAction: 'member_contacted_today',
      connectionJustNowText: null,
      contactAction: 'free',
      contactStatus: 'available',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: false,
      isWatermarked: true,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: true,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l//hs/1',
      albumStatus: 'default',
      isIndianDiaspora: true,
      isHoroscopeApplicable: true,
      isFamilyGamified: true,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'Online',
      onlineStatusDetails: '...',
      onlineAt: 1522903688000,
      device: 'mobile_native-android',
      platform: 'mobile',
      lastOnline: 'Online on Android App',
      lastOnlineDetails: 'Online now',
      ready: true,
      chatIcon: 'app_online',
    },
    summary: {
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '32, 5\' 8"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Tamil',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Brahmin - Madhwa',
        },
        {
          key: 'nakshatra',
          label: 'Nakshatra',
          value: 'Dhanistha Nakshatra',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Chennai, India',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Media Professional',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '32, 5\' 8"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Hindu',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Tamil',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Chennai,Tamil Nadu, India',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Media Professional',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '32 yrs, 5\' 8"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Hindu, Brahmin - Madhwa',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Chennai, India',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Tamil',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Media Professional',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '32 yrs, 5\' 8"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Media Professional',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Hindu, Tamil',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Chennai,Tamil Nadu, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Masters - Management',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India',
        },
      ],
      listAlbum: [
        'https://img1.shaadi.com/2018/04/05/6SH10710989-b307da-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-5a90ee-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-efd7b8-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-3521f2-male.webp',
      ],
      gridAlbum: [
        'https://img1.shaadi.com/2018/04/05/6SH10710989-b3a605-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-5af7ea-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-ab619d-male.webp',
        'https://img1.shaadi.com/2018/04/05/6SH10710989-5e1d9b-male.webp',
      ],
      shortBio:
        "Hi, thank you for visiting my brother's profile.\rHe has completed his Masters.He enjoys being around people and believes in living life with positivity.\rThank you for your valuable time and if you wish to take things forward, you are highly welcome.",
      createdBy: 'Sibling',
      profileCreatedBy: 'Sibling',
      shortlistCount: 0,
    },
    detailed: {
      album: ['https://img1.shaadi.com/2018/04/05/6SH10710989-b3a605-male.webp'],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: true,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: '',
      hasPhotos: false,
      canAddPhotos: false,
      isDefault: true,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: '',
      horoscope_status: '',
      memberlogin: '',
      phone: '',
      photo: '',
      photo_password: null,
      profile_privacy: '',
      shortlist_setting: '',
      sms_alert: 0,
      visitors_setting: '',
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img1.shaadi.com/2018/04/05/6SH10710989-f1df03-male.webp',
    thumbnail: 'https://img1.shaadi.com/2018/04/05/6SH10710989-f1df03-male.webp',
    photoBlur: 'https://img1.shaadi.com/2018/04/05/6SH10710989-b307da-male.webp',
    photoMedium: '/assets/default-photo.png',
    photo: 'https://img1.shaadi.com/2018/04/05/6SH10710989-b307da-male.webp',
    fullPhotoBlur: 'https://img1.shaadi.com/2018/04/05/6SH10710989-b3a605-male.webp',
    fullPhoto: 'https://img1.shaadi.com/2018/04/05/6SH10710989-b3a605-male.webp',
    drAction: {},
    heShe: 'He',
    himHer: 'Him',
    hisHer: 'His',
    gender: 'Male',
    tempId: '',
    verification: {
      count: 1,
      shield_state: 'HOLLOW',
      derived_text: 'Mobile number verified',
      verified_proofs: ['Mobile number Verified'],
    },
    se: '72f4dda743dd8fab87089f265d290785',
    uid: '6SH10710989',
    name: 'Nagaraj R',
    fullName: 'Nagaraj R',
    firstName: 'Nagaraj',
    lastName: 'R',
    slug: '6SH10710989',
    userHandle: 'SH10710989',
    location: 'Chennai, India',
    mrMs: 'Mr.',
  },
  me: {
    base: {
      infoMap: [
        {
          key: 'info-0',
          label: 'Age / Height',
          value: '30, 5\' 6"',
        },
        {
          key: 'info-1',
          label: 'Religion/Community',
          value: 'Buddhist, Buddhist',
        },
        {
          key: 'info-2',
          label: 'Mother Tounge',
          value: 'Marathi',
        },
        {
          key: 'info-3',
          label: 'Profession',
          value: 'Not Specified',
        },
        {
          key: 'info-4',
          label: 'Location',
          value: 'Bihar Sharif, India',
        },
      ],
      infoList: [
        {
          key: 'age-height',
          value: '30 yrs, 5\' 6", Buddhist, Marathi',
        },
        {
          key: 'location',
          value: 'Lives in Bihar Sharif, India',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
      ],
      detailList: [
        {
          key: 'age-height',
          value: '30, 5\' 6"',
        },
        {
          key: 'religion-caste',
          value: 'Buddhist, Not Specified',
        },
        {
          key: 'profession',
          value: 'Not specified',
        },
        {
          key: 'location',
          value: 'Bihar Sharif, India',
        },
      ],
      premiumInfo: [
        {
          key: 'age-height',
          value: '30 yrs, 5\' 6", Buddhist, Marathi',
        },
        {
          key: 'location',
          value: 'Bihar Sharif, India',
        },
      ],
      miniList: [
        {
          key: 'age-height',
          value: '30 yrs, 5\' 6", Buddhist, Marathi',
        },
        {
          key: 'religion-caste',
          value: 'Not Specified',
        },
        {
          key: 'location',
          value: 'Lives in Bihar Sharif, India',
        },
      ],
      miniNriList: [
        {
          key: 'age-height',
          value: '30 yrs, 5\' 6", Buddhist, Marathi',
        },
        {
          key: 'grew up in',
          value: 'Grew up in India',
        },
        {
          key: 'location',
          value: 'Lives in Bihar Sharif, India',
        },
      ],
    },
    flags: {
      canCommunicate: false,
      isFree: true,
      isPremium: false,
      membershipLevel: 'Free',
      connectionNote: null,
      connectionError: false,
      connectionStatus: 'unknown',
      connectionAction: 'not_contacted',
      connectionJustNowText: null,
      contactAction: 'none',
      contactStatus: 'none',
      horoscopeStatus: 'none',
      loading: 'none',
      isDeleted: false,
      isNri: false,
      isWatermarked: false,
      isTwoWayMatch: false,
      isBoldListing: false,
      canUnblock: false,
      unblockMessage: null,
      canUnignore: false,
      canRemind: false,
      canCancelInvite: false,
      isSameGender: false,
      activeStatus: 'default',
      isPreferredMatch: false,
      isConnectLimitExceeded: false,
      showHistory: false,
      membershipTags: 'free',
      isNameLocked: true,
      canCallSendSMS: false,
      canSendEmail: false,
      canSendEmailReminder: false,
      canSendSMS: false,
      canViewPhoneNo: false,
      isPhoneNoViewed: false,
      isSmsAlreadySent: false,
      showChatNow: false,
      showPostOnWall: false,
      isFiltered: false,
      isSkipped: false,
      isProfileViewed: false,
      canViewPhotosOnConnectOnly: false,
      canPremiumMemberViewPhoto: false,
      horoscopeStyle: 'l/ENG/hs/1',
      albumStatus: 'noPhoto',
      isIndianDiaspora: true,
      isHoroscopeApplicable: true,
      isFamilyGamified: true,
      isAstroReady: false,
      isHidden: false,
      hiddenReason: null,
      isBothPartyPayUser: false,
    },
    presence: {
      onlineStatus: 'invisible',
      onlineStatusDetails: '...',
      onlineAt: 0,
      device: 'none',
      platform: 'none',
      lastOnline: '...',
      lastOnlineDetails: '...',
      ready: false,
      chatIcon: 'none',
    },
    summary: {
      infoMap: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '30, 5\' 6"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Buddhist',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Marathi',
        },
        {
          key: 'community',
          label: 'Community',
          value: 'Buddhist',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Bihar Sharif, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Not Specified',
        },
      ],
      infoMapNonIndian: [
        {
          key: 'age_height',
          label: 'Age / Height',
          value: '30, 5\' 6"',
        },
        {
          key: 'religion',
          label: 'Religion',
          value: 'Buddhist',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Marathi',
        },
        {
          key: 'location_nri_info',
          label: 'Location',
          value: 'Bihar Sharif,Bihar, India',
        },
        {
          key: 'info-6',
          label: 'Grew up in',
          value: 'India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Not Specified',
        },
      ],
      infoMapIndian: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '30 yrs, 5\' 6"',
        },
        {
          key: 'marital_status',
          label: 'Marital Status',
          value: 'Never Married',
        },
        {
          key: 'religion_caste_list',
          label: 'Religion',
          value: 'Buddhist, Buddhist',
        },
        {
          key: 'location',
          label: 'Location',
          value: 'Bihar Sharif, India',
        },
        {
          key: 'mother_tongue',
          label: 'Mother Tongue',
          value: 'Marathi',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Not Specified',
        },
      ],
      infoMapNri: [
        {
          key: 'age_height_list',
          label: 'Age / Height',
          value: '30 yrs, 5\' 6"',
        },
        {
          key: 'profession',
          label: 'Profession',
          value: 'Not Specified',
        },
        {
          key: 'religion_mother_tongue_list',
          label: 'Mother Tongue',
          value: 'Buddhist, Marathi',
        },
        {
          key: 'location_nri_info_list',
          label: 'Location',
          value: 'Lives in Bihar Sharif,Bihar, India',
        },
        {
          key: 'education',
          label: 'Education',
          value: 'Bachelors - Commerce',
        },
        {
          key: 'grew_up_in_info',
          label: 'Grew up in',
          value: 'Grew up in India',
        },
      ],
      listAlbum: [],
      gridAlbum: [],
      shortBio: "Hello, I'm glad you are interested in my daughter's profile.\r\n She has completed her Bachelors.",
      createdBy: 'Parent / Guardian',
      profileCreatedBy: 'Parent',
      shortlistCount: -1,
    },
    detailed: {
      album: ['https://img2.shaadi.com/imgs/my-shaadi/ver2/250-photo-not-added-f.gif'],
      infoMap: [],
      about: {
        title: 'About',
        icon: 'about',
        desc: '',
      },
      lifestyle: {
        title: 'Lifestyle & Appearance',
        icon: 'lifestyle',
        items: [],
      },
      interests: {
        title: 'Interests & More',
        icon: 'interests',
        items: [],
      },
      background: {
        title: 'Background',
        icon: 'background',
        items: [],
      },
      education: {
        title: 'Education & Career',
        icon: 'education',
        items: [],
        hasCollegeOrEmployer: false,
      },
      horoscope: {
        title: 'Horoscope Details',
        icon: 'astro',
        isGamified: false,
        items: [],
      },
      family: {
        title: 'Family Details',
        icon: 'family',
        isGamified: false,
        desc: '',
      },
      preferences: {
        title: 'Preferences Details',
        icon: 'preferences',
        isGamified: false,
        items: [],
      },
      trustBadges: [],
      commonInterests: [],
    },
    requests: {
      count: 0,
      items: [],
    },
    shortlists: {
      selected: [],
      ready: false,
      count: 0,
    },
    photos: {
      count: 0,
      items: [],
      status: 'add_photo',
      hasPhotos: false,
      canAddPhotos: true,
      isDefault: false,
      isRejectedPhotosFetched: false,
    },
    astro: {
      details: {},
      chart: {},
      hasAstro: false,
    },
    privacy: {
      display_name: 'partial_name',
      horoscope_status: 'None',
      memberlogin: 'mSH10666126',
      phone: 'Show All',
      photo: 'Show All',
      photo_password: 'null',
      profile_privacy: 'Show All',
      shortlist_setting: 'N',
      sms_alert: 0,
      visitors_setting: 'N',
      isDefault: false,
    },
    contactSummary: {
      sms: '',
      contact: {},
      actionDate: '',
      dnd: '',
      hidden: '',
      hiddenReason: '',
      tempKey: '',
      contactType: '',
      photoStatus: '',
      photoCount: 0,
      profileContactStatus: '',
      contactDetailsStatusString: '',
      contactDetailsTitleStatusString: '',
    },
    connectMessages: [],
    thumbnailBlur: 'https://img2.shaadi.com/imgs/my-shaadi/ver2/60-add-ph-female-v2.gif',
    thumbnail: 'https://img2.shaadi.com/imgs/profiles/60-no-border-female.gif',
    photoBlur: 'https://img2.shaadi.com/imgs/profile/photoclicktoupload.gif',
    photoMedium: '/assets/default-photo.png',
    photo: 'https://img2.shaadi.com/imgs/profiles/150-no-border-female.gif',
    fullPhotoBlur: 'https://img2.shaadi.com/imgs/my-shaadi/ver2/250-photo-not-added-f.gif',
    fullPhoto: '/assets/60-add-ph-female-v2.gif',
    drAction: {},
    heShe: 'She',
    himHer: 'Her',
    hisHer: 'Her',
    gender: 'Female',
    tempId: '',
    verification: {
      count: 0,
      shield_state: '',
      derived_text: '',
      verified_proofs: [],
    },
    uid: 'mSH10666126',
    name: 'Puju S',
    fullName: 'Puju Soni',
    firstName: 'Puju',
    lastName: 'Soni',
    slug: 'mSH10666126',
    userHandle: 'SH10666126',
    location: 'Bihar Sharif, India',
    mrMs: 'Ms.',
  },
  history: {
    loading: null,
    typing: null,
    flash: null,
    flashType: 'default',
    items: [
      {
        messageId: 'chat-mSH10666126-6SH10710989-1507-2022-1522904393',
        chatUid: 'mSH10666126',
        from: 'mSH10666126',
        to: '6SH10710989',
        body: 'Hello! We came across your profile and it caught our attention. We can connect if you too like this profile.',
        time: '10:29AM',
        t: 1522904393000,
        isSelf: true,
        isDeleted: false,
        status: 'sent',
        timeAgo: 'few mins ago',
        source: 'api',
      },
    ],
    mark: 1522904393000,
    chatUid: '6SH10710989',
  },
  doChatWindowAction() {},
  onProfileAction() {},
  onStartTyping() {},
  onStopTyping() {},
  doSendMessage() {},
  fetchChatHistory() {},
  markAsRead() {},
};

const componentWillreceiveChangeProps = {
  ...FreeUserConnectChatWindow,
  item: {
    ...FreeUserConnectChatWindow.item,
    order: 4,
    status: 'opened',
  },
  settings: {
    ...FreeUserConnectChatWindow.settings,
    canInitiateChat: true,
  },
  flash: 'free member',
  history: {
    loading: null,
    typing: null,
    flash: null,
    flashType: 'default',
    since: 20180401220249,
    hide_message: false,
    items: [
      {
        messageId: '182ed615-d852-4fee-89fa-eafc35560012',
        chatUid: '1SH27475068',
        from: 'JSH26295881',
        to: '1SH27475068',
        body: 'hello good morning',
        time: '12:37PM',
        t: 1522566424000,
        isSelf: false,
        isDeleted: false,
        status: 'read',
        timeAgo: 'yesterday',
        source: 'api',
      },
      {
        messageId: '182ed615-d852-4fee-89fa-eafc35560012',
        chatUid: '1SH27475068',
        from: 'JSH26295881',
        to: '1SH27475068',
        body: 'hello good hhhhh morning',
        time: '12:37PM',
        t: 1522566424000,
        isSelf: false,
        isDeleted: false,
        status: 'read',
        timeAgo: 'yesterday',
        source: 'api',
      },
    ],
    mark: 1522904393666,
    chatUid: '6SH10710989',
  },
};

const chatWinodwProps = {
  ...FreeUserConnectChatWindow,
  item: {
    uid: '6SH10710989',
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'none',
      title: null,
      body: [],
      loading: false,
    },
    hasUnread: false,
    photoLoading: false,
    eoiLoadingStyle: 'none',
    gamifiedCount: 0,
    order: -100,
    status: 'minimized',
  },
};

const factory = {
  FreeUserConnectChatWindow,
  componentWillreceiveChangeProps,
  chatWinodwProps,
};
it('should export chatWinodw Props', () => {
  expect(factory.FreeUserConnectChatWindow).not.toBeFalsy();
});
export default factory;
