const props = {
  items: {
    items: [
      {
        uid: 'OSH95198972',
        photoLoading: false,
        changeCursorStatus: true,
        displayStatusMessage: '',
        viewSmsShowStatus: false,
      },
    ],
    tooltip: {
      key: 'none',
      page: 'none',
      position: 'photo',
      title: null,
      body: [],
      loading: false,
    },
  },
  tooltip: {
    key: 'none',
    page: 'none',
    position: 'photo',
    title: null,
    body: [],
    loading: false,
  },
  topSpace: 0,
  windowWidth: 1341,
  isChatOpen: true,
  wwwBaseUrl: 'https://www.shaadi.com',
  profiles: {
    OSH95198972: {
      base: {
        infoMap: [
          {
            key: 'info-0',
            label: 'Age / Height',
            value: '30, 5\' 5"',
          },
          {
            key: 'info-1',
            label: 'Religion/Community',
            value: 'Hindu, Boyer',
          },
          {
            key: 'info-2',
            label: 'Mother Tounge',
            value: 'Tamil',
          },
          {
            key: 'info-3',
            label: 'Profession',
            value: 'Electronics / Telecom Engineer',
          },
          {
            key: 'info-4',
            label: 'Location',
            value: 'Tiruchirappalli, India',
          },
        ],
        infoList: [
          {
            key: 'age-height',
            value: '30 yrs, 5\' 5", Hindu, Tamil',
          },
          {
            key: 'profession',
            value: 'Electronics / Telecom Engineer',
          },
          {
            key: 'location',
            value: 'Lives in Tiruchirappalli, India',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
        ],
        detailList: [
          {
            key: 'age-height',
            value: '30, 5\' 5"',
          },
          {
            key: 'religion-caste',
            value: 'Hindu, Boyer',
          },
          {
            key: 'profession',
            value: 'Electronics / Telecom Engineer',
          },
          {
            key: 'location',
            value: 'Tiruchirappalli, India',
          },
        ],
        premiumInfo: [
          {
            key: 'age-height',
            value: '30 yrs, 5\' 5", Hindu, Tamil',
          },
          {
            key: 'location',
            value: 'Tiruchirappalli, India',
          },
        ],
        miniList: [
          {
            key: 'age-height',
            value: '30 yrs, 5\' 5", Hindu, Tamil',
          },
          {
            key: 'religion-caste',
            value: 'Boyer',
          },
          {
            key: 'location',
            value: 'Lives in Tiruchirappalli, India',
          },
        ],
        miniNriList: [
          {
            key: 'age-height',
            value: '30 yrs, 5\' 5", Hindu, Tamil',
          },
          {
            key: 'grew up in',
            value: 'Grew up in India',
          },
          {
            key: 'location',
            value: 'Lives in Tiruchirappalli, India',
          },
        ],
      },
      flags: {
        isFree: true,
        isPremium: false,
        membershipLevel: 'Free',
        connectionNote: 'He sent you an Invitation on 16 Feb 2018.',
        connectionError: false,
        connectionStatus: 'theyContacted',
        connectionAction: 'profile_contacted',
        connectionJustNowText: null,
        contactAction: 'none',
        contactStatus: 'none',
        horoscopeStatus: 'none',
        loading: 'none',
        isDeleted: false,
        isNri: false,
        isWatermarked: true,
        isTwoWayMatch: false,
        isBoldListing: true,
        canUnblock: false,
        unblockMessage: null,
        canUnignore: false,
        canRemind: false,
        canCancelInvite: false,
        isSameGender: false,
        activeStatus: 'default',
        isPreferredMatch: false,
        isConnectLimitExceeded: false,
        showHistory: false,
        membershipTags: 'free',
        isNameLocked: false,
        canCallSendSMS: false,
        canSendEmail: false,
        canSendEmailReminder: false,
        canSendSMS: false,
        canViewPhoneNo: false,
        isPhoneNoViewed: false,
        isSmsAlreadySent: false,
        showChatNow: false,
        showPostOnWall: false,
        isFiltered: false,
        isSkipped: false,
        isProfileViewed: false,
        horoscopeStyle: 'l/ENG/hs/1',
        albumStatus: 'default',
        isIndianDiaspora: true,
        isHoroscopeApplicable: true,
        isFamilyGamified: false,
        isAstroReady: false,
        isHidden: false,
        hiddenReason: null,
        isBothPartyPayUser: false,
      },
      presence: {
        onlineStatus: 'invisible',
        onlineStatusDetails: '...',
        onlineAt: 0,
        device: 'none',
        platform: 'none',
        lastOnline: '...',
        lastOnlineDetails: '...',
        ready: false,
        chatIcon: 'none',
      },
      summary: {
        infoMap: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '30, 5\' 5"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Tamil',
          },
          {
            key: 'community',
            label: 'Community',
            value: 'Boyer',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Tiruchirappalli, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Electronics / Telecom Engineer',
          },
        ],
        infoMapNonIndian: [
          {
            key: 'age_height',
            label: 'Age / Height',
            value: '30, 5\' 5"',
          },
          {
            key: 'religion',
            label: 'Religion',
            value: 'Hindu',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Tamil',
          },
          {
            key: 'location_nri_info',
            label: 'Location',
            value: 'Tiruchirappalli,Tamil Nadu, India',
          },
          {
            key: 'info-6',
            label: 'Grew up in',
            value: 'India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Electronics / Telecom Engineer',
          },
        ],
        infoMapIndian: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '30 yrs, 5\' 5"',
          },
          {
            key: 'marital_status',
            label: 'Marital Status',
            value: 'Never Married',
          },
          {
            key: 'religion_caste_list',
            label: 'Religion',
            value: 'Hindu, Boyer',
          },
          {
            key: 'location',
            label: 'Location',
            value: 'Tiruchirappalli, India',
          },
          {
            key: 'mother_tongue',
            label: 'Mother Tongue',
            value: 'Tamil',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Electronics / Telecom Engineer',
          },
        ],
        infoMapNri: [
          {
            key: 'age_height_list',
            label: 'Age / Height',
            value: '30 yrs, 5\' 5"',
          },
          {
            key: 'profession',
            label: 'Profession',
            value: 'Electronics / Telecom Engineer',
          },
          {
            key: 'religion_mother_tongue_list',
            label: 'Mother Tongue',
            value: 'Hindu, Tamil',
          },
          {
            key: 'location_nri_info_list',
            label: 'Location',
            value: 'Lives in Tiruchirappalli,Tamil Nadu, India',
          },
          {
            key: 'education',
            label: 'Education',
            value: 'Bachelors - Engineering/ Technology',
          },
          {
            key: 'grew_up_in_info',
            label: 'Grew up in',
            value: 'Grew up in India',
          },
        ],
        listAlbum: [],
        gridAlbum: [],
        shortBio:
          'Hi,\r\n\r\n I am currently working  with chennai and have done my Bachelors from Anna University.  My father is not employed, my mother is a homemaker.I like to loving and carring life partner .',
        createdBy: 'Self',
        profileCreatedBy: 'Self',
        shortlistCount: -1,
      },
      detailed: {
        album: [],
        infoMap: [],
        about: {
          title: 'About',
          icon: 'about',
          desc: '',
        },
        lifestyle: {
          title: 'Lifestyle & Appearance',
          icon: 'lifestyle',
          items: [],
        },
        interests: {
          title: 'Interests & More',
          icon: 'interests',
          items: [],
        },
        background: {
          title: 'Background',
          icon: 'background',
          items: [],
        },
        education: {
          title: 'Education & Career',
          icon: 'education',
          items: [],
          hasCollegeOrEmployer: false,
        },
        horoscope: {
          title: 'Horoscope Details',
          icon: 'astro',
          isGamified: false,
          items: [],
        },
        family: {
          title: 'Family Details',
          icon: 'family',
          isGamified: false,
          desc: '',
        },
        preferences: {
          title: 'Preferences Details',
          icon: 'preferences',
          isGamified: false,
          items: [],
        },
        trustBadges: [],
        commonInterests: [],
      },
      requests: {
        count: 0,
        items: [],
      },
      shortlists: {
        selected: [],
        ready: false,
        count: 0,
      },
      photos: {
        count: 0,
        items: [],
        status: '',
        hasPhotos: false,
        canAddPhotos: false,
        isDefault: true,
        isRejectedPhotosFetched: false,
      },
      astro: {
        details: {},
        chart: {},
        hasAstro: false,
      },
      privacy: {
        display_name: '',
        horoscope_status: '',
        memberlogin: '',
        phone: '',
        photo: '',
        photo_password: null,
        profile_privacy: '',
        shortlist_setting: '',
        sms_alert: 0,
        visitors_setting: '',
      },
      contactSummary: {
        sms:
          'Msg from Sami L (SH88709866): Hi, I liked the Profile that you have posted on Shaadi.com. Please visit my Profile and respond.',
        contact: {
          profileid: 'nSH37634787',
          convenient_time: '',
          from_time_hours: 0,
          from_time_min: 0,
          last_update_date: 20161209003134,
          mob_isd: '+968',
          mob_std: '',
          mobile: '93175558',
          mobile_country: 'Oman',
          mobile_verified: 'Y',
          name: '',
          relation: '',
          tel_isd: '+968',
          tel_std: '',
          telephone: '',
          telephone_country: 'Oman',
          telephone_verified: 'N',
          timezone: '',
          to_time_hours: 0,
          to_time_min: 0,
          contact_details_status: 'show_all',
          contact_details_title_status: 'show_all',
        },
        actionDate: '05 Sep 2017',
        dnd: 'N',
        hidden: 'N',
        hiddenReason: false,
        tempKey: 'bef182c3bc31db1ed70d91f0e3de11bb',
        contactType: 'Contact_viewed',
        photoStatus: 'show_photo',
        photoCount: 20,
        profileContactStatus: 'accepted',
        contactDetailsStatusString: 'available',
        contactDetailsTitleStatusString: 'available',
      },
      connectMessages: [],
      thumbnailBlur: 'https://img1.shaadi.com/2017/11/25/OSH95198972-6567ea-male.webp',
      thumbnail: 'https://img1.shaadi.com/2017/11/25/OSH95198972-6567ea-male.webp',
      photoBlur: 'https://img1.shaadi.com/2017/11/25/OSH95198972-1fd21c-male.webp',
      photoMedium: '/assets/default-photo.png',
      photo: 'https://img1.shaadi.com/2017/11/25/OSH95198972-1fd21c-male.webp',
      fullPhotoBlur: 'https://img1.shaadi.com/2017/11/25/OSH95198972-721d4e-male.webp',
      fullPhoto: 'https://img1.shaadi.com/2017/11/25/OSH95198972-721d4e-male.webp',
      drAction: {},
      heShe: 'He',
      himHer: 'Him',
      hisHer: 'His',
      gender: 'Male',
      tempId: '',
      se: 'f8b60c843eeb79e0feb9186d807b3cbe',
      uid: 'OSH95198972',
      name: 'N Suresh',
      fullName: 'n suresh',
      firstName: 'n',
      lastName: 'suresh',
      slug: 'OSH95198972',
      userHandle: 'SH95198972',
      location: 'Tiruchirappalli, India',
      mrMs: 'Mr.',
    },
  },
  meta: {
    loading: false,
    results_id: 'contacts:9d347dde80ed5c27569f7d50163d3e1d',
    total: 108,
    page: '8',
    pages: 11,
    permaLink: '/inbox/contact-summary?pg_searchresults_id=contacts%3A9d347dde80ed5c27569f7d50163d3e1d&page=8',
  },
  settings: {
    defaultSearchFormat: 'grid',
    isPaidUser: true,
    showUpgradeBanner: false,
    canAccessChat: true,
    canInitiateChat: true,
    hasUploadedPhoto: true,
    canConnectWithMessage: true,
    showUpgradeLinks: false,
    canSendPasswordOnConnect: false,
    contactsTotal: 270,
    contactsRemaining: 97,
    isUnderScreening: false,
    isAstroGamified: false,
    gender: 'Female',
    canViewCollegeAndEmployer: true,
    canViewHoroscope: false,
    horoscopeStyle: 'l/ENG/hs/1',
    isFamilyGamified: true,
    isHidden: false,
    isBothPartyPayUser: false,
    isMobileVerified: false,
    mobileNumber: '8767676565',
    wasPaidUser: false,
    expiryDate: '04-Mar-18',
    isNri: true,
    isIndianDiaspora: true,
    experiments: {
      premium_tag: { bucket: 'A' },
      near_me: { bucket: 'A' },
      webCTA_Dec2017: { bucket: 'B' },
      premium_carousel: { bucket: 'A' },
      cartpage: { bucket: 'A' },
      profile_verification: { bucket: 'C' },
      offline_otp: { bucket: 'B' },
      inbox_revamp: { bucket: 'A' },
    },
    membershipTags: 'gold',
    offerCode: 'match15to1',
    offer_details: '',
  },
  doContactSummary() {},
  doProfileAction() {},
  membership: {
    accountType: 'PAID',
    plan: 'Gold',
    planExpiryDate: '04-Mar-18',
    planDaysToExpiry: 9,
    headerUpgradeLink: '/payment?source=top_navbar_upgrade',
    callSmsViewed: 173,
    callSmsBalance: 97,
    services: [],
    wasPaidUser: false,
    upgradeType: 'renew',
  },
  location: {
    pathname: '/inbox/contact-summary',
    search: '?pg_searchresults_id=contacts%3A9d347dde80ed5c27569f7d50163d3e1d&page=8',
    hash: '',
    key: 'nbrsnp',
  },
  onPageChange() {},
};

const factory = { props };

it('should export props', () => {
  expect(Object.keys(factory).length).toEqual(1);
});
export default factory;
